/* ========================================================================
   === GAMEPLAY & DIFFICULTY TUNING (TWEAK HERE) ===
   ======================================================================== */
const SKIP_TO_GAMEPLAY = false; // Set to true to skip menus and go straight to game
const W = 800; // Game screen width in pixels
const H = 600; // Game screen height in pixels

// Difficulty: 0 = EASY (sparse notes), 1 = MEDIUM (standard), 2 = HARD (fast dense streams)
const DEFAULT_DIFFICULTY = 1;
// Minimum seconds between notes per difficulty mode [EASY, MEDIUM, HARD] (higher = more spaced out notes)
const DIFFICULTY_GAPS = [0.24, 0.14, 0];

// Receptor arrow bounce animation on hit
const BOUNCE_SCALE = 0.25;  // Scale pulse on hit (+25% size boost; increase e.g. 0.4 - 0.6 for bigger pop)
const BOUNCE_Y = 8;          // Vertical displacement in pixels (hops upward by 8px on hit)
const BOUNCE_DECAY = 0.005;  // Decay rate per ms (lower = longer bounce, higher = snappier)

// Hit window & timing tolerances (in pixels)
const HIT_WIN = 50;          // Total hit window in pixels (~145ms window, DDR/FNF standard Good)
const PERFECT_WIN = 18;      // Perfect hit window in pixels (~52ms window for precision bonus)
const MISS_TOL = 50;         // Distance in pixels beyond hit line before a note is auto-missed

// Tug-of-war bar balance & damage/penalty values
const BAR_MAX = 100;         // Tug-of-war meter limit (+100 = Player 1 wins, -100 = Player 2 wins)
const DMG_PERFECT = 2.0;     // Bar shift amount awarded on a Perfect hit
const DMG_GOOD = 1.0;        // Bar shift amount awarded on a Good hit
const MISS_PEN = 2.5;        // Bar penalty deducted on Miss or empty ghost tap

// Note travel speed & layout
const HIT_Y = 518;           // Vertical screen position (Y coordinate in px) of receptor hit line
const TRAVEL_TIME = 1.5;     // Fall duration in seconds from top of screen to hit line
const ARROW_SCALE = 5.2;     // Base visual scale multiplier for arrow sprites
const LEAD_IN = 2;           // Lead-in delay in seconds before notes appear
const SEC_LEN = 8;           // Duration in seconds of each player's alternating turn
const PAD = 160;             // Background margin padding in pixels for camera pans
/* ======================================================================== */

/* === MIDI SONGS (generated by tools/midi_to_string/embed.py) === */
// Generated automatically - do not edit by hand.
// Re-run: python tools/midi_to_string/embed.py
// Each constant packs one .mid losslessly (M5 -> deflate -> base64url).
// MIDI_SONG_BARRANQUILLA: 3744 chars base64, about 120s of music.
// MIDI_SONG_FRUKO_Y_SUS_TESOS: 2972 chars base64, about 120s of music.
// MIDI_SONG_LOBA: 5228 chars base64, about 120s of music.
// MIDI_SONG_NUESTRA_CANCION: 5908 chars base64, about 120s of music.
// var MIDI_SONG is the default song played by create(); swap it to any
// MIDI_SONG_* below to make the game play that track instead.

var MIDI_SONG_BARRANQUILLA = "eNrtW21v20YS_i0LiqJlcqsEbZHrHVCndRLZlsWTZcmBbUiqBIGyJUjVSZfmS8rf3n2ZfV9StJtzkoPRAqa4O7M788zMzs4wnR8_Rf_69LJ2kQdHeZjXRnnwUx7-mR_m4SJvvM8PyIu7_Ic8GeXRUZ7g_FMf5Y1__NKqozwI8wZa3_6AUas2hl-XR_ovMlZvBa_5r9Xt99rYpv-zNaZ-LcmvBqwQogX5FUV5KyKjdTK6veo3cWNd3-U19AtO1sG9_vBWPJzgJGUPbRxe5mnYJ4_vcP2UMLp_mq032NbJThGR4gIHazKp-gNZzXgT0vXDWh6gbgsfUqTcF4dkpZC-ODvHtXxL_mvt-JvztMKb7pn1ZvDWnvP-WLxJd3kdbZLGn3mK8gitDsnTGuUxase4BfsYHPX4zujmQCf3t69iRCbWUBdHUoR0g0NqgnQWBXnVe92L61x2sqIgnuvEdDRGaRysqYK7-IC_aMc1gwuSr9m8czKPMjjFMR2oo20SrqkEa_ZX0qu9-pahonOyVRL6lktj-prI1kCjnwXNOokZzTKJxRJLKdGpLdEAHzC7ojzWx1wbcnv05Za-pKQdHDqDS40Cg-RSsIysKkgjvrdFErC9ZQlffYQlqwWwqhNh-aQFTDpXk1Zy0gakXLG_xrozKW2HW7apWJ8sVLGLEhzfcRwN3LIS3JZKTsF-KdlTiAKAKGDW4MVxCxKuFY7KMlNbsgHsNMVNiefSh6cX5B15mYJen53t2dmene1_7Gym8iewNXA06j7nIzhuZQokdtMW-G6AepYEPnZMoUIhW-l91C64nY-4nfP8wvFCzenPRy3p9JzFHFjccBbSdJl393AgXn4Q9ix9M0siRnnN_hqmtFIYS0U00E1LpCdgv1IcJF8b46YPSuyEz9DpfCA0yEwZLjwynAgZhEVNXcf6-Bhsl0Lwh2G6Kcd0oXlmFUwzYHGtMN34MN0JfbwT-lgCpmMX0_vqmJLc-LIM0zs30tiYdjyYrn2YZkKGdgnFs39-M_6Zcv8kucejPRShVVzRU_liHpQpl00clLEv8eAIUI_Y9EUc6Z7c8HqysUeReQ36_IV0UjJAzy7GLyL8fru4-umKvCF3xjr6b_JixBO-_8ATQnfxi1GupU489ev8SjI6mdNFRJRxb_DPq7j5R57ypSjVC3KBRR2iJViVGmKAeiBAjwjABuihb5yp5wx3c6ZIFtVMjSRA7-IXION3fKATywzgut-7jA8NDj5WsA0-xDbWAeYdGWxCY-oXkMmgQSjDoeSuM0FohmXC66GR7DziObR-MdnMqaURhMY4gtTqqbD8OrUQ_w0tpFwL30m_dfUwvbzo77Vpuo8i-Sem_Jrc0yK527D5tpA7c-Se4aZXbou0QG4RS24urvoxFZ_Fkje4eZQbDiCwcUUXtuC6NUJDjYb4qHghuRpTg4fddt8IlQxxIB9EVC6-_tLTmYf6yUse6mcvnbN2bqcTxddilRt5b1Ndz23KfwtmV5lKt94dhpsy-4vQHIcVNj4Q5PeYn4z8r1CbdedcwaQVTJpIeGpGesqRgOxlA0QbIJq5ROr2tYPJO5g8VwbA9gt5kqEwclMEqi1QZVimGGVsJbq2MRTxKzOG4r07l-MtQLUFqDJs1ET21VS6QrMC8p2CvEJtpc-DBQUmBGBCAKa8xkLSmi1kMUViPMTidjiC3Uew-8i2uFLL8lqQbimhx1JWsOd7Mkrj1b6wsIb5SxWzqocDquIIHCZ6BMIVkZS-XhG5ByIl2ZchIy5CoRn85dElUOkq_W3sldVpIq8nXeWfO3oVrYszM7K5_S659Ww5-p5a105ebJX2-2x1uh1X--vCWpehfZ2tJ0obml8V79in-blP88tjqcIHaN45Lo3wn3JfPsoFFCnfyVGevoYR-WbtOxUEil1_cDXPA2Nje4Pq3ii218UEyKUuZsvk9Wwphbucb9ueI_sjTPqoDjWPBj6AgB-0hMowkrF7VBcdzZabTtUkO9XGxUVlmTuOsCRzjtO55q4zN3jOio1f-tXMRDRiXN-_uiyKmnAuOBmGAa0a9a1Xsccg5-7plkiIplUj6JuCS0-d-B0_SqbyKMGyf2EU5PlNRd2ICs-5peaUGRjZFM7yMY583QyrdmmpMNKvLKZ6BrQkSQbvPLj1RD6zwDFsIra5ZOXZ8bIYL9mhnxfv3-dKyzJXWolcpOdxJb1mCQ08_OqI13OW9EmLkuJS90BXc8ge53ICicoup66TrsuVulporpMVuVrgc7WoJFkRIgysG5gZDacKV9fVJuKqOJHbbYq8afCrWWwce10shXwYinb0oejOOWUgpWN7_nrMDoQQDgThhU5vb7TXC1VivnaPxKkn73H88A8_PV1-WNLz05b1Lec9Aj9AVFsrkG9L_VT29mYS3KHrevNjiVIoPduMp_ew8gSuH5Pio29o50uaP07co2-ixdV70MkEEJ24fjmscI_wszGQnVS5Mc5ZWSgi2mgyPlMoE2kI3xRHWqrZsTy-7DgLqp8eqzMlhk3HYtNikWtZPU_LYjF_GLn4jrWefAqzvz_K7WlT_VZYVkAyTs7CzyWW_s8l9h-MngOxzAMffPI1aB2NL1-3S6hfruQfsgDQ_3-p-EuRBp9VJE8WnhnHpqfOnQnXyIoS-Kqy64sFvvzY0YWqS5fCLEre3zzc668Bbru8nz0JzEEhzAhOkK9LJ0EVnRjV3MfqZu7RzUDqJvusuvH4-B7dzBzdDKvqZmjrZmjrZmjppg26aQvdDJVuxIsSdcgs6HKgn4r2GcuHWbdopnWL-AaQ0_wKDQV1QcoujxnejqKpF50C0rzEDWZnMLDT1PEG1PGGqGMH42emNhJXG2cwsDOVMukTm0p3bLB-mjNGxZbTNmuBnuBpKaK6AsqCpy6xHTyZAH8jeD5MJOkd9tQ94N4Utq1vjDhbLutcBYCZ7UUFL4p0AGsHZmO8bdd6b8zIUKKUycOVMilUyrXRW_6aDOBJbJqGom9fJGU9PtG8FltkD9PCbxtmOHByCVsHKVgblh-21_T7padhIVTiNhcMBRUWjfwH0J19z9J6BJqKZHXLRL-gmlVw-bM3I2_XqjgMS1ZufKqWxdxoORQ1NuYYPolbWmRexarG6dzNPPcrug79U4N8v-LdVUuBsFf5XMBYm-zY1mG1GZ4IjgimRVXgCMvtvuG2Lxy31fJe418kyFJbKk6OeUl-7ZZSkC2qwfRUJe2qIeGr-quvp-RWQ5trdixz6yZPBLXWLf_XDyl7TSJanHOqkBYaD474F1CnuL7N12HCprB_bkhjXAI82Qta9kqg7JXAZxEJlx4Sv3_jRLDOjnHwW26SjwrIO0B-ocgnivxk3-oect_qM6sqSn6nTIu4yfvBJ-orjdkxVh-Tse9Wp2C8Y-gEy14VFkV6wCJA09c4XORRJL6sA_Ofggfz4sEBmsWRrOPW1bcybICwajBYT5RrLW9fYSQ7MwxM3mswZvLuDOZRdcC9g7Jsqo-acV3arkatRx_cMA3unq_DRlvtOJStVrYL3mCni5izVK8CttNX_LQTAAbfK-uObHZzwk7vlGBVYAXNRWJqpqYGtMBIoSD_1y5yvYzJtV9H5kMzhcI9NC_gge6XPIxZ7xuGdmJoLhocvg-rCr-dgnUC6H7zAU2Peyj9H3FplJ7vnyhWtA0TASV3gqWlj2cr_BJWqCMYqRgvtAsjMrBDeM7YrZqjvuO_U4jb4WUuDSLs85j-loz9BT0t6rY=";
var MIDI_SONG_FRUKO_Y_SUS_TESOS = "eNrtXFtv00gU_i2j2E5b29Q8rCqxSC1iobBcVrRV2wTVWVtuAs0mqsgr-LfvXM7El4zH40tCKUdCOGo85_qd70xmxv7wx_fhn9-fWmE6-JIOj9PhMN3_ke5fpV6Yen5qfUrt83RwnB4ep9Ykffoj_StMv1-Q1B7_uxyepAckdPdOSepZ6T4Jj939JUl98sLdW3oT-mXkWvLL6MS1-ZevXEuMTFxHfpmcuEP-5RvXWR4Q-mWciY1PQOxrKXaajZwew8i3cuQsGzmTI9_JkfPMoPkxGPRRGjTLxM6kQe-k2LtM7J3084MUq3Xl8UfoI_3SJf-439KPq_KH5UoTPMJvIksKLZecVn2oDgSBm7RxZjedUa-YkXY6IO-TK5eCXUD-dPA1ddmQ9_-5gyUzOqIiV7m_0Rsq00T_5jpc5M3fLhVI_7EaOk5Pmf1cRFLjQ0GEMIuON7GM38Adur3MlAtlFeBgyvjwWyqKmdhVMw1lSXMF8phmm8fjBlS3TUUFetdxvP1clYrbjporSqMJCCoKaDsgqKi6HYBAg_V-QFBR6zsAATIBMgEywUNiAivHBHZzJjhgdozOr4ScIUPr-dXRuWsLG02soleb3PkuVT4kEb9Sa3x3HV8IErdy8dqANZhvNpmDyBhETqjIVRFINlnATQncFHG9a6-colct2YZ7qDKH1AKQe6IKzgqMvLiUoR-Q6cXlcxqJT-yHB_0pIv5XcZbwfe47YJEDFrGrR6nnwMw_agRPyvIlT0oDaNtkGRCufMqvlF4Dsg489SkL_MXl0UUn_qO6fNDlgy5-VZrLDRhfn4mSZwbMrs-Org34EfAU7Ak88SvFU7DJE82LlcOfDbt__dIVaZWZ1RGnNImASQRMIjzNK5HmYj3MIVQxhGrir9PCosLT4vCoPLtuwbus4MAaUBBV50LNx9RGcCgGhyY56CiYqBtf0-oLfFF9_EqrL_AlZy6eNQF-gS91zNKV2zmQHa7o7ELEY59rOrs4Oj9Dmkea3znNz3dA89-AWpZALdPt0fw90PwCaD75-TR_D5FeQKQTHc3LjjjPOmK_NH8PChagIGlO8zrobIHmF0Dzd0DzEdI80jzSPM7mcTaPs3mkeaR5pHmczeNsHmfzj4PmRRyvXmQWMhEmuwY2WQEc7rKuvw5uieqHkK4XBVPpB4GKbyVJArkQy7cS3_eluxKfmPJ9pj-PF4Wrm7bo5jIiAZc5r9YuyTnXl4y38hxpzvs8CLdvRBDWBG_mkBHJryFQ70TsGxO9I-rgeRU5iXi0xJ8x2w-hQmpwVzKqEHIl7XUzXd8OamqlbI3A57ollGqmHHbzqb9xyTQuDY1NdT2glJmFfwi1egiTq8PmxaFtBMriMG4GWRHkmlYrsNd3BEuLd-hGED1sC9gWsC1gW_iV2sKTYh0_gbbwRNkWHKhVB9qCk5dEipIOQJKzi9YhARbA2mUAAAvMVy5211L2-mwpFpUT8V9U1EjWKVzytbDMQkjosjWSAVwtuPL7KheRWM1E4rdztoBEyARETUAUu0pV1FLCP7AbxNXiESKmP_HyKkveEJK4FpcsrhZcpZdrb3hA4ks3-3VMSAxDYxgacx8bdgeuLC41hhqbI1AcgeLcAc18k9iwXyTU1H5dY-BnQeXP5kqssMQ6kFgHEuuorDNqAywo8ec8dviJ-bjOioI2iTcCZhEwi7OMltE3ocuDqBAlmXztKb_xBm68gRtvXFMSr0HDGNI4hjSOzRGsGGoyt5eYXS-aaKwbAQJGgIBRdjoyz8fVWDWevpthchN7hsyqhx-SKZLpb0qmCcApATgl7ck0BlExiIqryFQD4W5kOoE0TiCNE3MEK4b2TaYhICAEBIRIpkimSKZIpkimSKZIpkimajJ1wH4H7Hf6JdPdkqYSJeVYIJkimfZNpiKWiXsImDrUxbDj3kKj7bdsaZdtGRgHsv3egKiuHNKz4y2XVXuv7bfLWPHtQfHt5Y_NbXv7rGC82TZZ11X-Ttthm0v8ZqYwgvCAIDxViCSbeoB8r5ZFtdtfLKEeJNSr3PZiAPMAYF7f213UZX8gXObXhttfBUptfBqCZ6aBqTluNToO9-ucgmiCZ6TfYjnOgH5nW6ffnKbm9MsRPAUE596PgXSMdFygY9hGa3NQB-kY6RhnwzgbRvrF2TDSL86GcTb8mOg4R3w7oeOcKA0dFxX2TMcRzIajdrPhGQBs5jrbpOO6c7XVlak6Z8vqwoe68Hd6vlY8CPE1OIS3IYinU24CzqkP7dxt0403vnodybPWMzhrPYOz1uPiWevWG2wG2xBMuQfKPVDu7WIjzSZT34cD3OK50pHvN9tIMybbh7hhxgJffOHD2Ccqn1tsjG1sgGXPus-yZ9372AAzQti8hLBJDmG9bHSxNwQUsRT6Pp4ayEEtcOBNJ0AwgfJYTSvymgYWvHTEEmUcWP2Tl2gGCaiKQNUVV1WEXIvpZJ68bFjrGsJ1H66mpBbB6GjzwT0VqQm_4pJKeEZv49SADVyRiU_MnxqTwIWslV5nMy2rrM-GdDUsuNqeNJVxKOZG7b4O-Qo_1Tkos_HMb3kqQUG-atmdybeBd5rAlchajUVjshZC1NCo80Zt5AMh8SJKwmImu5B7lsWwlMWupL9pqxocCv1VDxvXz2SV8encDKqDpJ1_YDPAZoDN4Kc3AwugYQE0LL03qhUM_XHKzKew-QsMzJpBlrhJNZ92numzLDrgiANZdLo3gw4zfT3zdo294Ywg3HxZVt2PzhjiOIE4xr6z9WUN1TZeHXB1JdaIxCvmXBpAK0b0-7CFDdEfshWt3Cv2mj6E0XIZJGvf41L73iDlsBSKsC9SVkwBTBE8Lhk_bka-JssmI0jPCNIz8n-_hy0e7RZc9X5EH1tueMKh5y21vl9ns7lFto7kT3g9jbYMt73l9YhPHCC9Ib0hvSG9Ib0hvSG9Ib39vvSmfLfhG_Fuwwxcr-iQ_wHOHla9";
var MIDI_SONG_LOBA = "eNrtXI1P20gW_1ssfySxPeMc4jjEVYhlKXRp1tcGhBDVNosQhYbGEUtZFlHN337vY8Z2EjuxE-jt7Vqq1MFxZt68-b3fe2_mTX7-57fWv7_9Y6we1JWyN9VA2aGyX6kbdaHsdWV31Z2yd5S9pxxffTu2VOurF_8LHlivA_eNShz4gvU-7CaWCqw7acf0YEe6p4qbPeHsK_40sPjRD767o7_5cxjxZ74dt3bogX1vXu_w628Cb0t3dhw6G-ZTPdSPobetP_2PcHZVrD919MPXoRvq5nth_5J-3lY84GthP-ouQ4FCWdZj24G3zAzxo33ZgieiZM4JfgR_x6Ao-LZ3orCltXAAL7nw-A9l3fe63Qg0iv82FXVYqij8kJ-wSL5HIrHqSKQooJdSZcJLHT-xJpVKosHfB_ACifGTsn9X1m_dKMJ13sS1NSOI2JpZAP46PtEjWPQSLYkWw6WXShcJP6QnWjvtJ60dWjijHS1W1CWx1hGB9M10deGbLVrc2WXG9-hZwiP4Dg9AK6-FbPPy0RM9E17jaUzQUuIzrTHb-qmn7McIBMJOL83X2z5DJI8eHoOe6DG8pXA0NY86MELJYlZTCZ70MnQMSOcjyvdWQZT_sojSeuo4SwLKaGoRoGAZKwDKt5YDFEgcOtDBxx-7EhiptWc6DLwKEMtTFfTkYU-3b4MQ5gHdw5MWPjnvSXEDTL4UmXG3NnZ7p56m-hwvz3Vpv33_QjlXuuOOdXEoZAEPwjCedRu4xjrqESIP5lijIz8wc7BhDuICXN2KbJnTe2cMWjYa-tgPRAx-tBL2jTbGhz7ABsbK9CzCM9PLMnRrxBse-whvWJF81zfg-Z-DkDMlhLCc45wSQvGk2KzKGTv_7bFCu6lJ4fASoEN2DIg-9oW_Iq3ncH81NaEziJMqsb6ZF8AuvAKkZZ0IOYCIaxmvUAblcKye1OouI12KfgALeZWJfCwkWKkznutUsm-HIBxgp56XyZmS_4ComVTYcqbqz5oq6u4mt6hsZFd1TJXAGtzk7B0ZcYxCL-vHcoi7Qd3lOg7Gy9vptJ8DQ3FPss4PpbDfKHs03wXmkXyRylLdJWZzC-_yC4tKe0Dg1jfWvIPMdZ_ZGVoFoGZcYKs6OdA22naUa12-lXZRnBavwYe3ESgoceISZ5llPdwbzOtIRPaxss8r2aFHQzh9kOsQmmPhnOC4mUlSn7_2RYhK6BWZYC61mrGzGLqDXiP0o35qaW3ytj3p1jEqLWAE_8UbObPSAkYS57ZeYEi5ZK7IPvaxV-kC9raMpXCvNvQqcdbHRV4uywErWsQujDNCIou3c66rrcHC2i0yhFw2OYv34vxyIY51n8UB3gxCQcAjCdIZRUyC1GcExQDSk8ogBcijfPZtJZDqIfYJTjPQlCGyyLsiaHq0tqTEswogPZsCKSNgHaWph9Q-jwvwktNIvegJyfsaS2cmu9z7BSMph1jShsit1HNlLWgjt123jTYyzesp7_SYznv_u4xmhfxFU6eM7FOkzgKcb5AOALEJMNDCbZhNYxXQQ9s6lzgTD1qXEbfqhEqHvN4e815Zeo29Xwg0bh9av0rEAABxYcYSg5AarQdejk33iO7l8ts7ByBVakQADIiVt6YzGGiR5W0sbw1aO33WAMz7ndaFhHUk-3uBfSEi8wgEPNjiOX6EOZ4qXtv_ry0jZitmcFmQRkykDYRmwPDnIgvxGOmIu7PFqcRk8tBNKZ7sRdinqb3c8ypWt5eYMUWBTEGSsTipkGxKj9z6VaAIoPAKu1cHMHhG8xSQkPcao_8E57JqzrFhDDQQmKyDsbMzwO0cf45D2scZBc42S_OVXB3O7Vp2E-_Pk6vsk3CIXIssuJ34JKSkkHTlLOYOOxMAXgoMvkqEiKbNY9RkPQ7Yhj5-lw7E_HpVLo8jNG1G0EulP4m0pt0XkSjkCU6RUcJKo996UolX4_CAugSYXKx8jKCDN2-f4sMK-2eHFCfLZGO-5-GgbYR0Pxf5Zzy8rzTOVz9sSAimI9nOEoZ5ziUBYfD1iLx3HYAdsugS_f5z-pQtcl5Rsl_Ft7B7GHUxn5TPfTCB87OKtqLQtm5lmOwuPKhoM2WccvpWz0mAcq0iJ7H04QWv2QjtmvFbfoyh9SqdNa3XVQ40dkldQbJdNWACtrjlcHLxEQeGsr9RgOW_yGEH70FIbw0GfVUhSeC1G9GeyVqVdIFJYISRBES4z5k4GOZ9ww7rPPRqHXS8wugieNIxIzKwpNAFEy3U5vMc5JKL-xiY7keRN6ANpQqZAVLsMATj4tClnI1hIWCMUGD8s9pxLynlQ6eToN8YBiKBL2PXAfP3FLgRB93aBxSbHL1vIaJ1BuCTjmj_f_NFzog5lAyyRfYgvuOgcgFho8WakFiSqYDkekG-81myxru7V-_8IKQYNdKU-DKnyz5hwdunBaxE1UiaQ9Qq0-ZLnjhTenPtOwlk1Qi9ts60VilqWE9JUC67rUO0KFvrmoC-77F0grQ_jIIDEKPweNpXHZzD8MOHSMoHEp8Olv3Zp7D6HdsRErv3qaEJbgGjExMMpYUTQ5sM2KyKz7Ylnb6Z8P2yHwaH6qww5ObtP5htIsupn1avnXF_NhAfu2YDBWEfksF6VpMQychWove3fcqh2VQwExl24vxUYGpFmbDWizndxFcFJOy4Hzp7GM4TaFvjXiicgsh-zUi0ywcN03tL6RiQMV6ZmoG8j9HCCKOpL6AZTJMP4AP9TRkOOGEtTQjW0rVx1rQc21Xc0jp9D5DSK8t0v4BuBrl0GXV1aLL4yQxigzoL9eIImzYE57srwoo_cbJu45B93JWpafkJ74u7CW-VCJfz1eljddqhAXAgNorpgHc5pd7YcAysOa_WBJGpR4oT5VgqYwpcOJrH6CiMEYCk5aEIU0rLn-KlSh0AOAq9HXeHJhTJE7TVDBjCnM4FOB5qh5jmMnvnuicFvqORvWDT7ImIA1NuAATjeqPsDP72bSgziyaVDrDUoMiHrmmYxfN9qTC-lMfoUP1C1r_spwelzAYWy1iFODQmnDmbZ9e9AJDdX3Qer4XB7Z5XmpCgWwpsc4SByMjxzyRnbJHcbU4IcdqzW2gt5Jzzo0DYs4TBPtKFBMuYCxUW5PhC6L2pUv_uGVM1rLVVxd9v0ssQvL4pZosOsKTIsSry1kMRUzCNB7EGBtrf7jyu6HKm4-jUKNsUg_EGk15FXEye7GuQhNUoRPuVoOBECFot6zLol5BGm2NIViRtcBmgXKFAN5RBO2Di_UkKwfWTYywHno05cqbfCWLylq84vHtnNn6sAjIBf8FFP_PYZHQkownYINi0PRcGLnl3NMaNSE0p84ORmGJDlpjz4JlMk3aRm4CkCUiagOQ5A5JSOvm-gck8KmmCkyY4aYKTP19w0h6YdAZbtKEyEXMcOFfPsotRXLTi8Kljyw1P1MYZxwiPEreOcDd6JNNtpbwZw_ckhTU9EXi7yqPdtK51DhgBGbqgmyeiGTJxo-6797sSyyUBPxx_cdSAXxwKzOmmSl_-iLxdluILtfwakQILCNzbC0A473CqdN_IE0QQDOIB6rHKxQckUSALLi9By7E--eFW0bG91smnoyDEMS8UTe1TgCst6ZzX83g-Q2zpwpqJUMHI5dOCniumZj7rIcUO8W4EmndpwUwqhR_AIN4ZBwdfpXvPY19jy2zdT94DSLWCpIEVYPcqZ_KkFT8sPqZ3XGLNtx3P8w_VD6D69ztmp9eLTckHtGYZwCzV9bEAs5Meq-0cjzSyzctUur1fAtLNHi5b4VEpfvtaWowhIJTPPPoFtWqePoFouOW6VbZD70DIubcxqTukMFTeu_zGPXY0FF5fiwfBkWTd9FPd9ClCqLKVH3PhwZ1ZUGgZMpyIKXLriYUeAKfP-YBCI2UIzgnm2rqlnX4imtu3vSiS7ki5t8q9T5lm9nHZlaCCt5kgRCdhggjtgjAkt8qhlHcE6T2VC0pIjR1nW2nWcNd1YgKMFaeMVVSEVM5hNH_gsDg7fZjPWOnBMZuECHgf_Y90Mb9QS9amK-TT0Pc2lDcou9xQibhyB83MV2LBTQZjgkBdsF5en09CgK8GKV8NstKLanxFwnwS7tzqvowyOx648TuukPwqPWmwDS0MCZH5AqN4vwZrFbMVx3h20NlRP5zO5aQQSfSG8XYdogtIT5rZcKlFtWqViCo9E2ciCAOOaMbSlK1dUGutFk8ZPV4f-wHEUbq0vCBqAb5qJ5uGmNu-IR9oLeSw3CBIZMHj8kc50FWHIqJj0TpVLXrgTz8oYi--bph7L3dAT9wQtrrlB5bMQJZmIG7M3sRYxEAARaz6q3TbejZOIm_8KN3Phq2wBRBAw9XwqBI0paES2zzC6BVxkPtoOAhb3vcMmT6FIUevv0dpoIMtHcfOhFFB8FgpjCq6DrmIeCDN5soD4BI_5RJ_XplXQeTEIRfCz1CPWIl6aN6X7e1B5TDoWrib5sSeAxKinG2KFRzr2thezSBJ9_2kj4C_Cqzksbiy8ZZd13NFSfVjI8FXLoQ31oyILb2duagujUycYwsMMvxYF87hhR8uooeW3shYLVhimElXB03ArP0jGUW8kv70g_JAKfeelt4QVNB5hhAJK8orXeifDYdMZjbG4gZ0UV1dUdvFvYL6gZJ0maTA18Wpr4uXIalFgRLzS0fuLiQunaJhyJOrzttMK6hISmr5NcKnopuhixlL1gyVPJZyPZVynYrm60ZIZnAYRMdFrY6PKFKx3otr7Znlwvv9G4urTkrCJ-HUyummQiWIsx-4wH9gwhZs7a8cKR3ShourJ_mRWhtFV5Tm85hOPN00Kko8S2_g0ImxZd3vArcQsSQtHXmYw-TrXyRbcvPLCM0vIzS_jND8MkLzywjNLyP83X4Z4dmrNev-rsKc6vzmXlRzL6q5F9Xci2ruRb3MvSgqMhlGLX0G1lyQai5I_T0uSD0Q7sMEvtBclGouSv2FL0rN29mqWobMRaaR4EALixLXyuyAC8XaHILUK0XmQrEorF5NCGBfW6oUmYEVQJiyciky_0ZIoAvXgFLW6pYiZ8JMlCLraj_pAkqqliRrvUgtxSJ_1NWJCWQcqxci--zfjQhtiq1KYzE9tA5VVy5D1r8XhlRBnv02Cgt-zqdSIfJsxkEuYYQ_s1P_RhTYRHMjqik6XrnoOHWGn1VTdtzciWruRDV3opo7Uc9zJ2qnuQnV3IT66wQlr2Gd_wtc4B68";
var MIDI_SONG_NUESTRA_CANCION = "eNq1W21zG7cR_i03J9G8wwKMZ9KxbCcNm8aieDxR5JGSVc84bCXTVBWaqkapp53J3G8v3naxwJFOmmk_JeIBi91nF_uG9fkffsm_--X5sF21z9s8a59l7UV7nLVHWZsP23zVPhu2su2v2qNVezxsf1lmbf_haKR_FUdtP5tUILOpXptVEobtbtWKrFbZyH4ustOlzEar8P-7Yfx9Uslords_yHY5LlylH3Fz3_wGtMBQSqnb0-kkIAIJ9SBFP6vEXin03qztZZ-EOaOXPYijiAn78cF_NIuymFNLP1r0D5GNslS0ZM2ncrDLsz2cpkC4H-0WeBYz5gVFuunHiJEA0YA2TJ1E-YUDRa9AEtUcLFuF-eNRa_9oZwCshflvntVwZOgeG_ZuXwhpNVGYY7ZLiUsztgQcjman4aLvKfAtEdXVN5UUgqhqDuIDi0AND1ulDECX6oulAthL1R4YqDFec86r2YLUD1A1DBCv1Z0QskOV88oYUM6OmFhhaYRAdQdS0hK3RTpcz0TgdeJxPXO89vTnxUjrApi-zCL8ePr-3TcCENszz8RZwJZTdN8Y5e-Xt0KCIsqfFrQ4w0WrH75fggDRocwWdyivXrwfSb1rP893P4wAoN_h2WruDFI0YsqaHa31_ZS1nb0vySbOBJ3AeZ663_7Y8l0aBtwFEXYRVoDaPpOdxZ9rD0fl4ahEYPqbt9_ruxGYNos5VhqqMvO7Mk-FKD81HoYK6ATi_e272Dg8G5ZQhBlAoGyBrgLQYRNX4fKt3rSf59Pl23dQItCHeTZRqEN58e6bCvj1C4uD2U2q9-9Kj7cTZtVlw2gOSHMVdNiIeb79AcipVWGTceUOy-_vJEiVISyar9yH0l3rVx_vjnXcze5tSDjOttZqj22IsKBKF2tOLXmzrk9BLvPfzd-nEtnI6fuQ70_XSfLz9ViBO_xeBKLITMY2vVHHNt5M_feHwn2fQYe4ZfZB5N4yKGA6ukVp6exnmv_uzym7wvjfXWjTyriUKLEPiqfKMfGombDMS8-8_z5jQoT1uQ_SRvjce35ifmqZL490AhHv2M8-xQ5kW4VwPeS_44lFvH-kjeM7z3FuT044FwnnisOO6YbjA9WZ8s1_r2WXr9x__47Oi78P6ZygpvQ7yvdYOk2MUBMej5ngag7yXySauEBNkHkW8frE9nG9s339t4jN5ymix-n4v_2de_IWVB2woCeI98883o-WP_c3mv-K4T-DoKdov8fjSez7XZCenwon50wkeAueQhjcu3jzc3Yit3TmEOPzqH2N_V0k_Ht-5geu7dzb_TzwxXxN6ZjaeebnEBvJzoNd7wHbGVmeMGHyeivkqrUJ771PlbcyqDfz7LgUWuw3m0QNU59Ab8FxOvXZ-yfYIxbWCFt0pWUgYn6_Tw5F3WzLnIkZvM3Mf38och1OjkzKt5lc-eyw62nvi69cQl_20ONqz2i33Z8tdBAiR7n6dhBCAa65va50JMvRGWMtotcqfhUiupvmTCkPHf883L83QEIOugzXO3HQSGQ2hkHwLT4exgwE1xqsA5fZoqe-UWGLh9BpKEdvGD5fK4LBO0cdHkjLN3IQPG8WByqCu55YWCKHpuK4-hDqotWLywGwWD20QMRx4VF4Gyk5MClN-9GysL6aSBVFswDQFsietpNaSYhwoi2Rex2QcHeXpxIB0tED7UQD0w19uEcfIyXkeyKh9XAIRD2-U0KGSzC0gcI7ujJ2cFPmIG1AKci8rcWghOtm4YFgnEly6gwIKUMNxW6KQkeYpaayG9dgpOJx9FFQQ8GCye_zKR3rSWTZXa2NUa3aVfvX1olTdkEcOnRO774VShEJhlIg_RmS8MpK-UvlIftZkJncLU4VAA-16BN6RoSfK9HzKOe4ZWsaEUBREpFy-k99yruxriNycrEuYgls56y-7UZpQqa6VlLetB_bTRs5-wvuX5SM8SBCkX_B7NPAm0fW81h2BNE4JXnyLAi0tTebaCFO_5yIHhncorG1U8Zk5JH2EX0ORfQcqa-vam2rOcLjbyMmF1GQR5g0Q9puf9QG9AENKI8SDh6hrIoyL3bEQ5lkDeh1ijgyzQS7ZMIT25UU6ulmnC5LUIkHK79ycOnPTdkDwut6IoTq4jUvk0yD4bRcwADyjhnNywQffdSkElIcJ5Qw50mslyc6p0nk2pU8kbYWFG4WeQ7Bs9V-Ng9u817bMwhfBuo_Fz4ee7_XlxKThDinuS97wxY7cLTLiD37UabUYwq-vTK3zhAjjVSCatEHbEZuVch6zZbFV1yVAoJNrv4UbdFLB0Ru20RXlBhDdKasHXrnE7SdJEgea4XZmuf8ckB0tB5h4Cv6Lh231NPZNXtBKozZeOZ32CfoZ08TEeUPljx1aA0XV4ELY3hK8PCGnllKwUhC2OpI4XlZ9rO-4t-1wxaDGtKY_fjauw2yW-XzxsfQCrHt6-vBaUst80uP-Z-hE9NuNbcydD_-9rqe6WDj-8S3bJ8tKLBQsAl_L9tISSDjGSOvtI2zfUP05tX51BIll28gYuvtWcFl37xSQDV6KNyVX7mRWYjIlVSB-2q6eS3VwOvmVvA80pTJLI-dAKbItUdwLRVF5bFMEosgzHi2eaXkACJhZFiP_DohLFoQ3g8uWSzyyJImiCf3M8o0_3AiQVGTIi7B2YGus4HcIkCnSwC2Nwt7rDDN-UZH0AGHPsQCpMhCY6CsxZYyYVMO_FGfS57nIycS3X1NjQufbBQhuxyrIJmHvD6f3knJ7CfQYkjKfUIww6xCloyNt-rjSaN5lnHer-LyA_3fbYFdEzJ-rNwoQoxdhNAfi5T7QcZWYwUg8frehkhRr6VKudcEVaiZuQHMyXqZUj-81BbKMiydbQwUaeL2qgYV-bEg5AehmPYh7iOgAfmE0SK4eVXroxQ_yySgkTCswA3NoQkLrGMlwwkratg5lSxHSgbh6g8vp_ZAS3QieKfMZdapQ5oydzFqJKp3GmjenEwb5TN7LJC8ITFVWKeQEeTuMG9IfzuZzZVirnlb1V63Yf1DSKk_NEuBKfU0dJc6buLRJ2pTSVsNHsB4f6UdtkBnOsHmR0G0tAxdEWqS1aenma6BiuPev9tnRy0KVX84mcEASdchc7tbnEkJcU9vK_qdG3cRWtw3L5pzJUHyTJpqKsWvLnjDXkCsSpM9LpgdnE83EPmEs0ZidVlHDbq0_-vDwYVgVvyikZSzM-PTRBXaWh18ma3IWOdgDV1384b6UMeY0t5X_ZJKAJ0zKXdvAthKss0c3Z23g7Fkl0bIAK-JsJLZ372u2WSSlY5Zlr-GUOYm1qE39Kk_y1IrNYi9vZIYlHZ9OgC5Zk5EhHtvFym6jjsTvSWL3s1ap0gK3xDoCvD8TgoWYcEe5LBdytI9-FzhY5VKfYG5Fz23IdMbQDx3OZbZQ7ZgrzKV-ZWKGjYDPFDnxfjc5s5Dqf039wTn9ATBEbkN_vn1yj4RIffh0e7mZF4r34pLGljoe-2mh6r0T-xzn5JfsVC0hjI2ymF6JPhU2ZU6tNuC8HLaDKSSsVvHmt9sFjK-aq76s8JFFsqCHu7EZ0ARQwuxTwMIx2msMVm2Yw3EkpSHrAHkEeb6TxPl3wKd-FEnVvNR0nvgw4LjI4CfKZ45E_14ro0DnFn0bMrwl1qXVZhkCMaDkPTQqXkgFpi1-FPhKLgnr3dH-qop-0Wf41AmtqR583WfZl5xMQm5I-YzdSYiA-8awgaA0cTLYQ563n7dMgiBZ8uhcLwKcyYWUuK9ad5IKXgNFWvBsyfFUdx8hyzc0FJ81T5nTLhLwulHAeHvIKVK2DJuTRBXn-p6IkJg9qnIEkJ92UiVpcrQ3OSmYhy3F85dXCtrhZbiG51N-TiEVl9ysg7ov9S1ZlYliTfr1BEiuph4htx81rHxmS3n3qn3bfCpwoewN0WnPMLijvJbpfg1vp74BIgVdyKONY9lUtxxH8aqO15_YBYV-YzQBIyqu3qN7dtKJplzqO6cSuvZR0mFIuudm74fzlHdCl6bao5UUs4h-1EjOHTQyX7WJ1OIUjhdZEjMK4HXdTItRDoRNC7vnMY3L-eS2hx_Bk5DybS8g4RfiBMYItqsqepCZZCiWc0Yx_0hed-kKC0Y9JuXAGhSn8tOteudXRQDRjIp5wL0odZ7EpEaWWo_ns210mBAKRClW9W1dB5XmBZNfb75Ynl3TOjMPr6Wvj_wX5R3g9T89d2C-KnPlXdEM73YAo0ZWxBT2VFBVNJxVdAzno76vMDGWpW5X1v2uQLhi3Wc4O_uoaHN6jiLvWR1nD8dq4k0AzYlpQoJlg6-1AyO60dblWAa7j6iaqIuiq6I6KZPkhp3Su_T_Bb4wZdpVHQB6waZcAd0C1hZFzxQBD0kNWjB1RNqL66S19pBi4jLMHXwJDq3gKVLobth7zCoRIy0oBO8ALRxFfvC6xPbwBumrroWvMYrTAxbNyIu8VzDTHUf43SFY8ebeNdvWxbdUy7K4DMM3kqpTo3n60VW44lOgWCLO1fkxRtBcAfxAULjx9dEOK1Ri84zu3Fpx25RGYq9eU3TVrwE5U9pdFHpNaFZkDd82GfjF0At7rsK3IPYtuyj0n4aLXnV7nGHeI6EH07paRO8veEcOOc_1RWVjA3nXAKLSZ7QFWs1Lil1DiUPlGFaxK5PAmsjmNNN4G2AntaiKgZE6KxrCIJLv31bA0veNdbCj2cUoxbfWFhKhZMyZS-02aO-kKlIgV6z5yJBlHjG6dfI2u9Tx7F5YYNf6KEAM1icZxwHQDUBwXy1LeaphhyjekXHxhyxUGtTCJEFNz5z4_FQlCyE5Ju3VVk45TyzWH69mJkBSveGY1Y8jBqy8EryWjFpCGrjhmNqXE6nk6J0rsaS2eiDSpFkY4Wp3oAqW2OrhovTn15NTT4lokEQ3zF21JqlTIcirySvIjG--loYd3nJnLDj5XQDOCaMI5jdjaYm948x0TbZOR9hPF3Ozjd6BUDUR5URKzSefCUPnd-h71moJpfrl-Y2Qywb6_Q1Z8Do08b5ePnRqDfIphUTjaDadTcns9nY9BGidbKrvrOF5OpzaI2aaCVCsj4RQirRNSEPzYrADgxPpptXY7Duji33BmlOxXmiL4642lfWbnbCRptEvwv93gHYA9NMh-Zh2YCUzh7zeNyWt7og2hsL8hvHY8lDu_xq7wwXjW2qeHZLxcOwbHg25C-mK3hAYOgI7PxC_ltHa10b_3eO1oZhkzOlZPzYyiZtk5mkSMP6fh8evA1P1Y2dNuGi113RwzBSzMb_fiw353o0jWWpklG1IDU23rMvD-1S3LgeA5vC-rUZXhwXsbkOzht153rjEanuXG_3-38312uHjKKX4mQ0amuHPHoOkKbs93s49csKSz-cv3cIOMxmVRKvw8WBGVWi-qVpo6SD8gTdueLfOSccHiIWVLnOXDfVBva67veLHk4RU27kvDENGSdDxWQfxgur_NdmjA-PEYl9c8WYQXaxxLnkL88dB3ps7jgarihjvzgP3eXdpCwgnUnmUypCHRxRTgaHIg8x73qIe21jwg4N_f8GmPHef6orqggZK915ZpqoaUYKh4V-w3gzyvTwZqnjdP5r0864_NPIdL9KNvyMy3D4Ofcxzn6P2qpRYe8mfnH4uTsMGQ8_49Aze8YsulE5S4ehzdDzAIeg2eSyTCeg2T9Wiv7pSUhelmakMwy1qkE2NYnOXOb_anevD4xB297Tr45Bs0DMwPmNY9DV5YC9YXZSCQaQ4jYWj_VWcQKALdB9Y9A8nTg8Bh3_O52M5poPjEFHXOJca33zQg2SCYIqscw3v3MM-ospB-xJOdj0L03w7h2D1gH44Bj0VJnBOJX_3O6-3j8Qvb6a-FQlGoimUd_LG5GOtlLfOHGRo2ggujsIjUTerNr_AE-LlAk=";
var MIDI_SONG = MIDI_SONG_FRUKO_Y_SUS_TESOS;
/* === /MIDI SONGS === */

const SONGS = [
  { name: 'LOBA (SHAKIRA)', data: MIDI_SONG_LOBA, genre: 'POP LATINO', bpm: '128 BPM' },
  { name: 'EN BARRANQUILLA ME QUEDO', data: MIDI_SONG_BARRANQUILLA, genre: 'SALSA', bpm: '120 BPM' },
  { name: 'EL PRESO (FRUKO)', data: MIDI_SONG_FRUKO_Y_SUS_TESOS, genre: 'SALSA BRAVA', bpm: '105 BPM' },
  { name: 'NUESTRA CANCION', data: MIDI_SONG_NUESTRA_CANCION, genre: 'CUMBIA', bpm: '115 BPM' },
]

// Base91 decoding table & constants for compact lossless MIDI storage
const A = "!#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[]^_`abcdefghijklmnopqrstuvwxyz{}~";
const B = A.length; // Radix size (91)
const Z = B - 1; // End-of-varint marker index (90)
const PROGRAM = [65, 59, 33, 0, 56, 56, 115, 12, 36, 0, 37]; // General MIDI program patch presets per channel

// === CABINET_KEYS (DO NOT modify - matches physical cabinet) ===
const CABINET_KEYS = {
  P1_U: ['w'], P1_D: ['s'], P1_L: ['a'], P1_R: ['d'],
  P1_1: ['u'], P1_2: ['i'], P1_3: ['o'],
  P1_4: ['j'], P1_5: ['k'], P1_6: ['l'],
  P2_U: ['ArrowUp'], P2_D: ['ArrowDown'], P2_L: ['ArrowLeft'], P2_R: ['ArrowRight'],
  P2_1: ['r'], P2_2: ['t'], P2_3: ['y'],
  P2_4: ['f'], P2_5: ['g'], P2_6: ['h'],
  START1: ['Enter'], START2: ['2'],
};

const KEY_TO_ARCADE = {};
for (const k in CABINET_KEYS) for (const kk of CABINET_KEYS[k]) KEY_TO_ARCADE[kk.length === 1 ? kk.toLowerCase() : kk] = k;

function getArcadeCode(e) {
  if (!e) return null;
  const k = e.key ? (e.key.length === 1 ? e.key.toLowerCase() : e.key) : '';
  if (KEY_TO_ARCADE[k]) return KEY_TO_ARCADE[k];
  if (e.code) {
    if (KEY_TO_ARCADE[e.code]) return KEY_TO_ARCADE[e.code];
    if (e.code.startsWith('Key')) {
      const ch = e.code.slice(3).toLowerCase();
      if (KEY_TO_ARCADE[ch]) return KEY_TO_ARCADE[ch];
    }
    if (e.code.startsWith('Digit')) {
      const ch = e.code.slice(5);
      if (KEY_TO_ARCADE[ch]) return KEY_TO_ARCADE[ch];
    }
    if (e.code.startsWith('Numpad')) {
      const ch = e.code.slice(6);
      if (KEY_TO_ARCADE[ch]) return KEY_TO_ARCADE[ch];
      if (ch === 'Enter' && KEY_TO_ARCADE['Enter']) return KEY_TO_ARCADE['Enter'];
    }
  }
  return null;
}

const held = Object.create(null);
const justPressed = Object.create(null);
const justReleased = Object.create(null);

function clearInputs() {
  for (const k in held) held[k] = false;
  for (const k in justPressed) justPressed[k] = false;
  for (const k in justReleased) justReleased[k] = false;
}

window.addEventListener('keydown', e => {
  const c = getArcadeCode(e);
  if (c) { if (!held[c]) justPressed[c] = true; held[c] = true; e.preventDefault(); }
});
window.addEventListener('keyup', e => {
  const c = getArcadeCode(e);
  if (c) { held[c] = false; justReleased[c] = true; }
});

const rand = () => Math.random();
const t = (s, c, b) => ({ fontFamily: 'monospace', fontSize: s + 'px', color: c, fontStyle: b ? 'bold' : 'normal' });
const cTxt = (s, x, y, str, sz, c, b) => s.add.text(x, y, str, t(sz, c, b)).setOrigin(.5);
const cRct = (s, x, y, w, h, color, alpha) => s.add.rectangle(x, y, w, h, color, alpha);

/* === COLORS === */
// Color palette constants for background, stage, HUD, receptors, and feedback effects
const COL = {
  hudBg: 0x110008, hudBd: 0xffd166, // HUD panel background and border colors
  sel: 0xfff200, selDim: 0xa89000, // Selection menu active & dim highlight colors
  arrowL: 0xd3cde7, arrowD: 0x6a6486, // Default resting arrow colors (light fill / dark border)
  arrowA: 0xffffff, // Active arrow highlight color
  // Per-direction pastels (light fill) + darker borders. Pink/blue/green/orange.
  pL: 0x872549, pLD: 0xfc76a7, // L (Left): pastel pink fill & outline
  pD: 0x15284c, pDD: 0x29aefd, // D (Down): pastel blue fill & outline
  pU: 0x00894a, pUD: 0x00dc36, // U (Up): pastel green fill & outline
  pR: 0xb4542e, pRD: 0xfca300, // R (Right): pastel orange fill & outline
  p1H: 0xff5577, p1B: 0x6a0a1a, // Player 1 tug bar head and body colors
  p2H: 0x77dd55, p2B: 0x0a3a0a, // Player 2 tug bar head and body colors
  pan: 0x0a0810, panBd: 0xfff200, // Panel overlay background and border colors
  note: 0xffffff, hit: 0xfff200, miss: 0xff3333, // Note / hit / miss judgment feedback colors
  center: 0xffd166, // Tug-of-war center divider color
};


/* === SPRITE ENGINE (CSEF) === */
const P_PAL = [
  0x000000, 0x24222a, 0x4e4b5b, 0, 0xaba4c1, 0xd3cde7, 0xfefdfe, 0,
  0xf7bb1b, 0x9f5611, 0, 0, 0x5e2e00, 0x915f01, 0, 0,
  0, 0, 0, 0, 0x362400, 0, 0, 0x206100,
  0x7ec43f, 0, 0, 0, 0xff6600, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0x333d8d, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0xd11717, 0xa41c1c, 0xab8169, 0, 0, 0, 0xdeac92,
  0, 0xf7bb1b, 0xBF921F
];

const CHARS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!@#$%&*()_+-=[]{};:,/<?`"';
const CLR = {};
for (let i = 0; i < CHARS.length; i++) if (i < P_PAL.length) CLR[CHARS[i]] = P_PAL[i];
CLR['.'] = null; CLR[' '] = null;

function parseCSEF(s, w) {
  const r = [], p = [];
  for (let i = 0; i < s.length;) {
    if (!p.length) {
      if (s[i] == '~') { r.push(Array(w).fill('.')); i++; continue; }
      if (s[i] == '^') { if (r.length) r.push([...r.at(-1)]); i++; continue; }
    }
    if (s[i] == '>' && p.length >= w / 2 && w % 2 == 0) {
      const h = p.slice(0, w / 2);
      r.push([...h, ...h.toReversed()]);
      p.length = 0; i++; continue;
    }
    const n = +s[i], c = s[i + 1];
    if (!n || n > 9) { i++; continue; }
    p.push(...Array(n).fill(c));
    while (p.length >= w) r.push(p.splice(0, w));
    i += 2;
  }
  if (p.length) r.push(p);
  return r;
}

function sp(sData, w = 24) { return sData ? (Array.isArray(sData) ? sData : parseCSEF(sData, w)) : []; }

function dsp(gfx, sData, x, y, opt = {}) {
  if (!sData || !sData.length) return;
  const h = sData.length, w = sData[0]?.length || 0;
  if (!w) return;
  const cx = w >> 1, cy = h >> 1;
  if (opt.shadow) {
    for (let r = 0; r < h; r++) for (let c = 0; c < sData[r].length; c++) {
      if (CLR[sData[r][c]] != null) {
        gfx.fillStyle(0x000000, .35);
        gfx.fillRect(x - cx + c + 0.3, y - cy + r + 0.3, 1, 1);
      }
    }
  }
  for (let r = 0; r < h; r++) for (let c = 0; c < sData[r].length; c++) {
    const col = CLR[sData[r][c]];
    if (col != null) {
      gfx.fillStyle(opt.white ? 0xBDBDBD : col, 1);
      gfx.fillRect(x - cx + c, y - cy + r, 1, 1);
    }
  }
}

/* === ARROW SPRITE (12x12, chars C=light, F=dark) === */
const ARROW_DATA = parseCSEF('4.2C>3.1C2F>2.1C3F>1.1C4F>1C5F>^1C2F1C2F>1.3C2F>3.1C2F>^^3.3C>', 12);

/* drawArrow: render the arrow sprite at gfx origin with given scale/rotation/colors. */
function drawArrow(gfx, x, y, scale, rot, light, dark) {
  const oldC = CLR.C, oldF = CLR.F;
  CLR.C = light; CLR.F = dark;
  gfx.save();
  gfx.translateCanvas(x, y);
  gfx.rotateCanvas(rot);
  gfx.scaleCanvas(scale, scale);
  dsp(gfx, ARROW_DATA, 0, 0);
  gfx.restore();
  CLR.C = oldC; CLR.F = oldF;
}

/* === DANCERS === */
const DANCERS = [
  ['PLATANUS', [
    sp('9.1.1<9.4.9.1<1N1<3U9.8.2r1<5U8.8.1r1<1r2U3,8.8.1[1r2U2,1A1,8.7.1[1<1[2{2,1A1,8.8.1[2U1<4,8.9.1.1U1{3,9.9.2.1{1,1[9.1.9.1.3[2G9.9.1,5G1,8.8.2,5G2,7.7.2,1.2E4G2,6.6.2,9G3,4.5.4<4G2<3r2,4.4.1G3r6<2r2[1G5.4.2G2[6r2[3G5.4.1E2G7[3G2<1G4.5.1E9G3<1r1[1G3.6.4E1{3G2<2r2[1G3.9.3{1.2G2r2[2G3.8.3,3.5G5.7.2,5.1,1{8.7.3,2.>', 24),
    sp('8.1I9.6.7.1I1N1I9.5.6.2r1I4U9.2.6.1r1<1r5U9.1.6.1[1r2U4,9.1.5.1[1<1[1U1,1A1,1A1,9.1.6.1[2U1,1A1,1A1,9.1.8.1<5,1<9.9.1.3,6.2,3.2.2,5.1[3{1[3.3,1G3.2.1G4,3G3[3G3,1<1G3.2.1G1<1.3,7G3,1.1<1G3.1.1G1[1r1<3.2E3G2E3.1G1<1r1G2.1.1G1[1r1<2G2.5E3.1G2<1r1G2.1.1G1[2r1<9G3G1<2r1G2.1.1G2[2r1<9G2<2r1[1G2.1.2G1[2r2<7G2<2r1[2G2.2.2G1[2r3<3G3<2r1[2G3.3.1G2[3r5<3r2[1G4.3.2G3[7r3[1G5.4.3G9[2G6.6.9G1G8.9.2,1.2,9.1.8.3,1.3,9.', 24),
    sp('8.1I9.6.7.1I1N1I3U9.2.6.2r1I5U9.1.6.1r1<1r2U3,9.1.6.1[1r2U2,1A1,9.1.5.1[1<1[2{2,1A1,9.1.6.1[2U1<4,4.2,4.8.1U1{3,4.3,1G3.9.1{1,1[4.2,1<1r1[1G2.6.2G3[2G2.2,1.1<1r1[1G2.5.8G3,2.1<1r1[1G2.5.3,5G2,3.1<1r1[1G2.4.2,2.4E2G3.2<1r1[1G2.4.2,3.1E5G1.2<1r1[2G2.3.1<3,8G2<1r1[1G4.2.1G2r3<6G2<1r2[1G4.2.1G2[2r2<4G2<1r2[1G5.2.2G2[2r6<2r1[1G6.3.2G2[7r2[1G7.4.3G8[2G7.5.9G1G9.7.2,3.2,9.1.7.2,3.1,1{9.1.7.3,2.3,9.', 24),
    sp('~~8.1I9.6.7.1I1N1I9.5.6.2r1I4U9.2.6.1r1<1r5U9.1.6.1[1r2U4,9.1.5.1[1<1[1U1,1A1,1A1,9.1.6.1[2U1,1A1,1A1,9.1.8.1<5,1<9.9.1[3,1[9.1.7.2G5[2G4,4.6.9G1G6,2.6.1{2,4G1E5.1<3,1.7.3,3E5G1<2r1G2.5.1r1<1G3,5G2<2r1[1G2.4.2r2<1G3,3G2<2r1[2G2.3.1G1[2r3<2{1G3<2r1[2G3.3.1G2[3r5<3r2[1G4.3.2G3[7r3[1G5.4.3G9[2G6.5.1,9G1G8.4.4,4.2,9.1.3.3,6.3,9.', 24),
  ]],
  ['LA PARKA', [
    sp('8.2X4.1X2.1X6.9.1X1?1<1?3]2Y6.8.1X1.1<1?1<1?3]2c1X4.9.1.1?1<1?1<3]3c4.9.1.9{5.9.2.7{6.9.3.5[7.9.2.1[1<5[6.9.1.1[1<1r1[1M2J1[6.9.1.1[1<1r1M4J6.9.2.1<1r1M1A2J1A6.9.2.2r2J2]1J6.9.3.1M5J6.9.1.2<1.2J2.2<5.9.1J2r6<1r1J4.7.3J2[6r3J3.6.3J3.5[2.2J3.4.3J5.5<2.2J3.3.1G2[6.5<1.3J3.4.1G3[2r8<2J4.4.2G3[2r1<5r1<1r5.5.2G3[1r1<5r1<2[4.6.2G4[5<2[1G4.5.2J3G8[1G5.4.4J1.9G6.4.2J9.2J7.5.1J9.2J7.9.6.3J6.', 24),
    sp('~~~8.2X4.1X2.1X6.9.1X1?1<1?3]2Y6.8.1X1.1<1?1<1?3]2c1X4.9.1.1?1<1?1<3]3c4.9.1.9{5.9.2.7{6.9.3.5[7.9.2.1[1<5[6.9.1.1[1<1r1[1M2J1[6.9.1.1[1<1r1M4J4.1X1.9.2.1<1r1M1A2J1A3.3]9.2.2r2J2]1J3.3]9.3.1M5J4.2J4.2[2.2J2<1.2J2.2<2.2J1.3.1G1[1.4J2r6<1r1J1.2J1.3.1G1[3J2.2[6r5J1.3.1G2[6.5[2.3J2.3.1G2[6.5<7.4.1G2[3r8<6.4.2G2[3r1<5r1<1r5.5.2G3[1r1<5r1<2[4.6.2G4[5<2[1G4.7.3G8[1G1J4.9.9G3J3.9.1.3J6.3J2.', 24),
    sp('5.2X4.1X2.1X9.6.1X1?1<1?3]2Y9.5.1X1.1<1?1<1?3]2c1X7.7.1?1<1?1<3]3c7.7.9{8.8.7{9.9.5[9.1.8.1[1<3[1<9.1.7.1[2<1M3J1<9.7.1[1<1M4J1<9.8.1<1J1A2J1A9.1.8.1r2J2]1J9.1.9.1M4J9.1.7.2<1.2J2.2<8.1.1J2.3J2r6<1r2J6.1.6J2[6r6J3.1G2[1<5.5[5.3J2.1G1[2r2<3.1?5<6.1<2.1G2[2r2<3?9<2r1[2.1.1G2[2r9<1<4r1[1G2.1.2G2[3r1<5r1<3r2[2G2.2.2G2[2r1<5r1<2r2[2G3.3.2G4[5<3[3G4.4.3G8[3G6.6.9G1G8.8.2J2.2J9.1.7.3J2.2J9.1.7.3J2.3J9.', 24),
  ]],
];

const TITLE_SPRITE = sp('2.9B9B9B2.1.2B1A1B9A9A5A2B1.1.1B1A1<2A3<1A2<1A2r2A1r2A1r1A2[1A3[1A1B1.1.1B1A2<1A1<3A1<2A1r1A1r1A2r1A1r1A1[2A1[3A1B1.1.1B2A3<1A1<1A2<1A1r1A1r1A4r1A2[1A3[1A1B1.1.2B1A2<2A1<1A1<2A2r2A1r1A2r1A1[4A1[1A1B1.2.1B2A1<2A1<1A2<1A1r1A1r1A1r1A2r1A3[1A2[1A1B1.1.2B9A9A8A1B1.1.1B1A6G3A2E2A2E9A1A2B1.1.1B1A2G3A2G2A1E1A1E1A1E3A4G2A2G1A1B1.1.1B1A2G3A2G2A1E1A1E1A2E2A2G2A1G1A1G1A1G2B1.1B1A2G2A2G3A2E2A1E3A2G2A1G1A1G1A1G1A1B1.1B1A5G8A2E3A1G2A1G1A1G1A1G1A1B1.1B1A4G4A1G1A1G1A1G3A1G1A3G2A3G1A1B2B1A2G1A2G3A1G1A1G1A2G1A2G1A1G1A2G1A1G1A1G1A1B2B1A2G2A3G1A1G1A1G1A1G1A1G1A1G1A1G2A1G1A1G1A1G1A1B1B1A3G1A4B1A3G1A1G3A1G1A4G1A1G1A1G1A1B2B3A5B7A1B9A3A1B1.5B2.9B9B4B1.', 31);

/* === GAMEPLAY CONSTANTS === */
const DIR = { L: 0, D: 1, U: 2, R: 3 }; // Direction lane indices (0: Left, 1: Down, 2: Up, 3: Right)

// Base arrow sprite points UP; rotate to face each lane
const DIR_ROT = [-Math.PI / 2, Math.PI, 0, Math.PI / 2]; // Rotation in radians for Left (-90°), Down (180°), Up (0°), Right (90°)
const ARROW_LIGHT = [COL.pL, COL.pD, COL.pU, COL.pR]; // Highlight fill colors per direction lane
const ARROW_DARK = [COL.pLD, COL.pDD, COL.pUD, COL.pRD]; // Highlight border colors per direction lane
const clamp = (v, a, b) => Math.max(a, Math.min(b, v));

const STATE = { SPLASH: -1, TITLE: 0, CHARSEL: 1, SONGSEL: 2, BATTLE: 3, WIN: 4 }; // Game flow states
const state = { v: STATE.SPLASH, t: 0, countdownStart: 0, songDecoded: null, songStart: 0, songEnd: 0, winner: -1 };

const players = [
  { name: 'PLATANUS', sprites: DANCERS[0][1], center: { x: 157, y: 380 }, box: { x: 85, y: 255, w: 145, h: 220 },
    combo: 0, score: 0, arrows: [], notes: [], keys: ['P1_L', 'P1_D', 'P1_U', 'P1_R'],
    dirKeys: [['P1_L', 'P1_4', 'P1_1'], ['P1_D', 'P1_5'], ['P1_U', 'P1_2'], ['P1_R', 'P1_6', 'P1_3']],
    arrowBounce: [0, 0, 0, 0],
    color: 0xff5577, perfect: 0, good: 0, miss: 0, seq: 0, gfx: null,
    poseIdx: 0, pulseDx: 0, pulseDy: 0, pulseT: 0 },
  { name: 'LA PARKA', sprites: DANCERS[1][1], center: { x: 642, y: 400 }, box: { x: 570, y: 255, w: 145, h: 220 },
    combo: 0, score: 0, arrows: [], notes: [], keys: ['P2_L', 'P2_D', 'P2_U', 'P2_R'],
    dirKeys: [['P2_L', 'P2_4', 'P2_1'], ['P2_D', 'P2_5'], ['P2_U', 'P2_2'], ['P2_R', 'P2_6', 'P2_3']],
    arrowBounce: [0, 0, 0, 0],
    color: 0x77dd55, perfect: 0, good: 0, miss: 0, seq: 0, gfx: null,
    poseIdx: 0, pulseDx: 0, pulseDy: 0, pulseT: 0 },
];

// Global runtime game state and visual container references
const G = {
  fxLayer: null, titleLayer: null, winLayer: null, tugGfx: null, splashLayer: null,
  worldLayer: null, hudLayer: null,
  bgGfx: null, stageGfx: null, floorGfx: null,
  playerLayers: [],
  notes: [], notesSpawned: 0, notesTotal: 0,
  bar: 0, barVis: 0, // Tug-of-war bar value (-100 to +100) and smoothly interpolated visual position
  cam: null, uiCam: null, camX: 400, camY: 300, camZ: 1, // Camera tracking coordinates & zoom level
  music: null, lastTurn: -1, turnT: 0, turnTxt: null, // Active music instance, turn tracking, and turn HUD text
  audioStart: 0, songLen: 0, blurred: false, // Audio start timestamp and song total length in seconds
  difficulty: DEFAULT_DIFFICULTY, // Difficulty setting: 0 = EASY, 1 = MEDIUM, 2 = HARD
  mode: '2p', selSong: 0, charSel: [{cursor: 0, ok: false}, {cursor: 0, ok: false}], aiPicking: false,
};

new Phaser.Game({
  type: Phaser.AUTO, width: W, height: H, parent: 'game-root',
  backgroundColor: '#000000', pixelArt: true,
  scene: { create, update },
});

function updateStagePlayer(idx, fighterIdx) {
  G.charSel[idx].cursor = fighterIdx;
  const f = DANCERS[fighterIdx];
  players[idx].name = f[0];
  players[idx].sprites = f[1];
  players[idx].poseIdx = 0;
  const g = G.playerLayers[idx];
  if (g) {
    g.clear();
    dsp(g, f[1][0], 0, 0, { shadow: true });
  }
}

function create() {
  const s = this;
  G.worldLayer = s.add.container(0, 0);
  G.fxLayer = s.add.container(0, 0);
  G.hudLayer = s.add.container(0, 0).setDepth(100);
  G.titleLayer = s.add.container(0, 0).setDepth(200);
  G.winLayer = s.add.container(0, 0).setDepth(200);
  G.splashLayer = s.add.container(0, 0).setDepth(300);

  drawBackground(s);
  drawStage(s);
  drawFloor(s);
  drawPlayer(s, 0);
  drawPlayer(s, 1);
  drawTugBar(s);
  drawArrowGfx(s);
  G.worldLayer.add([G.bgGfx, G.stageGfx, G.floorGfx, G.playerLayers[0], G.playerLayers[1], G.fxLayer]);

  // Two cameras: main zooms/pans on the world, UI cam keeps HUD fixed
  G.cam = s.cameras.main;
  G.uiCam = s.cameras.add(0, 0, W, H);
  G.cam.ignore([G.hudLayer, G.titleLayer, G.winLayer, G.splashLayer]);
  G.uiCam.ignore([G.worldLayer]);

  G.turnTxt = cTxt(s, W / 2, 90, '', 22, '#fff200', 1).setAlpha(0);
  for (let i = 0; i < 2; i++) players[i].comboTxt = cTxt(s, i ? 650 : 150, 46, '', 16, i ? '#77dd55' : '#ff5577', 1);
  G.hudLayer.add([G.tugGfx, ...players[0].arrows, ...players[1].arrows, G.turnTxt, players[0].comboTxt, players[1].comboTxt]);
  G.hudLayer.setVisible(false);

  clearInputs();

  if (SKIP_TO_GAMEPLAY) {
    updateStagePlayer(0, 0);
    updateStagePlayer(1, 1 % DANCERS.length);
    G.pendingStart = true;
    // menu song
    unpack(SONGS[0].data).then(song => {
      G.midiText = song;
      G.notesSong = decode(song);
      G.pendingStart = false;
      startBattle();
    });
  } else {
    drawSplashScreen(s);
    unpack(MIDI_SONG_FRUKO_Y_SUS_TESOS).then(song => {
      G.menuMidiText = song;
      startMenuMusic();
    });
  }

  G.blurred = false;
  const setBlur = (v) => { G.blurred = v; clearInputs(); };
  document.addEventListener('visibilitychange', () => setBlur(document.hidden));
  window.addEventListener('blur', () => setBlur(true));
  window.addEventListener('focus', () => setBlur(false));

  const unlockAudio = () => {
    const ctx = s.sound?.context;
    if (ctx && ctx.state === 'suspended') {
      ctx.resume().catch(() => {});
    }
    startMenuMusic();
  };
  window.addEventListener('pointerdown', unlockAudio);
  window.addEventListener('keydown', unlockAudio);
  s.input.on('pointerdown', unlockAudio);
}

function startMenuMusic() {
  if (state.v === STATE.BATTLE || state.v === STATE.WIN) return;
  if (!G.menuMidiText) return;
  const ctx = G.titleLayer?.scene?.sound?.context;
  if (!ctx) return;
  if (ctx.state === 'suspended') {
    ctx.resume().catch(() => {});
  }
  if (G.menuMusic) return;
  G.menuMusic = playMidi(ctx, G.menuMidiText, (len) => {
    G.menuSongLen = len;
  });
}

/* === DRAWING === */
function drawSplashScreen(s) {
  G.hudLayer.setVisible(false);
  G.titleLayer.setVisible(false);
  G.winLayer.setVisible(false);
  G.splashLayer.removeAll(true);
  G.splashLayer.setVisible(true);

  const bg = s.add.rectangle(W / 2, H / 2, W, H, 0x000000, 1);
  const txt = cTxt(s, W / 2, H / 2, '🇨🇴 Platanus hack 26, Bogotá 🇨🇴\n\npresenta', 24, '#ffffff', 1);
  txt.setAlign('center');
  G.splashLayer.add([bg, txt]);
}
function drawBackground(s) {
  const g = s.add.graphics(), FW = W + 2 * PAD, X0 = -PAD;
  g.setDepth(-100);
  // Sky gradient — deep blue top to pale horizon
  const sky = [0x1a3466, 0x254a82, 0x30609e, 0x4578b8, 0x5c90cc, 0x74a8dd, 0x8ec0ea, 0xa8d6f4];
  const bh = Math.ceil((H + 2 * PAD) / sky.length);
  for (let i = 0; i < sky.length; i++) { g.fillStyle(sky[i], 1); g.fillRect(X0, -PAD + i * bh, FW, bh + 1); }
  // Warm horizon glow
  g.fillStyle(0xf0e0c0, .08); g.fillRect(X0, 120, FW, 80);
  // Clouds — layered ellipses for volume
  for (const [cx, cy, rw, rh] of [[100, 20, 110, 30], [370, -8, 140, 36], [650, 42, 95, 26], [210, 88, 65, 18], [530, 72, 105, 25]]) {
    g.fillStyle(0xffffff, .32); g.fillEllipse(cx, cy, rw, rh);
    g.fillStyle(0xffffff, .16); g.fillEllipse(cx + rw * .22, cy - rh * .18, rw * .5, rh * .4);
    g.fillStyle(0xffffff, .08); g.fillEllipse(cx - rw * .18, cy + rh * .12, rw * .35, rh * .25);
  }
  G.bgGfx = g;
}

function drawStage(s) {
  const g = s.add.graphics(), X0 = -PAD, X1 = W + PAD, FW = X1 - X0;
  g.setDepth(-90);
  // Far mountains (misty green — Cerros Orientales)
  g.fillStyle(0x3a6a4a, 1);
  g.beginPath(); g.moveTo(X0, 400);
  for (let x = X0; x <= X1; x += 6) g.lineTo(x, 155 + Math.sin(x * .005) * 55 + Math.sin(x * .013 + 1) * 30 + Math.cos(x * .009) * 22);
  g.lineTo(X1, 400); g.closePath(); g.fillPath();
  // Mountain mist band
  g.fillStyle(0x90b8d4, .1); g.fillRect(X0, 185, FW, 45);
  // Near mountains (rich dark green)
  g.fillStyle(0x1e4a2a, 1);
  g.beginPath(); g.moveTo(X0, 400);
  for (let x = X0; x <= X1; x += 6) g.lineTo(x, 215 + Math.sin(x * .007 + 2) * 48 + Math.sin(x * .021) * 18);
  g.lineTo(X1, 400); g.closePath(); g.fillPath();
  // Highlight ridge on near mountains
  g.fillStyle(0x2a6a3a, .25);
  g.beginPath(); g.moveTo(X0, 400);
  for (let x = X0; x <= X1; x += 6) g.lineTo(x, 222 + Math.sin(x * .007 + 2) * 46 + Math.sin(x * .021) * 17);
  g.lineTo(X1, 400); g.closePath(); g.fillPath();
  // Tall buildings (Bogotá skyline)
  for (let x = X0 + 15; x < X1; x += 65) {
    const bh = 80 + ((x * 7 + 31) & 127), by = 400 - bh, bw = 28 + ((x * 3) & 7);
    g.fillStyle(0x484860, 1); g.fillRect(x, by, bw, bh);
    g.fillStyle(0x3a3a50, 1); g.fillRect(x + bw - 5, by, 5, bh);
    g.fillStyle(0x5a5a70, 1); g.fillRect(x, by, bw, 3);
    for (let wy = by + 10; wy < 392; wy += 12)
      for (let wx = x + 3; wx < x + bw - 3; wx += 8) {
        g.fillStyle(((wx * 3 + wy * 7) & 7) > 2 ? 0xffe888 : 0x28283a, ((wx + wy) & 3) ? .5 : .3);
        g.fillRect(wx, wy, 4, 6);
      }
  }
  // Colorful houses (La Candelaria)
  const hc = [0xc83030, 0x2266bb, 0xd4a020, 0x2e8a48, 0xd06828, 0x9a3388, 0xc75080, 0xe8e0c8];
  for (let x = X0, ci = 0; x < X1; x += 24, ci++) {
    const h = 30 + ((x * 3 + 17) & 31), by = 400 - h;
    g.fillStyle(hc[(ci * 3 + 1) % hc.length], 1); g.fillRect(x, by, 22, h);
    g.fillStyle(0x000000, .12); g.fillRect(x + 18, by, 4, h);
    g.fillStyle(0x000000, .18); g.fillRect(x - 1, by, 24, 2);
    g.fillStyle(0x1a1a1a, .65); g.fillRect(x + 8, 400 - 16, 6, 16);
    g.fillStyle(0xddddcc, .5); g.fillRect(x + 3, by + 8, 5, 5); g.fillRect(x + 14, by + 8, 5, 5);
  }

  // Festive carnival string lights across the plaza skyline
  g.lineStyle(1.5, 0x111122, 0.6);
  g.beginPath();
  g.moveTo(X0, 275);
  for (let x = X0; x <= X1; x += 12) {
    const ly = 275 + Math.sin(x * 0.012) * 18;
    g.lineTo(x, ly);
  }
  g.strokePath();
  const lightColors = [0xff3355, 0xffd166, 0x33cc66, 0x3399ff, 0xff66cc, 0xffaa00];
  for (let x = X0 + 10, li = 0; x < X1; x += 24, li++) {
    const ly = 275 + Math.sin(x * 0.012) * 18;
    const lc = lightColors[li % lightColors.length];
    g.fillStyle(lc, 0.9);
    g.fillCircle(x, ly + 4, 3.5);
    g.fillStyle(0xffffff, 0.8);
    g.fillCircle(x, ly + 3, 1.2);
  }

  // Dancing spectators / crowd along the plaza curb
  for (let x = X0 + 20, ci = 0; x < X1; x += 32, ci++) {
    if ((x > 110 && x < 230) || (x > 570 && x < 690)) continue; // Keep space around main fighters open
    const cy = 398;
    const shirtCol = [0xee4444, 0x3388ee, 0x44bb55, 0xf0aa20, 0x9944bb, 0xee7799][ci % 6];
    g.fillStyle(0x222233, 1);
    g.fillRect(x - 2, cy - 8, 2, 8); g.fillRect(x + 2, cy - 8, 2, 8);
    g.fillStyle(shirtCol, 1);
    g.fillRect(x - 4, cy - 18, 9, 10);
    g.fillStyle(0xdeac92, 1);
    g.fillCircle(x, cy - 22, 4);
    g.fillStyle(0x221100, 1);
    g.fillRect(x - 4, cy - 26, 8, 4);
    g.fillStyle(shirtCol, 1);
    if (ci % 2 === 0) {
      g.fillRect(x - 6, cy - 22, 3, 7); g.fillRect(x + 5, cy - 25, 3, 9);
    } else {
      g.fillRect(x - 6, cy - 25, 3, 9); g.fillRect(x + 5, cy - 22, 3, 7);
    }
  }

  G.stageGfx = g;
}

function drawFloor(s) {
  const g = s.add.graphics(), FW = W + 2 * PAD, X0 = -PAD, FH = H + PAD - 400;
  g.setDepth(-80);
  // Concrete plaza
  g.fillStyle(0x989490, 1); g.fillRect(X0, 400, FW, FH);
  // Tile joints
  g.fillStyle(0x000000, .06);
  for (let y = 400; y < H + PAD; y += 48) g.fillRect(X0, y, FW, 1);
  for (let x = X0; x < W + PAD; x += 48) g.fillRect(x, 400, 1, FH);
  // Depth darkening
  g.fillStyle(0x000000, .05); g.fillRect(X0, 500, FW, H + PAD - 500);
  // Surface specks
  for (let i = 0; i < 30; i++) {
    g.fillStyle(i & 1 ? 0x868280 : 0xaaa6a0, .4);
    g.fillRect(((i * 73 + 11) % W) + X0, 410 + ((i * 37) % (H - 420 + PAD)), 2, 1);
  }
  // Curb edge
  g.fillStyle(0x666660, 1); g.fillRect(X0, 400, FW, 3);
  g.fillStyle(0xb0aca6, .35); g.fillRect(X0, 400, FW, 1);
  G.floorGfx = g;
}

function drawPlayer(s, idx) {
  const p = players[idx];
  const g = s.add.graphics();
  // g.setDepth(-50);
  g.setScale(idx === 0 ? 9 : -9, 9);
  const pose = p.sprites[p.poseIdx % p.sprites.length];
  dsp(g, pose, 0, 0, { shadow: true });
  G.playerLayers[idx] = g;
  p.gfx = g;
}

function drawTugBar(s) {
  const g = s.add.graphics();
  G.hudLayer.add(g);
  G.tugGfx = g;
}

function drawTugGfx() {
  const g = G.tugGfx;
  if (!g) return;
  G.barVis += (G.bar - G.barVis) * 0.12;
  g.clear();
  const bx = 200, by = 18, bw = 400, bh = 20;
  // Thick pixel border (NES style)
  g.fillStyle(0x000000, 1); g.fillRect(bx - 8, by - 8, bw + 16, bh + 16);
  g.fillStyle(0x2a2a3a, 1); g.fillRect(bx - 4, by - 4, bw + 8, bh + 8);
  // Bar background
  g.fillStyle(0x0a0a14, 1); g.fillRect(bx, by, bw, bh);
  // Left half P1, right half P2
  g.fillStyle(COL.p1H, 0.3); g.fillRect(bx, by, bw / 2, bh);
  g.fillStyle(COL.p2H, 0.3); g.fillRect(bx + bw / 2, by, bw / 2, bh);
  // Center divider
  g.fillStyle(0xffffff, 0.5); g.fillRect(bx + bw / 2 - 1, by - 4, 2, bh + 8);
  // Pixel marker
  const mx = Math.round(bx + ((G.barVis + BAR_MAX) / (2 * BAR_MAX)) * bw);
  const danger = Math.abs(G.barVis) > 80;
  const mc = G.barVis >= 0 ? COL.p1H : COL.p2H;
  g.fillStyle(0x000000, 1); g.fillRect(mx - 8, by - 4, 16, bh + 8);
  g.fillStyle(danger && (state.t >> 4 & 1) ? 0xff3333 : mc, 1); g.fillRect(mx - 6, by - 2, 12, bh + 4);
  g.fillStyle(0xffffff, 1); g.fillRect(mx - 4, by, 4, 3);
}

function drawArrowGfx(s) {
  const p1xc = [65, 145, 225, 305];
  const p2xc = [490, 570, 650, 730];
  for (let pi = 0; pi < 2; pi++) {
    const xs = pi === 0 ? p1xc : p2xc;
    for (let i = 0; i < 4; i++) {
      const g = s.add.graphics();
      drawArrow(g, xs[i], HIT_Y, ARROW_SCALE, DIR_ROT[i], COL.arrowL, COL.arrowD);
      players[pi].arrows.push(g);
      G.hudLayer.add(g);
    }
  }
  // Labels (keyboard hints)
  const p1Keys = ['A', 'S', 'W', 'D'];
  const p2Keys = ['\u2190', '\u2193', '\u2191', '\u2192'];
  for (let i = 0; i < 4; i++) {
    G.hudLayer.add(cTxt(s, p1xc[i], 540, p1Keys[i], 9, '#aaaacc'));
    G.hudLayer.add(cTxt(s, p2xc[i], 540, p2Keys[i], 9, '#aaaacc'));
  }
}

function drawTitleScreen(s) {
  G.hudLayer.setVisible(false);
  G.winLayer.setVisible(false);
  G.titleLayer.removeAll(true);
  G.titleLayer.setVisible(true);

  // Black background
  const bg = s.add.rectangle(W / 2, H / 2, W, H, 0x000000, 1);
  G.titleLayer.add(bg);

  // Title sprite (31x19) centered near top
  const titleGfx = s.add.graphics();
  titleGfx.setScale(10, 10);
  titleGfx.x = W / 2 - 20;
  titleGfx.y = 150;
  dsp(titleGfx, TITLE_SPRITE, 0, 0, {});
  G.titleLayer.add(titleGfx);
  G.titleSpriteGfx = titleGfx;

  // Mode selector text (will be updated by updateTitleMode)
  G.titleModeTxts = [];
  updateTitleMode(s);

  // Bottom text
  const startTxt = cTxt(s, W / 2, H - 50, 'PRESIONA CUALQUIER TECLA', 16, '#ffffff', 1);
  G.titleLayer.add(startTxt);
  G.startText = startTxt;

  // 4 dancing characters: 2 on the left, 2 on the right
  // Cycle through DANCERS if fewer than 4
  const dCount = DANCERS.length;
  const dancerIndices = [0 % dCount, 1 % dCount, (dCount > 2 ? 2 : 0) % dCount, (dCount > 3 ? 3 : 1) % dCount];
  G.titleDancers = [];
  const positions = [
    { x: 100, y: 420, flip: 1 },   // left back
    { x: 185, y: 440, flip: 1 },   // left front
    { x: W - 185, y: 440, flip: -1 }, // right front
    { x: W - 100, y: 420, flip: -1 }, // right back
  ];
  for (let i = 0; i < 4; i++) {
    const di = dancerIndices[i];
    const sprites = DANCERS[di][1];
    const g = s.add.graphics();
    const scale = 7;
    g.setScale(positions[i].flip * scale, scale);
    g.x = positions[i].x;
    g.y = positions[i].y;
    const poseIdx = 0;
    dsp(g, sprites[poseIdx], 0, 0, { shadow: true });
    G.titleLayer.add(g);
    G.titleDancers.push({ gfx: g, sprites, poseIdx, dancerIdx: di, timer: 0 });
  }
}

function updateTitleMode(s) {
  // Remove old mode texts
  if (G.titleModeTxts) {
    for (const t of G.titleModeTxts) { if (t && t.active) t.destroy(); }
  }
  const m1Sel = G.mode === '1p';
  const m2Sel = G.mode === '2p';
  const m1Tx = cTxt(s, W / 2 - 20, H / 2 + 30, m1Sel ? '> 1 JUGADOR' : '  1 JUGADOR', 22, m1Sel ? '#ffffff' : '#555555', 1);
  const m2Tx = cTxt(s, W / 2 - 20, H / 2 + 70, m2Sel ? '> 2 JUGADORES' : '  2 JUGADORES', 22, m2Sel ? '#ffffff' : '#555555', 1);
  G.titleLayer.add([m1Tx, m2Tx]);
  G.titleModeTxts = [m1Tx, m2Tx];
}

function drawCharSelScreen(s) {
  G.hudLayer.setVisible(false);
  G.winLayer.setVisible(false);
  G.titleLayer.removeAll(true);
  G.titleLayer.setVisible(true);

  const t1 = cTxt(s, W / 2, 50, 'ELIGE TU PERSONAJE', 32, '#ffffff', 1);
  const t2 = cTxt(s, W / 2, 85, G.mode === '1p' ? 'MODO 1 JUGADOR' : 'MODO 2 JUGADORES', 16, '#cccccc', 1);
  G.titleLayer.add([t1, t2]);

  // Left Player (index 0)
  const p0x = players[0].center.x;
  G.titleLayer.add(cTxt(s, p0x, 155, G.mode === '1p' ? 'RIVAL (CPU)' : 'JUGADOR 1', 16, '#ffffff', 1));
  if (G.mode === '1p') {
    if (G.aiPicking) {
      G.titleLayer.add(cTxt(s, p0x, 185, 'ROULETTE', 18, '#ffffff', 1));
    } else if (G.charSel[0].ok) {
      G.titleLayer.add(cTxt(s, p0x, 185, 'LISTO', 20, '#ffffff', 1));
    } else {
      G.titleLayer.add(cTxt(s, p0x, 185, 'ESPERANDO...', 14, '#666666', 1));
    }
  } else {
    if (G.charSel[0].ok) {
      G.titleLayer.add(cTxt(s, p0x, 185, 'LISTO', 20, '#ffffff', 1));
    }
  }
  G.titleLayer.add(cTxt(s, p0x, 488, players[0].name, 22, '#ffffff', 1));

  // Right Player (index 1)
  const p1x = players[1].center.x;
  G.titleLayer.add(cTxt(s, p1x, 155, G.mode === '1p' ? 'TU PERSONAJE' : 'JUGADOR 2', 16, '#ffffff', 1));
  if (G.charSel[1].ok) {
    G.titleLayer.add(cTxt(s, p1x, 185, 'LISTO', 20, '#ffffff', 1));
  }
  G.titleLayer.add(cTxt(s, p1x, 488, players[1].name, 22, '#ffffff', 1));
}

function drawSongSelScreen(s) {
  G.hudLayer.setVisible(false);
  G.winLayer.setVisible(false);
  G.titleLayer.removeAll(true);
  G.titleLayer.setVisible(true);

  const t1 = cTxt(s, W / 2, 50, 'SELECCIONA LA CANCIÓN', 32, '#ffffff', 1);
  G.titleLayer.add([t1]);

  G.songTexts = [];
  const startY = 140, gapY = 60;
  for (let i = 0; i < SONGS.length; i++) {
    const sel = i === G.selSong, sy = startY + i * gapY;
    const name = cTxt(s, W / 2, sy, (sel ? '> ' : '') + SONGS[i].name + (sel ? ' <' : ''), sel ? 24 : 18, sel ? '#ffffff' : '#555555', 1);
    const meta = cTxt(s, W / 2, sy + 25, SONGS[i].genre + '  •  ' + SONGS[i].bpm, 12, sel ? '#aaaaaa' : '#333333', 0);
    G.titleLayer.add([name, meta]);
    G.songTexts.push(name);
  }

  // Difficulty Pill
  const diffTxts = ['FÁCIL', 'MEDIO', 'DIFÍCIL'];
  const diffTx = cTxt(s, W / 2, 480, '< DIFICULTAD: ' + diffTxts[G.difficulty] + ' >', 20, '#ffffff', 1);
  G.titleLayer.add([diffTx]);
}

function showWinScreen(winner) {
  G.hudLayer.setVisible(false);
  G.titleLayer.setVisible(false);
  G.winLayer.removeAll(true);
  G.winLayer.setVisible(true);

  const s = G.titleLayer.scene;
  const bg = s.add.rectangle(W / 2, H / 2, W, H, 0x000000, 0.65);
  const col = winner === 0 ? '#ff5577' : '#77dd55';
  const t1 = cTxt(s, W / 2, H / 2 - 90, '¡K.O.!', 68, '#fff200', 1).setStroke('#000000', 6);
  const t2 = cTxt(s, W / 2, H / 2 - 20, `${players[winner].name} GANA LA RUMBA`, 28, col, 1).setStroke('#000000', 4);
  const w = players[winner];
  const t3 = cTxt(s, W / 2, H / 2 + 35, `PERFECT: ${w.perfect}   GOOD: ${w.good}   MISS: ${w.miss}`, 16, '#ffffff', 1).setStroke('#000000', 3);
  const t4 = cTxt(s, W / 2, H / 2 + 90, 'PRESIONA START PARA VOLVER', 20, '#ffd166', 1).setStroke('#000000', 4);

  G.winLayer.add([bg, t1, t2, t3, t4]);
  G.winText = t4;
}

/* === STATE TRANSITIONS === */
function startBattle() {
  if (G.music) { G.music.stop(); G.music = null; }
  if (G.menuMusic) { G.menuMusic.stop(); G.menuMusic = null; }
  state.v = STATE.BATTLE;
  state.t = 0;
  state.winner = -1;
  state.songStart = 0;
  state.songEnd = 0;
  G.audioStart = 0; G.songLen = 0;
  G.bar = 0; G.barVis = 0;
  G.lastTurn = -1;
  for (const p of players) {
    p.combo = 0; p.score = 0;
    p.perfect = 0; p.good = 0; p.miss = 0;
    p.arrowBounce = [0, 0, 0, 0];
    if (p.notes) {
      for (const n of p.notes) { if (n.gfx) { n.gfx.destroy(); n.gfx = null; } }
    }
    p.notes = []; p.seq = 0;
    if (p.comboTxt) p.comboTxt.setText('');
  }
  G.notesSpawned = 0;
  if (G.notesSong) buildSchedule();
  G.titleLayer.setVisible(false);
  G.winLayer.setVisible(false);
  G.hudLayer.setVisible(true);
  clearInputs();
  if (G.notesSong) startMusic();
}

function startMusic() {
  if (!G.notesSong) return;
  const ctx = G.titleLayer.scene.sound.context;
  G.audioStart = ctx.currentTime + 0.08; // playMidi internal base offset
  G.music = playMidi(ctx, G.midiText, len => {
    if (state.v === STATE.BATTLE) G.songLen = len;
  });
}

function endBattle() {
  if (G.music) { G.music.stop(); G.music = null; }
  let w;
  if (G.bar >= BAR_MAX) w = 0;
  else if (G.bar <= -BAR_MAX) w = 1;
  else w = G.bar > 0 ? 0 : 1;
  state.v = STATE.WIN;
  state.winner = w;
  for (const p of players) {
    if (p.notes) {
      for (const n of p.notes) { if (n.gfx) { n.gfx.destroy(); n.gfx = null; } }
    }
    p.notes = [];
  }
  G.hudLayer.setVisible(false);
  clearInputs();
  showWinScreen(w);
}

function buildSchedule() {
  G.notes = [];
  const song = G.notesSong;
  const tempos = song.events.filter(e => e.kind === 'T');
  const div = song.division;
  const diff = G.difficulty; // 0=EASY 1=MEDIUM 2=HARD

  // Min seconds between arrows per difficulty (configured in DIFFICULTY_GAPS at top)
  const gaps = DIFFICULTY_GAPS;

  // Gather every melodic/harmonic attack from every instrument
  const cand = [];
  for (const e of song.events) {
    if (e.kind !== 'N' || e.channel === 9) continue;
    const t = secondsAt(e.tick, tempos, div);
    if (t < LEAD_IN) continue;
    cand.push({ t, tick: e.tick, pitch: e.pitch });
  }
  cand.sort((a, b) => a.t - b.t);

  // Group simultaneous attacks (~same instant). Within a group the HIGHEST
  // pitch is the primary note; a lone low note is primary too. Everything
  // else is secondary accompaniment.
  const groups = [];
  for (const c of cand) {
    const g = groups.at(-1);
    if (g && c.t - g.t < 0.05) g.push(c);
    else groups.push([c]);
  }

  const kept = [];
  let lastT = -9;
  for (const g of groups) {
    g.sort((a, b) => b.pitch - a.pitch);
    const seen = {};
    let rank = 0;
    for (const n of g) {
      if (seen[n.pitch]) continue; // same pitch doubled across instruments
      seen[n.pitch] = 1;
      const primary = rank === 0;
      rank++;
      if (diff === 0 && !primary) continue;
      if (diff === 1 && !primary && n.tick % (div / 2) !== 0) continue;
      if (n.t - lastT < gaps[diff]) continue;
      lastT = n.t;
      kept.push(n);
    }
  }

  // Lane from pitch quartiles spread across the 4 directions
  const ps = kept.map(k => k.pitch).sort((a, b) => a - b);
  const q = i => ps[Math.floor((ps.length - 1) * i / 4)] ?? 60;
  for (const k of kept) {
    let dir;
    if (k.pitch < q(1)) dir = DIR.L;
    else if (k.pitch < q(2)) dir = DIR.D;
    else if (k.pitch < q(3)) dir = DIR.U;
    else dir = DIR.R;
    G.notes.push({ time: k.t, dir, turn: Math.floor(k.t / SEC_LEN) % 2 });
  }
  G.notesTotal = G.notes.length;
}

/* === UPDATE LOOP === */
function update(time, delta) {
  if (G.blurred) {
    clearInputs();
    return;
  }
  if (delta > 500) delta = 0;
  state.t += delta;

  const s = G.titleLayer.scene;
  
  if (state.v === STATE.SPLASH) {
    if (state.t > 2000 && !G.splashFading) {
      G.splashFading = true;
      drawTitleScreen(s); // Draw title screen so it's under the splash screen during fade out
      s.tweens.add({
        targets: G.splashLayer,
        alpha: 0,
        duration: 1000,
        onComplete: () => {
          state.v = STATE.TITLE;
          state.t = 0;
          G.splashLayer.setVisible(false);
        }
      });
    }
    // Also animate dancers during the fade out
    if (G.splashFading && G.titleDancers) {
      const DANCE_INTERVAL = 400;
      for (const d of G.titleDancers) {
        d.timer += delta;
        if (d.timer >= DANCE_INTERVAL) {
          d.timer -= DANCE_INTERVAL;
          d.poseIdx = (d.poseIdx + 1) % d.sprites.length;
          d.gfx.clear();
          dsp(d.gfx, d.sprites[d.poseIdx], 0, 0, { shadow: true });
        }
      }
    }
  } else if (state.v === STATE.TITLE) {
    if (justPressed.P1_U || justPressed.P1_D || justPressed.P2_U || justPressed.P2_D) {
      G.mode = G.mode === '1p' ? '2p' : '1p';
      updateTitleMode(s);
    }
    if (justPressed.START1 || justPressed.START2 || justPressed.P1_1 || justPressed.P2_1) {
      state.v = STATE.CHARSEL;
      G.charSel[0] = { cursor: 0, ok: false };
      G.charSel[1] = { cursor: 1 % DANCERS.length, ok: false };
      G.aiPicking = false;
      G.waitSong = false;
      updateStagePlayer(0, G.charSel[0].cursor);
      updateStagePlayer(1, G.charSel[1].cursor);
      drawCharSelScreen(s);
    }
    // Animate dancing characters on title screen
    if (G.titleDancers) {
      const DANCE_INTERVAL = 400; // ms between pose changes
      for (const d of G.titleDancers) {
        d.timer += delta;
        if (d.timer >= DANCE_INTERVAL) {
          d.timer -= DANCE_INTERVAL;
          d.poseIdx = (d.poseIdx + 1) % d.sprites.length;
          d.gfx.clear();
          dsp(d.gfx, d.sprites[d.poseIdx], 0, 0, { shadow: true });
        }
      }
    }
    if (G.startText && G.startText.active) {
      G.startText.setAlpha(0.5 + 0.5 * Math.sin(state.t * 0.003));
    }
  } else if (state.v === STATE.CHARSEL) {
    if (G.mode === '1p') {
      if (!G.charSel[1].ok) {
        if (justPressed.P1_U || justPressed.P1_D || justPressed.P2_U || justPressed.P2_D) {
          updateStagePlayer(1, (G.charSel[1].cursor + 1) % DANCERS.length);
          drawCharSelScreen(s);
        }
        if (justPressed.P1_1 || justPressed.P2_1 || justPressed.START1 || justPressed.START2) {
          G.charSel[1].ok = true;
          G.aiPicking = true;
          G.aiTick = 0;
          G.aiTicksLeft = 12;
          G.charSel[0].ok = false;
          playHurt();
          drawCharSelScreen(s);
        }
      }
      if (G.aiPicking) {
        G.aiTick += delta;
        if (G.aiTick > 80) {
          G.aiTick -= 80;
          G.aiTicksLeft--;
          updateStagePlayer(0, (G.charSel[0].cursor + 1) % DANCERS.length);
          playHurt();
          if (G.aiTicksLeft <= 0) {
            if (DANCERS.length > 1 && G.charSel[0].cursor === G.charSel[1].cursor) {
              updateStagePlayer(0, (G.charSel[0].cursor + 1) % DANCERS.length);
            }
            G.aiPicking = false;
            G.charSel[0].ok = true;
          }
          drawCharSelScreen(s);
        }
      }
      if (G.charSel[0].ok && G.charSel[1].ok && !G.waitSong) {
        G.waitSong = true;
        setTimeout(() => {
          state.v = STATE.SONGSEL;
          G.waitSong = false;
          drawSongSelScreen(s);
        }, 750);
      }
    } else {
      if (!G.charSel[0].ok) {
        if (justPressed.P1_U || justPressed.P1_D) {
          updateStagePlayer(0, (G.charSel[0].cursor + 1) % DANCERS.length);
          drawCharSelScreen(s);
        }
        if (justPressed.P1_1 || justPressed.START1) {
          G.charSel[0].ok = true;
          playHurt();
          drawCharSelScreen(s);
        }
      }
      if (!G.charSel[1].ok) {
        if (justPressed.P2_U || justPressed.P2_D) {
          updateStagePlayer(1, (G.charSel[1].cursor + 1) % DANCERS.length);
          drawCharSelScreen(s);
        }
        if (justPressed.P2_1 || justPressed.START2) {
          G.charSel[1].ok = true;
          playHurt();
          drawCharSelScreen(s);
        }
      }
      if (G.charSel[0].ok && G.charSel[1].ok && !G.waitSong) {
        G.waitSong = true;
        setTimeout(() => {
          state.v = STATE.SONGSEL;
          G.waitSong = false;
          drawSongSelScreen(s);
        }, 750);
      }
    }
  } else if (state.v === STATE.SONGSEL) {
    if (justPressed.P1_U || justPressed.P2_U) {
      G.selSong = (G.selSong - 1 + SONGS.length) % SONGS.length;
      drawSongSelScreen(s);
    }
    if (justPressed.P1_D || justPressed.P2_D) {
      G.selSong = (G.selSong + 1) % SONGS.length;
      drawSongSelScreen(s);
    }
    if (justPressed.P1_L || justPressed.P2_L) {
      if (G.difficulty > 0) { G.difficulty--; drawSongSelScreen(s); }
    }
    if (justPressed.P1_R || justPressed.P2_R) {
      if (G.difficulty < 2) { G.difficulty++; drawSongSelScreen(s); }
    }
    if (justPressed.START1 || justPressed.START2 || justPressed.P1_1 || justPressed.P2_1) {
      if (!G.pendingStart && SONGS.length > 0) {
        G.pendingStart = true;
        unpack(SONGS[G.selSong].data).then(song => {
          G.midiText = song;
          G.notesSong = decode(song);
          G.pendingStart = false;
          startBattle();
        });
      }
    }
    if (G.songTexts) {
      for (let i = 0; i < G.songTexts.length; i++) {
        if (i === G.selSong) G.songTexts[i].setAngle(Math.sin(state.t * 0.01) * 2.5);
        else G.songTexts[i].setAngle(0);
      }
    }
  } else if (state.v === STATE.BATTLE) {
    updateBattle(delta);
  } else if (state.v === STATE.WIN) {
    if (G.winText && G.winText.active) {
      G.winText.setScale(1 + Math.sin(state.t * 0.005) * 0.08);
    }
    if (justPressed.START1 || justPressed.START2 || justPressed.P1_1 || justPressed.P2_1) {
      state.v = STATE.TITLE;
      drawTitleScreen(s);
      startMenuMusic();
    }
  }

  drawDynamicElements();
  animateCharacters(delta);
  updateCamera();

  for (const k in justPressed) justPressed[k] = false;
  for (const k in justReleased) justReleased[k] = false;
}

function drawDynamicElements() {
  drawTugGfx();
}

function animateCharacters(delta) {
  const bob = state.v === STATE.TITLE ? 0 : Math.sin(state.t * 0.005) * 2;
  for (let i = 0; i < 2; i++) {
    const p = players[i];
    const g = G.playerLayers[i];
    if (!g) continue;

    // Decay pulse offset back to center (fast snap-back)
    if (p.pulseT > 0) {
      p.pulseT = Math.max(0, p.pulseT - delta * 0.008);
      const ease = p.pulseT * p.pulseT; // quadratic ease-out
      p.pulseDx *= ease > 0 ? Math.pow(0.92, delta / 16) : 0;
      p.pulseDy *= ease > 0 ? Math.pow(0.92, delta / 16) : 0;
    } else {
      p.pulseDx = 0;
      p.pulseDy = 0;
    }

    g.x = p.center.x + p.pulseDx;
    g.y = p.center.y + bob - 40 + p.pulseDy;
  }
}

/* Trigger a dance pose change for the player on a successful note hit */
function triggerDancePose(pi, dir) {
  const p = players[pi];
  const numPoses = p.sprites.length;
  if (numPoses <= 0) return;

  // Map direction to pose index, cycling if fewer poses than 4 arrows
  const newPose = dir % numPoses;
  p.poseIdx = newPose;

  // Redraw the sprite with the new pose
  const g = G.playerLayers[pi];
  if (g) {
    g.clear();
    const pose = p.sprites[p.poseIdx];
    dsp(g, pose, 0, 0, { shadow: true });
  }

  // Start pulsation: random direction snap
  const angle = Math.random() * Math.PI * 2;
  const strength = 8 + Math.random() * 6; // 8-14px snap
  p.pulseDx = Math.cos(angle) * strength;
  p.pulseDy = Math.sin(angle) * strength;
  p.pulseT = 1.0;
}

function getSongTime() {
  const ctx = G.titleLayer?.scene?.sound?.context;
  if (!ctx || !G.audioStart) return 0;
  return ctx.currentTime - G.audioStart;
}

function updateCamera() {
  if (!G.cam) return;
  let tx = W / 2, ty = 300, tz = 1;
  if (state.v === STATE.BATTLE) {
    const songT = getSongTime();
    const hasNotes = players[0].notes.length > 0 || players[1].notes.length > 0;
    if (hasNotes) {
      const turn = Math.floor((songT + TRAVEL_TIME) / SEC_LEN) % 2;
      tx = turn === 0 ? 300 : 500;
      ty = 285;
      tz = 1.15;
    } else {
      tx = W / 2;
      ty = 300;
      tz = 1;
    }
  } else if (state.v === STATE.CHARSEL) {
    tx = W / 2;
    ty = 330;
    tz = 1.05;
  } else if (state.v === STATE.WIN) {
    tx = state.winner === 0 ? 250 : 550;
    ty = 320;
    tz = 1.18;
  }
  G.camX += (tx - G.camX) * .07;
  G.camY += (ty - G.camY) * .07;
  G.camZ += (tz - G.camZ) * .06;
  G.cam.setZoom(G.camZ);
  G.cam.centerOn(G.camX, G.camY);
}

function updateBattle(delta) {
  const songT = getSongTime();
  const turn = Math.floor(songT / SEC_LEN) % 2;
  G.lastTurn = turn;

  while (G.notesSpawned < G.notes.length && G.notes[G.notesSpawned].time - TRAVEL_TIME <= songT) {
    const n = G.notes[G.notesSpawned];
    players[n.turn].notes.push({ targetTime: n.time, dir: n.dir, hit: false, dead: false, gfx: null, y: 0 });
    G.notesSpawned++;
  }

  // 1P Mode CPU hit automation for Player 0
  if (G.mode === '1p') {
    for (const n of players[0].notes) {
      if (!n.dead && !n.hit && Math.abs(n.y - HIT_Y) < 14) {
        const acc = G.difficulty === 0 ? 0.85 : (G.difficulty === 1 ? 0.93 : 0.99);
        if (Math.random() < acc) tryHit(0, n.dir, songT);
      }
    }
  }

  for (let pi = 0; pi < 2; pi++) {
    const p = players[pi];
    const xs = pi === 0 ? [65, 145, 225, 305] : [490, 570, 650, 730];
    const alive = [];
    for (const n of p.notes) {
      if (n.dead) { if (n.gfx) { n.gfx.destroy(); n.gfx = null; } continue; }
      const y = HIT_Y - (n.targetTime - songT) * (HIT_Y / TRAVEL_TIME);
      n.y = y;
      if (y > HIT_Y + HIT_WIN + 20) {
        n.dead = true; n.hit = true;
        onMiss(pi, n.dir);
        if (n.gfx) { n.gfx.destroy(); n.gfx = null; }
        continue;
      }
      if (!n.gfx) {
        n.gfx = G.fxLayer.scene.add.graphics();
        G.hudLayer.add(n.gfx);
      }
      n.gfx.clear();
      drawArrow(n.gfx, xs[n.dir], y, ARROW_SCALE, DIR_ROT[n.dir], ARROW_LIGHT[n.dir], ARROW_DARK[n.dir]);
      alive.push(n);
    }
    p.notes = alive;
  }

  for (let pi = 0; pi < 2; pi++) {
    const p = players[pi];
    const xs = pi === 0 ? [65, 145, 225, 305] : [490, 570, 650, 730];
    for (let d = 0; d < 4; d++) {
      if (p.arrowBounce && p.arrowBounce[d] > 0) {
        p.arrowBounce[d] = Math.max(0, p.arrowBounce[d] - delta * BOUNCE_DECAY);
      }
      const b = p.arrowBounce ? p.arrowBounce[d] : 0;
      const curScale = ARROW_SCALE * (1 + BOUNCE_SCALE * b);
      const curY = HIT_Y - BOUNCE_Y * b;
      const keys = p.dirKeys ? p.dirKeys[d] : [p.keys[d]];
      const isHeld = keys.some(k => held[k]) || (G.mode === '1p' && pi === 1 && players[0].dirKeys[d].some(k => held[k]));
      const isPressed = keys.some(k => justPressed[k]) || (G.mode === '1p' && pi === 1 && players[0].dirKeys[d].some(k => justPressed[k]));
      const g = p.arrows[d];
      if (g) {
        g.clear();
        drawArrow(g, xs[d], curY, curScale, DIR_ROT[d],
          isHeld ? ARROW_LIGHT[d] : COL.arrowL,
          isHeld ? ARROW_DARK[d] : COL.arrowD);
      }
      if (isPressed) tryHit(pi, d, songT);
    }
  }

  if (G.bar >= BAR_MAX || G.bar <= -BAR_MAX) endBattle();
  else if (G.songLen && songT >= G.songLen) endBattle();
}

function showJudgment(scene, pi, dir, rating) {
  if (!scene || !G.hudLayer) return;
  const xs = pi === 0 ? [65, 145, 225, 305] : [490, 570, 650, 730];
  const x = xs[dir ?? 1], y = HIT_Y - 32;
  const col = rating === 'PERFECTO' ? '#ffd166' : (rating === 'BIEN' ? '#77dd55' : '#ff5577');
  const txt = scene.add.text(x, y, rating, { fontFamily: 'monospace', fontSize: '15px', color: col, fontStyle: 'bold' }).setOrigin(0.5);
  txt.setStroke('#000000', 4);
  txt.setDepth(150);
  G.hudLayer.add(txt);

  scene.tweens.add({
    targets: txt,
    y: y - 28,
    alpha: 0,
    scale: rating === 'PERFECTO' ? 1.25 : 1.05,
    duration: 380,
    ease: 'Power2',
    onComplete: () => txt.destroy()
  });

  if (rating === 'PERFECTO') {
    for (let i = 0; i < 6; i++) {
      const p = scene.add.rectangle(x, y, 4, 4, [0xffd166, 0xff5577, 0x77dd55, 0x29aefd][i % 4]);
      p.setDepth(150);
      G.hudLayer.add(p);
      const angle = (i / 6) * Math.PI * 2;
      const speed = 25 + Math.random() * 20;
      scene.tweens.add({
        targets: p,
        x: x + Math.cos(angle) * speed,
        y: y + Math.sin(angle) * speed,
        alpha: 0,
        scale: 0.2,
        duration: 300,
        ease: 'Quad.easeOut',
        onComplete: () => p.destroy()
      });
    }
  }
}

function tryHit(pi, dir, songT) {
  const p = players[pi];
  let best = null, bestDist = Infinity;
  for (const n of p.notes) {
    if (n.dead || n.hit || n.dir !== dir) continue;
    const dist = Math.abs(n.y - HIT_Y);
    if (dist < bestDist && dist < HIT_WIN) { bestDist = dist; best = n; }
  }
  if (best) {
    best.hit = true;
    best.dead = true;
    if (best.gfx) { best.gfx.destroy(); best.gfx = null; }
    if (p.arrowBounce) p.arrowBounce[dir] = 1.0;
    let dmg;
    if (bestDist < PERFECT_WIN) {
      dmg = DMG_PERFECT; p.perfect++; p.score += 100;
      showJudgment(G.titleLayer.scene, pi, dir, 'PERFECTO');
    } else {
      dmg = DMG_GOOD; p.good++; p.score += 50;
      showJudgment(G.titleLayer.scene, pi, dir, 'BIEN');
    }
    p.combo++;
    if (p.comboTxt) p.comboTxt.setText(p.combo > 1 ? p.combo + ' COMBO' : '');
    G.bar = clamp(G.bar + (pi === 0 ? dmg : -dmg), -BAR_MAX, BAR_MAX);
    triggerDancePose(pi, dir);
  } else {
    onMiss(pi, dir);
    triggerDancePose(pi, dir);
  }
}

function onMiss(pi, dir) {
  const p = players[pi];
  p.miss++;
  p.combo = 0;
  if (p.comboTxt) p.comboTxt.setText('');
  G.bar = clamp(G.bar + (pi === 0 ? -MISS_PEN : MISS_PEN), -BAR_MAX, BAR_MAX);
  showJudgment(G.titleLayer.scene, pi, dir ?? 1, 'FALLO');
  playHurt();
}

// Damage sound: gritty descending buzz, like a fighter taking a hit
function playHurt() {
  const ctx = G.titleLayer?.scene?.sound?.context;
  if (!ctx) return;
  const t0 = ctx.currentTime;
  const g = ctx.createGain(), f = ctx.createBiquadFilter();
  f.type = 'lowpass';
  f.frequency.setValueAtTime(1200, t0);
  f.frequency.exponentialRampToValueAtTime(200, t0 + .18);
  g.gain.setValueAtTime(.22, t0);
  g.gain.exponentialRampToValueAtTime(.001, t0 + .2);
  f.connect(g);
  g.connect(ctx.destination);
  const o1 = ctx.createOscillator(), o2 = ctx.createOscillator();
  o1.type = 'sawtooth';
  o2.type = 'square';
  o1.frequency.setValueAtTime(220, t0);
  o1.frequency.exponentialRampToValueAtTime(70, t0 + .18);
  o2.frequency.setValueAtTime(110, t0);
  o2.frequency.exponentialRampToValueAtTime(45, t0 + .18);
  o2.detune.value = 15;
  o1.connect(f); o2.connect(f);
  o1.start(t0); o1.stop(t0 + .2);
  o2.start(t0); o2.stop(t0 + .2);
}

/* === MIDI PLAYBACK (kept from prior) === */
async function unpack(data) {
  const binary = atob(data.replace(/-/g, '+').replace(/_/g, '/'));
  const bytes = Uint8Array.from(binary, c => c.charCodeAt(0));
  const stream = new Blob([bytes]).stream().pipeThrough(new DecompressionStream('deflate'));
  return new Response(stream).text();
}

function variable(data, state) {
  let value = 0, digit;
  do {
    digit = A.indexOf(data[state.pos++]);
    if (digit < 0) throw Error('invalid MIDI varint');
    if (digit !== Z) value = value * Z + digit;
  } while (digit !== Z);
  return value;
}

function fixed(data, state, width) {
  let value = 0;
  for (let i = 0; i < width; i++) {
    const digit = A.indexOf(data[state.pos++]);
    if (digit < 0) throw Error('invalid MIDI field');
    value = value * B + digit;
  }
  return value;
}

function decode(data) {
  const parts = data.split('|');
  if (parts.length !== 4 || parts[0] !== 'M5') throw Error('invalid MIDI header');
  const division = fixed(parts[1], { pos: 0 }, 2), dictionary = [];
  const ds = { pos: 0 }, count = A.indexOf(parts[2][ds.pos++]);
  for (let i = 0; i < count; i++) dictionary.push(variable(parts[2], ds));
  const body = parts[3], st = { pos: 0 }, events = [];
  let tick = 0;
  while (st.pos < body.length) {
    const kind = body[st.pos++];
    tick += variable(body, st);
    if (kind === 'T') events.push({ kind, tick, tempo: fixed(body, st, 3) * 10 });
    else if (kind === 'N' || kind === 'n') {
      const channel = A.indexOf(body[st.pos++]), pitch = fixed(body, st, 2), level = A.indexOf(body[st.pos++]);
      events.push({ kind: 'N', tick, channel, pitch, level, duration: kind === 'n' ? dictionary[A.indexOf(body[st.pos++])] : variable(body, st) });
    } else if (kind === 'G') {
      const channel = A.indexOf(body[st.pos++]), count = variable(body, st), flags = A.indexOf(body[st.pos++]);
      const pitches = [];
      for (let i = 0; i < count; i++) {
        if (!i) pitches.push(fixed(body, st, 2));
        else {
          const delta = A.indexOf(body[st.pos++]);
          pitches.push(delta === Z ? fixed(body, st, 2) - 128 : pitches[i - 1] + delta - 45);
        }
      }
      const levels = flags & 1 ? Array(count).fill(A.indexOf(body[st.pos++])) : pitches.map(() => A.indexOf(body[st.pos++]));
      const durations = flags & 2 ? Array(count).fill(flags & 4 ? dictionary[A.indexOf(body[st.pos++])] : variable(body, st)) : pitches.map(() => variable(body, st));
      for (let i = 0; i < count; i++) events.push({ kind: 'N', tick, channel, pitch: pitches[i], level: levels[i], duration: durations[i] });
    } else if (kind === 'E') return { division, events, endTick: tick };
    else throw Error('invalid MIDI event');
  }
  throw Error('missing MIDI end');
}

function secondsAt(tick, tempos, division) {
  let tempo = 500000, from = 0, seconds = 0;
  for (const t of tempos) {
    if (t.tick > tick) break;
    seconds += (t.tick - from) * tempo / division / 1e6;
    from = t.tick;
    tempo = t.tempo;
  }
  return seconds + (tick - from) * tempo / division / 1e6;
}

function noise(ctx) {
  const buffer = ctx.createBuffer(1, ctx.sampleRate, ctx.sampleRate), data = buffer.getChannelData(0);
  for (let i = 0; i < data.length; i++) data[i] = Math.random() * 2 - 1;
  return buffer;
}

function oscillator(ctx, type, frequency, output, time, stop, detune = 0) {
  const source = ctx.createOscillator();
  source.type = type;
  source.frequency.setValueAtTime(frequency, time);
  source.detune.setValueAtTime(detune, time);
  source.connect(output);
  source.start(time);
  source.stop(stop);
  return source;
}

function profile(program) {
  if (program === 12 || program === 115) return { type: 'mallet', cut: 5500, attack: .003, release: .16 };
  if (program >= 32 && program < 40) return { type: 'bass', cut: 900, attack: .008, release: .1 };
  if (program >= 56 && program < 72) return { type: 'brass', cut: 2100, attack: .035, release: .11 };
  if (program >= 16 && program < 32) return { type: 'pluck', cut: 2600, attack: .006, release: .13 };
  if (program >= 8 && program < 16) return { type: 'mallet', cut: 5000, attack: .003, release: .14 };
  if (program >= 24 && program < 32) return { type: 'pluck', cut: 1800, attack: .008, release: .15 };
  if (program >= 40 && program < 56) return { type: 'string', cut: 1800, attack: .045, release: .18 };
  if (program >= 80 && program < 96) return { type: 'pad', cut: 1400, attack: .08, release: .3 };
  return { type: 'piano', cut: 3200, attack: .004, release: .2 };
}

function drum(ctx, buffer, note, filter, time, length) {
  const finish = time + Math.min(.2, Math.max(.04, length));
  if (note < 42) {
    const source = oscillator(ctx, 'sine', 140, filter, time, finish);
    source.frequency.exponentialRampToValueAtTime(46, time + .11);
    return;
  }
  const source = ctx.createBufferSource(), drumFilter = ctx.createBiquadFilter();
  source.buffer = buffer;
  drumFilter.type = note < 46 ? 'bandpass' : 'highpass';
  drumFilter.frequency.value = note < 46 ? 1800 : 6500;
  drumFilter.Q.value = 1.2;
  source.connect(drumFilter);
  drumFilter.connect(filter);
  source.start(time);
  source.stop(finish);
}

function playNote(ctx, buffer, master, channel, note, time, length) {
  const style = profile(channel.program), finish = time + length + style.release + .03;
  const level = Math.min(.14, note.level / 15 * channel.volume / 127 * channel.expression / 127 * .16);
  const amp = ctx.createGain(), filter = ctx.createBiquadFilter(), panner = ctx.createStereoPanning ? null : null;
  amp.gain.setValueAtTime(.0001, time);
  amp.gain.linearRampToValueAtTime(Math.max(.0001, level), time + style.attack);
  amp.gain.setValueAtTime(Math.max(.0001, level * .7), time + Math.max(style.attack, length * .65));
  amp.gain.exponentialRampToValueAtTime(.0001, time + length + style.release);
  filter.type = 'lowpass';
  filter.frequency.setValueAtTime(style.cut, time);
  filter.Q.value = style.type === 'brass' ? 2 : .7;
  filter.connect(amp);
  if (panner) {
    panner.pan.setValueAtTime((channel.pan - 64) / 64, time);
    amp.connect(panner); panner.connect(master);
  } else amp.connect(master);
  if (note.channel === 9) return drum(ctx, buffer, note.pitch, filter, time, length);
  const frequency = 440 * Math.pow(2, (note.pitch - 69 + (channel.bend - 8192) / 4096) / 12);
  if (style.type === 'bass') {
    oscillator(ctx, 'sawtooth', frequency, filter, time, finish);
    oscillator(ctx, 'triangle', frequency / 2, filter, time, finish, -5);
  } else if (style.type === 'brass') {
    oscillator(ctx, 'sawtooth', frequency, filter, time, finish, -6);
    oscillator(ctx, 'square', frequency, filter, time, finish, 6);
  } else if (style.type === 'mallet') {
    oscillator(ctx, 'sine', frequency, filter, time, finish);
    oscillator(ctx, 'triangle', frequency * 2, filter, time, finish);
  } else if (style.type === 'pluck' || style.type === 'piano') {
    oscillator(ctx, 'triangle', frequency, filter, time, finish, -3);
    oscillator(ctx, 'sine', frequency * 2, filter, time, finish, 3);
  } else if (style.type === 'string' || style.type === 'pad') {
    oscillator(ctx, 'sawtooth', frequency, filter, time, finish, -8);
    oscillator(ctx, 'sawtooth', frequency, filter, time, finish, 8);
  } else oscillator(ctx, 'triangle', frequency, filter, time, finish);
}

function playMidi(ctx, data, onEnd = () => {}) {
  let song;
  try { song = decode(data); } catch (error) { console.error(error); onEnd(0); return; }
  if (!ctx) { onEnd(0); return; }
  const start = () => {
    const tempos = song.events.filter(event => event.kind === 'T');
    const notes = song.events.filter(event => event.kind === 'N').map(event => ({
      event,
      at: secondsAt(event.tick, tempos, song.division),
      length: Math.max(.025, secondsAt(event.tick + event.duration, tempos, song.division) - secondsAt(event.tick, tempos, song.division)),
    }));
    const master = ctx.createGain(), delay = ctx.createDelay(.4), feedback = ctx.createGain(), wet = ctx.createGain();
    master.gain.value = .8;
    delay.delayTime.value = .16;
    feedback.gain.value = .18;
    wet.gain.value = .1;
    master.connect(ctx.destination);
    master.connect(delay);
    delay.connect(feedback);
    feedback.connect(delay);
    delay.connect(wet);
    wet.connect(ctx.destination);
    const channels = Array.from({ length: 16 }, (_, number) => ({ program: PROGRAM[number] || 0, volume: 100, pan: 64, expression: 127, bend: 8192 }));
    const base = ctx.currentTime + .08, buffer = noise(ctx), lookAhead = 2, interval = 80;
    let cursor = 0;
    const end = Math.max(secondsAt(song.endTick, tempos, song.division), ...notes.map(note => note.at + note.length));
    const pump = () => {
      const limit = ctx.currentTime - base + lookAhead;
      while (cursor < notes.length && notes[cursor].at <= limit) {
        const note = notes[cursor++];
        playNote(ctx, buffer, master, channels[note.event.channel], note.event, base + note.at, note.length);
      }
      if (cursor === notes.length) clearInterval(timer);
    };
    let timer;
    pump();
    timer = setInterval(pump, interval);
    stopFn = () => { clearInterval(timer); try { master.disconnect(); } catch (e) {} };
    onEnd(end);
  };
  let stopFn = () => {};
  let started = false;
  const safeStart = () => {
    if (started) return;
    started = true;
    start();
  };
  if (ctx.state === 'suspended') {
    ctx.resume().then(safeStart).catch(() => {});
    const onStateChange = () => {
      if (ctx.state === 'running') {
        ctx.removeEventListener('statechange', onStateChange);
        safeStart();
      }
    };
    ctx.addEventListener('statechange', onStateChange);
  } else {
    safeStart();
  }
  return { stop: () => { if (typeof stopFn === 'function') stopFn(); } };
}
