(() => {
/* ========================================================================
   === GAMEPLAY & DIFFICULTY TUNING (TWEAK HERE) ===
   ======================================================================== */
const M = Math, Mmax = M.max, Mmin = M.min, Msin = M.sin, Mcos = M.cos, Mabs = M.abs, Mrnd = M.random, Mpow = M.pow, Mceil = M.ceil, Mround = M.round, MPI = M.PI;
const SKIP_TO_GAMEPLAY = 0; // Set to 1 to skip menus and go straight to game
const SKIP_TO_CHARSEL = 0; // Set to 1 to skip title and go straight to character selection
const W = 800; // Game screen width in pixels
const H = 600; // Game screen height in pixels

// Receptor arrow bounce animation on hit
const BOUNCE_SCALE = 0.25;  // Scale pulse on hit (+25% size boost; increase e.g. 0.4 - 0.6 for bigger pop)
const BOUNCE_Y = 8;          // Vertical displacement in pixels (hops upward by 8px on hit)
const BOUNCE_DECAY = 0.005;  // Decay rate per ms (lower = longer bounce, higher = snappier)

// Hit window & timing tolerances (in pixels)
const HIT_WIN = 50;          // Total hit window in pixels (~145ms window, DDR/FNF standard Good)
const PERFECT_WIN = 18;      // Perfect hit window in pixels (~52ms window for precision bonus)
const MISS_TOL = 50;         // Distance in pixels beyond hit line before a note is auto-missed

// Tug-of-war bar balance & damage/penalty values
const BAR_MAX = 100;         // Tug-of-war meter limit (+100 = Player 1 wins, -100 = Player 2 wins)
const DMG_PERFECT = 1.8;     // Bar shift amount awarded on a Perfect hit
const DMG_GOOD = 0.75;       // Bar shift amount awarded on a Good hit
const MISS_PEN = 4.0;        // Bar penalty deducted on Miss or empty ghost tap

// Note travel speed & layout
const HIT_Y = 518;           // Vertical screen position (Y coordinate in px) of receptor hit line
const TRAVEL_TIME = 1.5;     // Fall duration in seconds from top of screen to hit line
const ARROW_SCALE = 5.2;     // Base visual scale multiplier for arrow sprites
const LEAD_IN = 2;           // Lead-in delay in seconds before notes appear
const SEC_LEN = 8;           // Duration in seconds of each player's alternating turn
const PAD = 160;             // Background margin padding in pixels for camera pans
const LANE_X = [[65, 145, 225, 305], [490, 570, 650, 730]];
/* ======================================================================== */

/* === MIDI SONGS (generated by tools/midi_to_string/embed.py) === */
// Generated automatically - do not edit by hand.
// Re-run: python tools/midi_to_string/embed.py
// Each constant packs one .mid losslessly (M5 -> deflate-raw -> base64url).
// MIDI_SONG_BARRANQUILLA: 3556 chars base64, about 99s of music.
// MIDI_SONG_FRUKO_Y_SUS_TESOS: 1864 chars base64, about 60s of music.
// MIDI_SONG_LOBA: 4064 chars base64, about 71s of music.
// MIDI_SONG_NUESTRA_CANCION: 5088 chars base64, about 91s of music.
// var MIDI_SONG is the default song played by create(); swap it to any
// MIDI_SONG_* below to make the game play that track instead.

var MIDI_SONG_BARRANQUILLA = "7Vp7b9tGEv8sC5KiJXLrHK5Nrr1endaN5SfPlmUbiXFSJRBULJ0In1Q3_yT72W8fs-8VRaeN7woYECByHzM785uZnR3u2Tcf079__Et8QaI9Eo9I9C1JSPKJ9MjXJJmTHdrynqR7ZEVGpHtDPg4R6f7tx34HkSghXVTffo1RPx7D2-We-Ub7kn70Wrwtb_9q9N0Pf3D69NuCvvWAQ4Lm9C1NST-lvR3au7oe7uJe3VmTGP2I8zq6Mx_eyIdDnBf84QQnl6RIhvTxAHeOKKG7p1l6ly-drhRRKS5wVNNB7R8oN6slZvyTmETovI97DCm_oUc5Jazh-BTHFLEV6a9Fy2nRouX82Gm5euOOudmXLcWadNB93v1ECkRStOzRpxqRDJ1k3T6s42pvIFbGFgc6ubt9lSE6MEbnOFUiFPc4YQbIRjGQl4PXgywRsp_ijpw8Myez3gwVWVQzBZ_jHdFwknUsKkg183GndBwjcIQz1tFBqzyumQQ1_1fz9VpDbJjoYtoyj0Psiow1U9m6aPSDnFPnGZ-zyDPJYqEkOnIlusI73K4YjXpfaEMtjzWuWCObeoZjr3NhzOiC5EqwinKVU1Oxtnke8bVVueA-worUHEh1qLBi0BwGnepBSzXoHqRc8n-Lb6mkPROWbSs2JAtT7LwBxwOBo4Vb1YDbQsspyS8UeQZRBBBF3BqCOK5AwlrjqC2zcCW7gpUWGCs8FyE8gyCvaWMBen12tmdne3a2L-xstvInsDRwNOY-pyPYblUKJFdzIvG9h9llHoXIcYVKhayU9zG7EHY-EnYu8gvPCw2nPx31ldMLEjMg8U6QUKbLvXuAI9n4IO1Z-WaVp3zmW_5vmdJSY6wU0UXv-jI9AftV4iDVbPXbPqiwkz7DhouO2Jpmy3ARkOFQyiAtauo71ofPwXYhBX8cpvfNmM4Nz2yDaQUk3mpM70OYrqU-DqQ-FoDp2Mf0rj2mNDe-bML0vR9pXEzPApjWIUwrKcNJw4xn__zT-Gch_JPmHp_toQgts5aeKpgFUGZU7rOoiXyDB6eAesqHz7PU9ORe0JOtNcrM62ooGpST0g62d3F6KaX3y8X1t9e0hZ4ZO-jX_MVIJHz_gSeE3mcvRsRInUTqd_YTzehUTpdSUcaDq--us93fSCFYsVkv6AEWnVEtAVdmiBEagAADKgDvYJu-taeectztkTJZ1CPlQ8GGHmQ5lqxzYfoZZa2ygLfDwWX2wqISIgdLEV18cWd8TUIMN4NRyeDTy2XNQ6jCseJgEkKoxCrxDcxR5AIienPDovKRU0crCI1xCinWU2L6_6mJ7Pdr4qtRkyamlxfDrdbNVrJJAxNbA4bk002Sn8DyT6TklSd5iXFQcmfqBsllZHl3cT3MlAJ-xrt7thtIdHzRpTX4Do7Qv4w51Ftlg6LKhxagnBxCoDgvOCfdnw1_90-4lvT-eSKoAjvNMYiwPT-z0LcSK1sD4YNr5J2nwotRh5mlOrcAS5UNCuGzpkMNFvveDEdh_XmjRBLpTAsqls2LYVjsmtl2RTMu3vTtive5NgLhcvmjgHEWeeZah1PmeCI4UhiWtoEjbrb7nl8IgngUmW6KYFVWtWK2rzLK1BskA0Nkgq4KBYk53rJqRfRIBzydF0ev3WqDGUvVUmOXarWvthos4hAdZFdGCt48xUlGxKwElfvZzp6Ih0e4syJ1kvMh_FMEi4c50OQNNJPnDSmLZDyhFO-UNP9P0D9xLklX-zj6hdjTRxumn8H0Cz19oqcfbuMemB7iXoJdTbDIhul7wbWIdwmfT_Nvqc5yH-uthee0UzDeMRap9xSs8wR3oH4DWERo-honc5KmMlsG85-CB4vdcweVWQoDYsZCbjK8g5LqclgPtWvRgwJGsNPHAuOKY2yNFKdNLKLqlfAORhLrAw9OlO0as83og3u2wd0JPry3f8I3buZTsIo7rhLGxB6li36wnKGmZ-wA0HmjrTt1yc0oudRwflhfIcDhHiSHVnpoxEp8DAr6iy-IedoR2u8g-wELoB7wLgdK_LPV7tZj2r6G9jW0z6B9BaaxAtOoJOJr6FhDh4qED9DxAB2GBrfMDPGyZt6DlYl_kdPEbJUfwPxXYP4LRxPP9ve_sD8TwVRHd6ndWhomhHQIzCzyrQH1tXgvIGInl0QZRDLU0dy2eK138X1WvWi46INsVVYLHzPAtO7kNoRDxQ2Jg96GJoPhPkYmdiGaoA2V5uy0oSVRld4jTH0Bpq4QtRfs1rkMtMVOwBiNGSMNN_-6PcBRAd6Y7YlCx5w9GR4p8whpE3prqeS62U6t1i2Wl9r61JUwOcgqO40GGNlpyUimJTOLpDWrlPwPdf4RSb42ldIgy85bI8NzgTyu5SUBNmDiila5Cys1r4aCmJSrktJXQbNQNV6cuMfsyCh0mdRamAEoJzaDlOaEbMEGODIL11bdwAxoCByrCWIpnFPAxnbRU6auLrjan3X2i5EdRw3JnSI3NgujFinxIUoiP5UxSSNvRH0UovIcPbzoIfdywWgOjCrQadvI0WhOwUhhGJHaXLZHiEBkGG2KDJO2kaF0I0PVaA9GZOBbYfm4gDANBoRS6aBVQFCHMzMQTL9AIBjbsd5lOXFVN1UW-riA8PmB4DkAfJkAkD5lAGA1YUaCHvpDIQA-gLHeTWlCAcnGsSJQiGhwTIpjkcp-o4oN8338b-lLX9G01bIdlaOHUgcrV7crIK2ChU7JGoNEhWMvSLTMEkptWuaW7QWFKU43BoVmFDdkA0_h7O2d_HFOzT8AD7-zfVpnuiHf9aeYrotUzbCti3JDofTCHtrskXCHyHbJ7SCyYlwgpbNSP7gFtXUbntnTxDWsAGi-d83-OO-atfWu0BY847WUrV5WAKNPpD_2N8TZpj3Yqela7mYUZ0N7cLUhGe85yM2sTChUpNWg-ZUU0wVtSC9Mdb00DEacPGdw3mwEicmamPXvFHIHnkNYxsE7S6NmZCAqjUN9MZip9Z8bprnp6shWphEwVSB6tRl9lQSLO3VT_o_g_3Pj6dJ3xQ04nW9wQeeST8D1VloG__KJjLAdUFGK3m4_H1cKVXUts4Q0aBIK3gaKdYifH3BCdBvDqvnVAiObw03YOd16uHvztAFDd10Wpgsf0w6E8VRtvyPrUxJ2rw05--R5A3L-3igLpM_--uyvf3J_hZsiOy_J7_DYQq7spaiUTtiT7bWJWEgs-AivEeeDI9BiwjfB6JbAR7m8PmZX8mDJU_tArD89a0PemtDUSpv6siVQKWXYccmWOHjpUmI2B3WNwE1n2Lx8-QiP7EBWkKJ3QGrhGCxPHea-Rz4EPBIuY8KZ885PkZY6RbrbnCJ5lzOlIVXwmWwKn8nEu0BnvKFftJtoegdA28ELvRWEMPGDONz97EBiZ7LxcuhVKDAoVR5KSgHz0zdCcRKymRY5tX0T1DBBwD1sinMcvAnawhTnxue2NqYoPzCWmlTwsGvqx6tvNsd7Z_f-wCNRSun945O4TMqfTJ3zm6PXw-wWf38jP7RB5PmAvx-RDVVvfuLkl0gK_nCAX-2RN69ek_8C";
var MIDI_SONG_FRUKO_Y_SUS_TESOS = "7Vptb9pIEP4tI2wTsvaFfjhF6lUiUa9JX-9UgkhCFThbDrRwIBS-pvvbb3d21m_YZoGEu2tXirIo3p15ZuaZZ2yHT78-Nn97fOEMeeMrb3Z4s8lb33nrmvtD7l5xP-DOZ-6M-EmHP_AX3_nvQ_7YA-4O_lo0z_gxDNnRJXDf4S0YdtjxAngA5-xo4Y_ExZA5-mJ4xly8-IY56mTMPH0xPmNNvPiWeYtjEBej1Gx0RmYvtNlxenLcoZPv9MlJenKiT37QJ2cpoFmHAP2hAU1SsxMN6IM2O03NTnWcn7TZ2lB-ggyJiwz-ZL8sVmtrdeYA98BCkIvBZdWH6iwAbapNstzUFSFJhC5vwMf4mgmiK7pfNr5xJo98_Js1EHMoTK4yfxMbKmsk_sY8NHn3ngmD4kf2T4dfSvxoIt4QQ86EgiXOmyDDDRjQfT91rpxVMEM6w-P3wpSEuK9nkcqC5wraSc8u5uOOXO9aigrqJnm8_1JVivs9PVf0xTYkqOie5yFBRdcdgAQ1XH8aElT0-gFIYJXAKoFVgv-SEjgZJXC3V4JjieP26lrZaUq2Xl2fXjFXYTRBJVYXpkFLOG9CiKtAE7SS_FKSEOX8wkA1ZGwuzMhkRCZHwuQqTyQX5rQppk0h-k2i8vJR7ag2GGEZHNhIQIykLDkrAtnr69Q3YNzrvxKZ-CyfOMRjiPpdplkq9lngESKPEMnVF9LDzOITILAoi9dYlC2o7cKiDeh8jKuQ1zYkiRcxpYnv9U97e-mf8BWQr4B84VoKFwEMbrqq5SWAyU339MZAH4lP7SPFJ1wFn9rrOrF9syL95bHlxWumyqorWyecGhIQJCBIgGVeqTLn-2FGqYooVaMgKYvMCpbFw6y8vNlBd2XDERpyEFbXolyPBUYKKKKARhnqlCjRfnotuq8dqO7DVXRfO9CaOX-5DfFzelmnLPtqOxLZQ0fdnspHCz11e6dXXSvzVuYPLvOzA8j8A0nLgqRl_HwyvySZn5PMx_--zC8p03PKdFwn83oiztKJ-LQyvyQHc3IQby_zddR5Bpmfk8xPSeZDK_NW5q3M27t5ezdv7-atzFuZtzJv7-bt3by9m_8xZF7l8fo8RShNmPzXwIUV0WGaTv0kuQWpb1K5znNQxQfFioeCJcVcyuU7ze9lYVccgKnep_6zfCkJdR1L3b2MKkA_E1USkr7n-prqVlYjzXUfk3D_ViUhEXizgIxEPqHA5iCiwFjoPdUHr6rESeVjR_4Zq32TOmQD7wqgcikvlb39oNePgw29UkSj-JmMhELPFNNufutv3DJbt0YNpk0zoFCZeXBCvXpCN1cn2zdH7SAobQ7jYZA2QWZo7UT2zRPBqeU7TSPKnh0LdizYsWDHwv9pLPj5PvZpLPilY8GjXvVoLHhZS5C3xMiSd4jRoQnWpneXbSJY2_zNxeFGytFTjhRH2AnxiUqAlJOCwbfcaxaAIZPvSBq0OrTivsqXSLJnQvXsnL5AAhiRqRGZkqt2JZACfpAb1OpghsD0ES_rshANQMwctKxWh1YdZRINJiTqs_TpGCCioxEdjTDGLacDOosKg2ED5pAch-Q48wXN7JBYw68Kaoq_bjDgd0H1Y3MlV2RhPSqsR4X1ytAZjQGZlOhLljv4jfloE4qcN803IFhAsFBlahV9nbqYxBJTWsmTSHHjHW28o413zFTEN7BhQGUcUBkH5gwuOWpyb685m7w0qUF3Swy4JQbcpt-OzOpxNVeNb9_NOLnOPUNlraefFVMrpj-pmMZEp5joFO8uphGZishUVCWmNRTeT0xHVMYRlXFkzuCSo08tpkNiwJAYMLRiasX0hxRTn_D7hN_P4vfzYuqTmPpZ4r4Rhv4B";
var MIDI_SONG_LOBA = "7VsLT9vIFv4tlh9xbM84F3ER4iLEZSmwadbbBoQQ1UJRRKGhcZSlLK2o5rfveczYTmInTgK9eyWkldZ17Jkz53znOy_z279_NP7z41-PaqhulL2p7Ehdqjtlb6uesteV3VL3yt5VTqDsffXjxFKNr15iXyjbehO6Ryp1LuHyfRSnlgqte2kldGNXumeKLzvCOVD8a2jzrf8G7q5-87eoxb8FVtLYpRv2g3nc58ePQm9LL3YSORvmV73VL5G3o3_9XTh7KtFbOfrmm8iN9OV7Yf-R_e4r3vCNsL_rJSOBQlnWd9-Bp8wJ8acD6cEdUXHmFH-CfyegKHjbO1V4pbVwCA-5cPubsh46rVYMGsX_NhUtWKko_JHvsEhBg0Ri1ZFIcUgPZcqEh5pBao0rlUSDfx_CAyTGr8r-S1l_tuIYLI32zl4ORGJNGYBfxzt6B5seIpNoMVx6qNJI-CPd0drxn7R2yHBGO1qsuEVirSP-6M3MuvBmg4w7bWZ8ju6lvEPg8AZkeS1kk81Hd_RJ2MaTmCBT4j2tMdv6taPs7zEIhItem9f9gCFSRA_vQXf0Ho2lcDRxjkVghJIlrKYKPGkzNA1IZyMqaKyCqOBlEaX11HSWBJTR1DxAgRlrACqwlwMUSBw5sMDFLy0JjNTYNwuGjRoQK1IVrOThSqO3YQTngOXhTgPvXHWkuAMmX4rMeFkbl71XTxNrDpfnumzdbtBTzo1euGn12kKW8CBs41mj0DXesRgh8maONTgOQnMGG84gehDtVmTLgt6bQ9Cy0dBFNxQJxNFa2DfaGLYDgA3sletZROdmlWXo1ojXPwkQ3mCR4tJ36vFZCDlXQgTmHBaUEIknxW5VzdjFt4cK_WZBCoeHAB3SNyC66IpgRVov4P5m4kDnkCTVYn1zLoBddANIyxcR8hIyrmWiQhWUo6F6UquHjMwU3RAMeZOLfCIkeKkznBlU8rcjEA6ws1iUKbhS8IioGVfYcq4aTLsq6u6uYFR2sptFXJXAGt4V_B0ZcYhCLxvHCoi7Q90VFg6Hy_vpZJwDR3FP88XbUthHyh7MDoFFJPcyWeqHxPxs0X3RsKi0RwTu4s5aDJCF5XM_Q68A1AxLfFUXB9pHfUe51vVbaZflacka_DiKQUGpk1QEy7zq4dXgXMcitk-UfVXLDz3awumCXG24HArnFPfNXZLW_NgVESqhU-aChdJqys8SWA5WjTGOBpmn-RRtO9JdxKm0gDH8L9kouJUWMJZ4tvUSRyoUc2X-cYCrShewt2U8hVe1YVWJpz4pi3J5DVjTI_ZgnwESWbJTCF2-Bgtrt8wRCtXkNN7L68u5ONZrlid4UwgFAY8lSGcUMQ7SgBGUAEhPa4MUII_y2aNaINVbHBCcpqApI2SRd2XQ9Mi2pMTzGiA9nwApI2AdpVkMqV3eF-AlJ5Ha6wiJRthfvjLZ49V7jKQCYkkbomCp56pa0EdGLddHH5nk9Yx3Okznnf9dRbNC_aKpU8b2GVJnCc43SAeA2BQYaG4bZtN4BazgW1cST-LB1XXMV4ukSm22t8e8V1Ve4-o9gc4dwNVHiRgAIM6tWBIQUqP10Cuw6T7RvVy-vXMIUmVOBMCAXHlrsoKBK_K8jeW9QWunyxqAc7_TupBgR_K_F-gLEZnHIODhFp_xAs54pti2_18tI2YrZnBZUkaMlQ2EZsDw5zIP8RjpiLvz-aXEePHQyiie_EXYZ5m_PLAV6_tLwpiiRKakyJhfVEh2pe989VGgCKDwGt2rQ9g8p3lKSCh6DTF-QnBZtebYMA4aCizWwdk5GGA7J5gRkA7wRKGzw9J8pVCHZ7uVcer9c2qVAxIOkWuRBzfTgISUlJKuXMXc42ICwEuJwVeJENG0eYKaXIwDdmCNv6QDOb-2yvVJjK7NCHqp8ieV1mT4IhKFOsEpc0qwNMatJ5V6CwwPaEmASW_lMYJO3rwDyg9r9M_alCfLdGN25OGkbYB0PxP557x9oDTOVx82pATTgWzmBcOs4JKCMPh4i6L3IgBrs-gS4_5zxpQtCl6t9KBObOHwMGhhPSmfezBBsC1rRaFvjWSU7s0dVPhMGWdcvi0WJEC5VlmQWHp4wTYboF8zfqvHGFqv0lnTel1loLFH6grTnboJE6h9xOnk_BEHprJ_UoIVvMiwg3sQ0luDTbdrFAlsuwH1TNbqlAtMAgPMJCDDfc7CwTDvEQesq6ix0KBjG7OL8EnnjMjAklIXLLRQm88zyKUQdxGa5Qexd0kNpRqVAVJsPwLn4tSlmo3BELBHJDD_WW3cS0r50PRTjBv9UKTwMi4dMn9PgBtxEC88oNjk7H0LEa0rgIB0RP3_zReZEXMqGeZG9iC_46RyDmGjx5qUWJKrgOTaID95lqzx7u4vNj-IKEdtaUp8melyQFjwDsiAtagaSbOPWmXafMmJM5U3t4GTQlWN0GvqSmuVjxrWMxKUy7Z1iBZlY10T0M8dS6dI-_04PAQxSsfTgWriGfofPsRSPpL4NFgOpu-C9Zu2IyQuH9CFJrg5jE5M0Jc2Hgx9MmS3Kp9tS5q-mfT9uhuFbXVemnJz-w9Om8pq6ifr-Tn35xvx2DXfKIy6UAwu5jUpkYz0Ut3fDqiGZlfBSqTfTIpHgaOVVcJaL2a6iY8KKNixHzo9DOcD-NawEwmnJLNfMxLt8aBhsreU7QEV4435ZqAYY7QwwmjqC2gGy-RD-EG_KaNLLlgrC4K1zDbOmpZjp05YWuf3UqjjKyrdL6Cby0K5jLpqmyp-vILYoMUibRxhUUNwdrgirARjk3Ubt-xiV2ZBz0-5L-6m3CoRLterk2N16tAAOBAb5XTAXU6pGxuOgTXX1ZogcvVIcaocS-VMgYajcwyOowQBSFruiyijtOIUL1PqJYCjNNrxcuhCsTxFX82BIcx0LsT9UDvENNf5M7cdKfAZjew5TbMnJg4ouQEQjOuNqhn86G0kc48mlV7ipwZlMVTDM01mx1JhYinv0aTvF_L1ZTcblDIbWCxjHeLQmHBmNM9uOyEguztvHq-FwXbPtiYkWJYS2wJhIDIK_DPOGVskd5MLQjz2dAutgZxzdRwKa5owOEa6UGAZd6EPCwp8IXRvqjK-e8ZVDWtt1Yn3m_QwJK9H5WzRBJYUBVZF3nosYwqm8TAxwHC4T1XJFS2udBxdGuVNMdjvcjyqiN74ZF-DJKpHITquhCUTIbhqWNdht4I0fM4hWZHU4DJAuUGB7qiCdsDFu-MUgvaTQ_wieDrnKLh-M0woWm5zevfONH7sEjKBeMEf_cxik8GxjMdgg2DT_lyauBTD0RAbkZpSZicjCeWGLDHXwVOVJnWRXxOS14TkNSF5zoSkkk5-bmIyi0pek5PX5OQ1OfnnJSf-pSln8IoaKmM5x6Fz8yxdjPKPVhyeOjbc6FRtnHOO8F1i6wi70QOZtZWKbgzvSUprOiL09pRH3bSWdQUYARlaoJsnohlycaPu-_d7Ej-XBPxw_sVZA77YF1jTTXz68i329liKL3QVLJApsIDAvZ0QhPPaE5_uG3nCGJJBHKCeqEJ-QBKFsuSPl-DKsT4F0VbZ2F7r5NNxGOGePUVH-xSipSXNeT2Pz9PHK_1hzViqYOQKyKBXiqmZZz2k2D7-bQS6d-UHM5kUQQibeOecHHyV7gPvfYtXpnU__ncAmVaQNPALsAdVcHnSShCVj-kdl1jzbdPzgrbalfifbvR6ifniA66mCcBY6vZEgNdJj7V2hRONvHeZCbf_R0iq2UerlU5K8e1baTOEgE8-8-49ulpw-ASiYcd1q6pB70DGuSnHVYcMhrp7V-zb40J94XW1eJAbSdZNN9NNlxKEOp38hL87uDf2hCvDhWMpRcGc-J0HoOlzMZ_QQOlDbIKzNkbU6CeeGb3txLF0B8odKfchI5rp21V_EVTyNPOD8FPmh8gqyUIKVo6kvCdE76tCTkJqbDo7SpOGu67rEiCsJCOssm-QqimMzg8UluTDh9mElc2N2SNEyG30bzF_8oBs5Z5lnxt15rNVR8viAFtFAfwzn1aknJn4vIavKctPmat8zVT-mzv1Nw==";
var MIDI_SONG_NUESTRA_CANCION = "lVptbxs5Dv4tAzuJZ0TJLbCHpi979XW3djyeTOyxk2YDdH2bxHUumzoXZK_AAYv57ac3UpTGXeC-JZZEUQ8pkg81p3_7s_f-z5ej9mW7bntZe9YeZe1B1vazVrYD_dO6Hbcwavvr9mDU_rnK2sFjf3LVin47yGYlyGyX6XWlVLt1K7JKZZORGcyz8Upmk3X4ezeKx2eljOa69cNs18OJ63QQFw_Mb0ATjKRUut2ddgISkEgPZxhkpdhzBjBjh9lXYXY4zB5FL1LBDj76QTMpi_VE6WHSv0U2ydKDJXO-FsNdL9un53qfeLsEDmPF_DFRbjoYKRIAGtKC2p2od9baET0DRZQLsGrl5p-nUkLPwleJnnWFCnpG7oFR7-aVkNYOudnmYSVxasamgMPRrDRaDLwEviSSun5XSiFIqtYg3jAP0nCzdaoAdKW-WimAvVLthkEa07XHdTVLUPp3pBoFSNfyTgjZkcp1ZQoovGl0rDA1QqC8AylpilsiHa4nIug687ieOF0P9fByom0BzF5mEg6OP1-9E4DYnnglTgK2XKIbY5I_rG6EBEWSvy5pcoaT1j9_WIEA0ZHMJnckr199nki9ar_Odz9PAGDQ0dla7gRSNGLJWh1t9f2StZ99LsgnTgTtwHWu3W9_b_kqDQOuggi7CCtAa5_IzuRvlYej9HCUIij97tMHfTeC0mYyx0pDVWC085E7SH5uPAwl0A6k-6er2Dm8GlZQhBlAkGyBLgPQYRE34eqTXrRf5_Hq0xUUCPT3dTYZqCN5efWuBH79wuTgdrPy81UBIQdEOHPLAVmuhI4asc43PwMFtTIsMqHcYfnhToJUGcKi9erX7hC71s8-2B3olJvd25RwkD1Yrz2wKcKCKl2uGVvxZt6AUlzmx83_Y0zQ0KfxEV-fzpMU56upArf5vQhCUZmMLfqoDmy-qf34Y-7G59ARbpV9FH3vGZQways319nZStqvNv_d71R0j-N_d8lNm-Nc4pl9Whwrp8aTVsOqL736fnzOjhHm93yaNsfv-9ifqF_0UX1asV99yh6otgoJe8R_xx3zeP1Eu8d7r3HP7pxoLhLNFQceCw6nBxo01Zv_XsmuXj0__p72i8dHtE8wUzqO53sqnCUmaAmPx1xwM4fznyWWOENLkIPm8fzE-3G-8379v4jd5zmSx-X4__2te_YeVH7Hg54hXj_3eD9Z_dz_3oPcRVE4L9gpWu_xeBb7fhdk5-fcnXMuErwFLyIM7l28-T470bdyFhDj86Sjjf1dJPp7fRbfubYL7_eLoBeLNoVTaueVX0DsJDsPdrUHbOdk_USJrPaHXLe25L33xfKDDObNvDquiIb9bpOYofYl9AM4TWtfv3-FPcdClvCAwbQIQszv98mmaBsdTdgxQ7SZ-_HHvK8TSt8UfdvZha8Pu7H2Pn_hSvriCGOujox22f3JUqchCpTrH4chGeCcm8tS57I-BmNkI3qu4lchkrttTpTy0PHh0f61ARIK0EW43kmARiHzKQxDbPEZMVYghNbgHTjN0p7qWoUlHkJnoT5GwzB8qQgGHxx1eiArX8thiLxZnKgI7mpmYYkCmooz62NgRutX50Ng2XpkgYjzwpPwPlJwYFKZdtCqsLmYSRVlswDQA5A_PcwqJSHCiZZE4XVIh7s7H0sESGcP9BMNTDf14Rq9jZTQ35MJbYRDIKrpnRIyXIKRTRQ-0BVxgKtZgLQJJSf3th6DJ9w0Sw8E00xSUGdASBlYFLspCgNhlrrKblqBORXPo0-CWgoWTH6fx7StF5Fld5V2RrVu1-0_W3ecogviyKEzvvtRKEUiGEpB9DdI0isj8-fKQ_aHIDe5W44VAE-1GBMOzRH-KMWRR7mPSx5MKwIoSyJSzv5pTLmaaibRpxDrMhZgO2f9YzdLEzLlpZLyuv3Sbtso2J_x-KJkjAcJiuIL1p8G3n7kPU9F5yAap6RSnocDPdibTbIQp__MxBE53LKx7CljZ-SZ9gljDmX0PkrfXFTaV_sIj7-NWFxESR5h0gppv_1VO9AtOlA_Kjh4hrImyvyxIx2KpGrAqJPHmWku2CUTXtiuoFRPN2O8KkAlEax44eDqZ7umODwatYTY5UwI1UVsUSS1BkNqtYQh9DuOtCgShLQus1JIcZBIwqon8V9e6oyT3LUreCltfSjcLYodgterg2wRAue99mgQngrqf5c-I_vIN5ASy4S4qrkvDi1W8Spz7PmvMpUeS_AtloUNh5hrpBLERx-xIfmgQt1rlixfcGMKCF65_ke0RE8dkriHJrqkpBiiU7OW6J0v0XaSIHmqFNZrXvPzIcnRdoShZ_VdOW6ql7Nr9oKUG7fxyu-wVzDInmciqiCseOrSGi0ughbG8ZTgCQ5js5SCiYSw1InC_bLsD33J37ejFtMaypj_-tYHDvJb5SvHJxG3GC6Hknrm5x7yn6CT1G60sjI0QH57W811tvGt4hu2zjIKZAq24j_MtrIgjHGPibfZ1rm-EXr95rS2QinmG4TYfLtXiNnXbxQQSQ_MXfmZW5mFlFxKFbQv6-1bqYbeNDeCF5KGJ7NCdgZYI1cewI0UlJanMqkswmGm8-0bJYcQHUaG-aivO4RFC8ITwjlLRh5ZsgTp5H7GMy1ujyUo6lLEHJxt6FobqC0CNF4BsLVZWGMP05xudQodcuhDMkCJLDcGyfrYUiZqyqHf6lvBC33URGK8r6hz4auNPJSXUxVO5iGvTus7KZn_BFkMSbnvEMwxy1AmY--t_HLcaJ1lXPirmH9g-LvJsW1Czo_UjRLE1CUIPZin2g8zNhspgMTbexMSRbWRKtVeC1SBNHMHWJD3MqPevtYeykosXW4MFVni5qICFYWxcMhbIZj1IW4koAP5itEiuH1T6a0U38tUoNFhGMMN3aEZy6tTJcMOa-rYOZOsJkqGw1W3r2u7oRU6E7xV5krrNCDVLFxMGonmrYPM6-O6Ub60R4bkHYmZwgaFjCB3m3lH-u14vlCKReaHsvK2DfMfQ01926wE1tR1aC91wsSTr9RqSUsNHsB0f6MDtsBgOsPuR06y9Bm6R6jorL4-zTQJyg8O_9se9Vs8VHV7PIchiq5C6Xa3PJES4qbegxh0btxZ6HJfv2pOlQTJS2kiVYpfXfCOvYTYlKZ8XDI_OK23EMWEk0YivayiDl3aAPbp4EwwL37VSCramfNpoQp9rQqxzFIy1jrYQDfcfKRG1IGD2JQ5g4I4gC6ZlLs3AWwl2WKO7s77wVSySyNkgNdkWMn8716TNpkUpVNW5m8g8NzEO_SCATVoWWWlhnG0VxKT0m5AG6DWLIiIcO_tJEXXcWeyt2TZu9noCknhMwJdAV7eScEyLNiNHLYrWbg3nwt8r1JpLDD34sgtyPQCEC9diWXWkC_Yq0w8v1RRx2aIG-qyGF_c3H54aj_mXuGcnSAEIrfAv8Be2Fci1D68210fLyrle3FJBwtjr130WBb-lX3ha74Lloo2UMROOUq3BF8pO6ZDqy0Ir-tmKJWMwzqSfrNYyPiqOfpnDxd5KEt6uBJfAkUMLcQxDSBsp7HGWtl-2UAqSfk9bwDZw1L_eab8c6A7ftSK1XoU9CT4uOT4COB7iiPnol9OtXOAc4tDWzL8UmlWhUWGYDoISW-dWgdSgXmL3xV6ITx5uzvRF00xyAcchyLxJa2bp31aecWPScj1WMzUlYgMumsIGwAmEy-H2ehl-0PLIAReLQfeeBE-NbGQku5N81FKwSlUbAWvnhS9uPsOWbihhXjRvmRKuEvC5UcJ4V8gpUrUMmFNkFZfq2omQmL2pcgKAr1spMpSY2hteoYwTtszFy4ulfVCK_GjrqZ8HkKvL7hYB_QvVaWVVUnhzVp1hIgmE4eozTedGw9rs-OV-tyGmCp8CvuYd-gRkjuqb5Xi1_hy5gsgRu5EnGueioTc8RjG2B3nH1hFRTEjdAEjdldtsH9byqRyDuzOmbSaf5FEFFnz3DT-8FOqG8G5qdZIJXQO1Y86waGFTv6zOa4hKuE0yZBYVwLndTIlIp0MGtM7Z_Ht64WkLsdPwGUomdI7SPSFuIAhoc2GWBcagwzNOGOc90cUfRNSmjPot68B0KW-FR2264NdlAMmMqFzAfrA9Z5FZEZW2k_nC80WYEglEJVb5aV0EVeYDk11uv1LendA6My_vJW-P_B_0Lth6v76bkH81ufoHclML7ZAZ8YWRC07JogoHTcFvePprM8JNnJVFn4t7XME4S95nOAP76GjzXicxV4yHud3RzaRVsCGUqpQYOnkS93gmD9aVoJluBtE00RdFM2I6KbPEo5b0wM1vwX-25c6Il3AukEm3QHdAkbrQgSKoIeEg-bcPIF7cZO81QFaRFqGzw6eRecWsHIpdDfsHQaVHCMldIITQJtXsS28ObYNvFEaqivBOV5uctimETHFcw0z1X2N0wzHfuHEu34PRd7d5awIMcPgrZTqcDzPFxnHEx2CYMmdI3nxQhA8QNxCaPx4ToSfa1Si885uQtqBm1QEsreo6IMrTkH5WxpdVHpMaJYUDR_3-fgZUIf7rgT3IvZQDNBov09WnLV73CH-kIRvTuVpE6K90Ry45r9XJVHGhmsugeUkL-iCtRpXVDoHygNF-FzEzk8SayNY0E3gbYDe1iIWAyI01jUEIaTffKqAFe8aa-G_z8gnLT6xsJIKP5UpjkKXPeoLGUYK9Jy9EAmipDN-ABt5-30aOLavbPILPRRgDoufNE4DoFqAYLHaknnikFM0r-j4mBMWuDalEJlz5zM3HjfFk4WUfP2pLHJnnCOL5Q_LufmG0j3hmBmPk4Y8vJScKyYNQe3ccECNy7qe5YULNVbMVm9UiKQayw17A2K2xleNFuPf39SmnhLRlyC-Y-ykNSuZfhd5ITmLxPzquTCu8idzh52u6i3gl8L4FWZ3oeHk_i0mWiY7-yOM49X8dKtnAER9VBmpQl8oX8jv7d-R71UoZ-eb1-Y2Q3w21ulrToDJp4WL6eqLMW84mzZM9BWqnXd9PJ9PTR8hmie75jtZSm4-h9akiWYiJJtjIaQSXRfy0KwJ7KDwrN6-mYINd2y6d0izq_QbyY_j9n8=";
var MIDI_SONG = MIDI_SONG_FRUKO_Y_SUS_TESOS;
/* === /MIDI SONGS === */

const SONGS = [
  { name: 'LOBA (SHAKIRA)', data: MIDI_SONG_LOBA, genre: 'POP LATINO', bpm: '128 BPM' },
  { name: 'EN BARRANQUILLA ME QUEDO', data: MIDI_SONG_BARRANQUILLA, genre: 'SALSA', bpm: '120 BPM' },
  { name: 'EL PRESO (FRUKO)', data: MIDI_SONG_FRUKO_Y_SUS_TESOS, genre: 'SALSA BRAVA', bpm: '105 BPM' },
  { name: 'NUESTRA CANCION', data: MIDI_SONG_NUESTRA_CANCION, genre: 'CUMBIA', bpm: '115 BPM' },
]

// Base91 decoding table & constants for compact lossless MIDI storage
const A = "!#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[]^_`abcdefghijklmnopqrstuvwxyz{}~";
const B = A.length; // Radix size (91)
const Z = B - 1; // End-of-varint marker index (90)
const PROGRAM = [65, 59, 33, 0, 56, 56, 115, 12, 36, 0, 37]; // General MIDI program patch presets per channel

// === CABINET_KEYS (DO NOT modify - matches physical cabinet) ===
const CABINET_KEYS = {
  P1_U: ['w'], P1_D: ['s'], P1_L: ['a'], P1_R: ['d'],
  P1_1: ['u'], P1_2: ['i'], P1_3: ['o'],
  P1_4: ['j'], P1_5: ['k'], P1_6: ['l'],
  P2_U: ['ArrowUp'], P2_D: ['ArrowDown'], P2_L: ['ArrowLeft'], P2_R: ['ArrowRight'],
  P2_1: ['r'], P2_2: ['t'], P2_3: ['y'],
  P2_4: ['f'], P2_5: ['g'], P2_6: ['h'],
  START1: ['Enter'], START2: ['2'],
};

function phaserKey(k) {
  const map = { ArrowUp: 'UP', ArrowDown: 'DOWN', ArrowLeft: 'LEFT', ArrowRight: 'RIGHT', Enter: 'ENTER' };
  return map[k] || (k >= '0' && k <= '9' ? ['ZERO','ONE','TWO','THREE','FOUR','FIVE','SIX','SEVEN','EIGHT','NINE'][+k] : k.toUpperCase());
}

let arcadeKeys = {};
const held = {};
const justPressed = {};
const justReleased = {};

function clearInputs() {
  for (const k in held) held[k] = 0;
  for (const k in justPressed) justPressed[k] = 0;
  for (const k in justReleased) justReleased[k] = 0;
}

const t = (s, c, b) => ({ fontFamily: 'monospace', fontSize: s + 'px', color: c, fontStyle: b ? 'bold' : 'normal' });
const cTxt = (s, x, y, str, sz, c, b) => s.add.text(x, y, str, t(sz, c, b)).setOrigin(.5);

/* === COLORS === */
const C = {
  arrowL: 0xd3cde7, arrowD: 0x6a6486,
  pL: 0x872549, pLD: 0xfc76a7,
  pD: 0x15284c, pDD: 0x29aefd,
  pU: 0x00894a, pUD: 0x00dc36,
  pR: 0xb4542e, pRD: 0xfca300,
  p1H: 0xff5577, p2H: 0x77dd55,
  miss: 0xff3333,
};


/* === SPRITE ENGINE (CSEF) === */
const P_PAL = [
  0x000, 0x24222a, 0x4e4b5b, 0, 0xaba4c1, 0xd3cde7, 0xfefdfe, 0,
  0xf7bb1b, 0x9f5611, 0, 0x390800, 0x5e2e00, 0x915f01, 0, 0,
  0, 0, 0, 0x5b4d00, 0x362400, 0, 0, 0x206100,
  0x7ec43f, 0, 0, 0, 0xff6600, 0, 0, 0x004d3d,
  0, 0, 0, 0, 0, 0, 0, 0,
  0x08b8ea, 0, 0, 0x333d8d, 0, 0, 0, 0,
  0, 0x002e83, 0, 0, 0, 0, 0, 0,
  0, 0xf6629d, 0, 0, 0, 0, 0, 0,
  0, 0xd11717, 0xa41c1c, 0xab8169, 0x7c6822, 0xc1b087, 0, 0xdeac92,
  0, 0xf7bb1b, 0xBF921F
];

const CHARS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!@#$%&*()_+-=[]{};:,/<?`"';
const CLR = {};
for (let i = 0; i < CHARS.length; i++) if (i < P_PAL.length) CLR[CHARS[i]] = P_PAL[i];
CLR['.'] = null; CLR[' '] = null;

function parseCSEF(s, w) {
  const r = [], p = [];
  for (let i = 0; i < s.length;) {
    if (!p.length) {
      if (s[i] == '~') { r.push(Array(w).fill('.')); i++; continue; }
      if (s[i] == '^') { if (r.length) r.push([...r.at(-1)]); i++; continue; }
    }
    if (s[i] == '>' && p.length >= w / 2 && w % 2 == 0) {
      const h = p.slice(0, w / 2);
      r.push([...h, ...h.toReversed()]);
      p.length = 0; i++; continue;
    }
    const n = +s[i], c = s[i + 1];
    if (!n || n > 9) { i++; continue; }
    p.push(...Array(n).fill(c));
    while (p.length >= w) r.push(p.splice(0, w));
    i += 2;
  }
  if (p.length) r.push(p);
  return r;
}

function sp(sData, w = 24) { return sData ? (Array.isArray(sData) ? sData : parseCSEF(sData, w)) : []; }

function dsp(gfx, sData, x, y, shadow = false, flipX = false, maxRows = null, scale = 1) {
  if (!sData) return;
  const h = maxRows ? Mmin(sData.length, maxRows) : sData.length;
  const w = sData[0]?.length || 0;
  const cx = w >> 1, cy = (sData.length) >> 1;
  const draw = (ox, oy, isShadow) => {
    for (let r = 0; r < h; r++) {
      for (let c = 0; c < w; c++) {
        if (CLR[sData[r][c]] != null) {
          const px = flipX ? w - 1 - c : c;
          if (isShadow) {
            gfx.fillStyle(0x000, .4);
            gfx.fillRect(x + (px - cx) * scale + 0.3, y + (r - cy) * scale + 0.3, scale, scale);
          } else {
            gfx.fillStyle(CLR[sData[r][c]], 1);
            gfx.fillRect(x + (px - cx) * scale + ox, y + (r - cy) * scale + oy, scale, scale);
          }
        }
      }
    }
  };
  if (shadow) draw(0, 0, true);
  draw(0, 0, false);
}

/* === ARROW SPRITE (12x12, chars C=light, F=dark) === */
const ARROW_DATA = parseCSEF('4.2C>3.1C2F>2.1C3F>1.1C4F>1C5F>^1C2F1C2F>1.3C2F>3.1C2F>^^3.3C>', 12);

/* drawArrow: render the arrow vector at gfx origin with given scale/rotation/colors. */
function drawArrow(gfx, x, y, scale, rot, light, dark) {
  const oldC = CLR.C, oldF = CLR.F;
  CLR.C = light; CLR.F = dark;
  gfx.save();
  gfx.translateCanvas(x, y);
  gfx.rotateCanvas(rot);
  gfx.scaleCanvas(scale, scale);
  dsp(gfx, ARROW_DATA, 0, 0);
  gfx.restore();
  CLR.C = oldC; CLR.F = oldF;
}

/* === DANCERS === */
const DANCERS = [
  ['Cumbiambera', [
    sp('9.1.1<9.4.9.1<1N1<3U9.8.2r1<5U8.8.1r1<1r2U3,8.8.1[1r2U2,1A1,8.7.1[1<1[2{2,1A1,8.8.1[2U1<4,8.9.1.1U1{3,9.9.2.1{1,1[9.1.9.1.3[2G9.9.1,5G1,8.8.2,5G2,7.7.2,1.2E4G2,6.6.2,9G3,4.5.4<4G2<3r2,4.4.1G3r6<2r2[1G5.4.2G2[6r2[3G5.4.1E2G7[3G2<1G4.5.1E9G3<1r1[1G3.6.4E1{3G2<2r2[1G3.9.3{1.2G2r2[2G3.8.3,3.5G5.7.2,5.1,1{8.7.3,2.>', 24),
    sp('8.1I9.6.7.1I1N1I9.5.6.2r1I4U9.2.6.1r1<1r5U9.1.6.1[1r2U4,9.1.5.1[1<1[1U1,1A1,1A1,9.1.6.1[2U1,1A1,1A1,9.1.8.1<5,1<9.9.1.3,6.2,3.2.2,5.1[3{1[3.3,1G3.2.1G4,3G3[3G3,1<1G3.2.1G1<1.3,7G3,1.1<1G3.1.1G1[1r1<3.2E3G2E3.1G1<1r1G2.1.1G1[1r1<2G2.5E3.1G2<1r1G2.1.1G1[2r1<9G3G1<2r1G2.1.1G2[2r1<9G2<2r1[1G2.1.2G1[2r2<7G2<2r1[2G2.2.2G1[2r3<3G3<2r1[2G3.3.1G2[3r5<3r2[1G4.3.2G3[7r3[1G5.4.3G9[2G6.6.9G1G8.9.2,1.2,9.1.8.3,1.3,9.', 24),
    sp('8.1I9.6.7.1I1N1I3U9.2.6.2r1I5U9.1.6.1r1<1r2U3,9.1.6.1[1r2U2,1A1,9.1.5.1[1<1[2{2,1A1,9.1.6.1[2U1<4,4.2,4.8.1U1{3,4.3,1G3.9.1{1,1[4.2,1<1r1[1G2.6.2G3[2G2.2,1.1<1r1[1G2.5.8G3,2.1<1r1[1G2.5.3,5G2,3.1<1r1[1G2.4.2,2.4E2G3.2<1r1[1G2.4.2,3.1E5G1.2<1r1[2G2.3.1<3,8G2<1r1[1G4.2.1G2r3<6G2<1r2[1G4.2.1G2[2r2<4G2<1r2[1G5.2.2G2[2r6<2r1[1G6.3.2G2[7r2[1G7.4.3G8[2G7.5.9G1G9.7.2,3.2,9.1.7.2,3.1,1{9.1.7.3,2.3,9.', 24),
    sp('~~8.1I9.6.7.1I1N1I9.5.6.2r1I4U9.2.6.1r1<1r5U9.1.6.1[1r2U4,9.1.5.1[1<1[1U1,1A1,1A1,9.1.6.1[2U1,1A1,1A1,9.1.8.1<5,1<9.9.1[3,1[9.1.7.2G5[2G4,4.6.9G1G6,2.6.1{2,4G1E5.1<3,1.7.3,3E5G1<2r1G2.5.1r1<1G3,5G2<2r1[1G2.4.2r2<1G3,3G2<2r1[2G2.3.1G1[2r3<2{1G3<2r1[2G3.3.1G2[3r5<3r2[1G4.3.2G3[7r3[1G5.4.3G9[2G6.5.1,9G1G8.4.4,4.2,9.1.3.3,6.3,9.', 24),
  ]],
  ['Rolo con ruana', [
    sp('9.1.2A>9.1A2U>^7.5A>7.5U>9.2U1{1A1{1A9.9.1U5{9.9.1.2{2G1{9.9.2.1{>9.1}1f3N1f2}7.8.2}2f1N2f2}1T6.7.2T2}1f1N1f2}2T6.7.2T2}1f1N1f1}1T1M1;6.6.2;2T1}2f3M2;6.6.3;1T2}1f2{2;7.5.2{1;1.2T1}1f2{1;8.4.1[2{2.2T1}1f2}1T8.3.1[1x1<3.2T1}1f2}1T8.3.1[1x1<3.2T1}2B1}1T8.4.1x4.2T1B2C1B1T8.9.1.1B1C1B2C9.9.1.3C1B2C8.9.1.3C1.2C8.9.1.2L3.3L6.', 24),
    sp('~9.1.2A>9.1A2U>3.2<4.1A4U1A9.2.2x2<1.9A1A7.1.3[2{1.9U1U7.4.1{1;3.2U1{1A1{1A9.5.2;2.1U5{9.5.2;3.2{2G1{9.6.3;1}1f2{1N1f2}7.7.1;1}2f2N2f2}1T1.2;2{1.7.2T1f2N2f2}1T4;2{1.7.1}1T4f2}2T2;5.6.2}1T3f3}1T8.5.2}1T3f3}2C8.4.3}1T1f2T1}1T4C4.1L2.5.1}2T1f1T9C1.2L2.6.1T2f1T5C1B1.3C2L2.7.1f2T3C2B1C2.2C2L2.9.2T2.3C8.9.5.2C8.^9.5.2L8.9.5.4L6.', 24),
    sp('9.1.5A9.9.1A5U1A8.2.2[5.1A5U1A8.1.3x1[3.9A1A6.1.1x1<2{3.9U1U3.2{1.2.1<2{1;3.1U1{1A1{1A1{1U4.2{2.4.2;3.1U5{1U4.2;2.5.2;1}2.1{2G2{4.2;3.5.2;3}1.2{3.2}3;3.6.2T2}1f3N1f3}2;4.7.1T2}2f1N2f2}1T6.7.2T2}1f1N1f2}2T6.8.1T2}1f1N1f1}3T6.8.2T1}3f1}3T6.8.2T2}1f2}2T7.8.3T1}1f2}1T8.7.4T1}1f2}1T8.6.5T1}1f2}2T7.6.5T1}1f2}3T6.5.6T1}1f2}3T6.5.1T2.5B2C2B1T6.7.3C3T1B3C7.7.3C2.>6.4L5.3L6.', 24),
  ]],
  ['La Palenquera', [
    sp('8.2X4.1X2.1X6.9.1X1?1<1?3]2Y6.8.1X1.1<1?1<1?3]2c1X4.9.1.1?1<1?1<3]3c4.9.1.9{5.9.2.7{6.9.3.5[7.9.2.1[1<5[6.9.1.1[1<1r1[1M2J1[6.9.1.1[1<1r1M4J6.9.2.1<1r1M1A2J1A6.9.2.2r2J2]1J6.9.3.1M5J6.9.1.2<1.2J2.2<5.9.1J2r6<1r1J4.7.3J2[6r3J3.6.3J3.5[2.2J3.4.3J5.5<2.2J3.3.1G2[6.5<1.3J3.4.1G3[2r8<2J4.4.2G3[2r1<5r1<1r5.5.2G3[1r1<5r1<2[4.6.2G4[5<2[1G4.5.2J3G8[1G5.4.4J1.9G6.4.2J9.2J7.5.1J9.2J7.9.6.3J6.', 24),
    sp('~~~8.2X4.1X2.1X6.9.1X1?1<1?3]2Y6.8.1X1.1<1?1<1?3]2c1X4.9.1.1?1<1?1<3]3c4.9.1.9{5.9.2.7{6.9.3.5[7.9.2.1[1<5[6.9.1.1[1<1r1[1M2J1[6.9.1.1[1<1r1M4J4.1X1.9.2.1<1r1M1A2J1A3.3]9.2.2r2J2]1J3.3]9.3.1M5J4.2J4.2[2.2J2<1.2J2.2<2.2J1.3.1G1[1.4J2r6<1r1J1.2J1.3.1G1[3J2.2[6r5J1.3.1G2[6.5[2.3J2.3.1G2[6.5<7.4.1G2[3r8<6.4.2G2[3r1<5r1<1r5.5.2G3[1r1<5r1<2[4.6.2G4[5<2[1G4.7.3G8[1G1J4.9.9G3J3.9.1.3J6.3J2.', 24),
    sp('5.2X4.1X2.1X9.6.1X1?1<1?3]2Y9.5.1X1.1<1?1<1?3]2c1X7.7.1?1<1?1<3]3c7.7.9{8.8.7{9.9.5[9.1.8.1[1<3[1<9.1.7.1[2<1M3J1<9.7.1[1<1M4J1<9.8.1<1J1A2J1A9.1.8.1r2J2]1J9.1.9.1M4J9.1.7.2<1.2J2.2<8.1.1J2.3J2r6<1r2J6.1.6J2[6r6J3.1G2[1<5.5[5.3J2.1G1[2r2<3.1?5<6.1<2.1G2[2r2<3?9<2r1[2.1.1G2[2r9<1<4r1[1G2.1.2G2[3r1<5r1<3r2[2G2.2.2G2[2r1<5r1<2r2[2G3.3.2G4[5<3[3G4.4.3G8[3G6.6.9G1G8.8.2J2.2J9.1.7.3J2.2J9.1.7.3J2.3J9.', 24),
  ]],
  ['Marimonda', [
    sp('4.3r1.7o1.3r5.3.5r3&1o3&5r4.3.5r1&2B1Y2B1&5r4.^3.5r3&1Y3&5r1.2{1.3.5r3o1Y3o5r1.2{1.4.4r1o2<1Y2<1o4r2.2G1.8.1o2N1Y2N1o4.3G2.9.2o1Y2o3.5G2.8.2c1r1Y1r2c5G4.7.1G2c3r2c4G5.5.3G2c1G1r1G2c9.4.3G1.2c1G1r1G2c9.3.3G2.2c1G1r1G2c9.3.2G3.2c1G1r1G1c1<1c8.2.3G4.1<2G2<1c1<8.1.2{1G5.1<1c1<1c3<1c7.1.2{5.1c2<3.1c2<7.8.1<1c4.1<1c8.8.2<4.1c1<8.8.1c2<3.2Y8.8.2<1c3.3Y7.9.2Y9.4.8.3Y9.4.', 24),
    sp('7.7o1.3r6.5.1r3&1o3&1o5r5.4.2r1&2B1Y2B1&1o5r5.3.3r1&2B1Y2B1&1o5r5.3.3r3&1Y3&1o5r5.3.4r2o1Y4o5r5.4.3r1o1<1Y3<1o4r6.7.1o1N1Y3N1o9.1.8.1o1Y3o9.2.7.1G1c1Y2r2c2G8.6.2G1c3r2c3G7.5.3G1c1G1r1G2c3G7.4.3G1.1c2{6G7.4.2G2.1c2{5E8.4.1G2{1.1c1G1r1G2c9.1.5.2{1.1<3G2<9.1.8.2<1c1<1c1<9.1.8.1c5<9.1.9.1c1<1c1<2J1<2Y6.9.1.2<2J1c1<2Y6.9.1.2<5.1Y6.9.1<1c9.4.9.2Y9.4.8.3Y9.4.', 24),
    sp('~~~5.3r9.3r4.4.5r7o5r3.^4.5r3&1o3&5r3.4.5r1&2B1Y2B1&5r3.^5.4r3&1Y3&4r4.9.1o2<1Y2<1o8.9.1o2N1Y2N1o8.6.3G1c2o1Y2o1c3G5.5.4G2c1r1Y1r2c4G4.4.3G2.2c1G1r1G2c2.3G3.4.2G3.2c1G1r1G2c3.2G3.4.2{3.2c1G1r1G2c3.2{3.4.2{2.2<1c1G1r1G1c2<2.2{3.6.1<1c4<1G2<1c3<1c4.6.3<1c1<1c1<1c3<1c2<4.6.1c2<8.1<1c5.6.2<1c8.1c1<5.7.2Y8.2Y5.6.3Y8.3Y4.', 24),
    sp('6.3r1.7o2r5.5.5r1o3&1o3&2r4.5.5r1o1&2B1Y2B1&2r4.^5.5r1o3&1Y3&2r4.5.5r4o1Y2o3r4.6.4r1o3<1Y1<1o2r5.9.1.1o3N1Y1N1o7.9.2.3o1Y1o8.8.2G2c2r1Y1c1G7.7.3G2c3r1c1G7.7.2G1.2c1G1r1G1c1G7.^7.2G1.2c1G1r1G1c2G6.7.3G1{1c1G1r1G1c2G1{5.8.1G2{1<3G1<1.2{5.9.1.1<1c1<1c2<8.6.1Y1c1<1.5<1c8.6.1Y3<1c1<1c1<1c1<8.6.2Y1c2<1c1<1.3<7.6.1Y2.1<1c2<2.1c1<7.9.6.1<1c7.9.6.2Y7.9.6.3Y6.', 24),
  ]],
];

const TITLE_SPRITE = sp('2.9B9B9B2.1.2B1A1B9A9A5A2B1.1.1B1A1<2A1<1A1<1A2<1A2x2A1x2A1x1A2[1A3[1A1B1.1.1B1A2<1A1<3A1<2A1x1A1x1A2x1A1x1A1[2A1[3A1B1.1.1B2A3<1A1<1A2<1A1x1A1x1A4x1A2[1A3[1A1B1.1.2B1A2<2A1<1A1<2A2x2A1x1A2x1A1[4A1[1A1B1.2.1B2A1<2A1<1A2<1A1x1A1x1A1x1A2x1A3[1A2[1A1B1.1.2B9A9A8A1B1.1.1B1A6G3A2E2A2E9A1A2B1.1.1B1A2G3A2G2A1E1A1E1A1E3A4G2A2G1A1B1.1.1B1A2G3A2G2A1E1A1E1A2E2A2G2A1G1A1G1A1G2B1.1B1A2G2A2G3A2E2A1E3A2G2A1G1A1G1A1G1A1B1.1B1A5G8A2E3A1G2A1G1A1G1A1G1A1B1.1B1A4G4A1G1A1G1A1G3A1G1A3G2A3G1A1B2B1A2G1A2G3A1G1A1G1A2G1A2G1A1G1A2G1A1G1A1G1A1B2B1A2G2A3G1A1G1A1G1A1G1A1G1A1G1A1G2A1G1A1G1A1G1A1B1B1A3G1A4B1A3G1A1G3A1G1A4G1A1G1A1G1A1B2B3A5B7A1B9A3A1B1.5B2.9B9B4B1.', 31);

/* === GAMEPLAY CONSTANTS === */
const DIR = { L: 0, D: 1, U: 2, R: 3 }; // Direction lane indices (0: Left, 1: Down, 2: Up, 3: Right)

// Base arrow sprite points UP; rotate to face each lane
const DIR_ROT = [-MPI / 2, MPI, 0, MPI / 2]; // Rotation in radians for Left (-90°), Down (180°), Up (0°), Right (90°)
const ARROW_LIGHT = [C.pL, C.pD, C.pU, C.pR]; // Highlight fill colors per direction lane
const ARROW_DARK = [C.pLD, C.pDD, C.pUD, C.pRD]; // Highlight border colors per direction lane
const clamp = (v, a, b) => Mmax(a, Mmin(b, v));
const fRect = (g, c, a, x, y, w, h) => { g.fillStyle(c, a); g.fillRect(x, y, w, h); };

const STATE = { SPLASH: -1, TITLE: 0, CHARSEL: 1, SONGSEL: 2, BATTLE: 3, WIN: 4, DIFFSEL: 5 }; // Game flow states
const state = { v: STATE.SPLASH, t: 0, countdownStart: 0, songDecoded: null, songStart: 0, songEnd: 0, winner: -1 };

const players = [
  { name: '', sprites: DANCERS[0][1], center: { x: 157, y: 380 }, box: { x: 85, y: 255, w: 145, h: 220 },
    combo: 0, score: 0, arrows: [], notes: [], keys: ['P1_L', 'P1_D', 'P1_U', 'P1_R'],
    dK: [['P1_L', 'P1_4', 'P1_1'], ['P1_D', 'P1_5'], ['P1_U', 'P1_2'], ['P1_R', 'P1_6', 'P1_3']],
    aBnc: [0, 0, 0, 0],
    color: 0xff5577, perfect: 0, good: 0, miss: 0, seq: 0, gfx: null,
    pIdx: 0, pDx: 0, pDy: 0, pT: 0 },
  { name: '', sprites: DANCERS[1][1], center: { x: 642, y: 400 }, box: { x: 570, y: 255, w: 145, h: 220 },
    combo: 0, score: 0, arrows: [], notes: [], keys: ['P2_L', 'P2_D', 'P2_U', 'P2_R'],
    dK: [['P2_L', 'P2_4', 'P2_1'], ['P2_D', 'P2_5'], ['P2_U', 'P2_2'], ['P2_R', 'P2_6', 'P2_3']],
    aBnc: [0, 0, 0, 0],
    color: 0x77dd55, perfect: 0, good: 0, miss: 0, seq: 0, gfx: null,
    pIdx: 0, pDx: 0, pDy: 0, pT: 0 },
];

// Global runtime game state and visual container references
const G = {
  fxL: null, titL: null, winL: null, tugGfx: null, splL: null,
  wrldL: null, hudL: null,
  bgGfx: null, stageGfx: null, floorGfx: null,
  pLyrs: [],
  notes: [], nSpwn: 0, nTot: 0,
  bar: 0, barVis: 0, // Tug-of-war bar value (-100 to +100) and smoothly interpolated visual position
  cam: null, uiCam: null, camX: 400, camY: 300, camZ: 1, // Camera tracking coordinates & zoom level
  music: null, lastTurn: -1, turnT: 0, turnTxt: null, // Active music instance, turn tracking, and turn HUD text
  audS: 0, sLen: 0, blurred: 0, // Audio start timestamp and song total length in seconds
  diff: 1, // 0: EASY, 1: MEDIUM, 2: HARD
  mode: '2p', sSng: 0, cSel: [{cursor: 0, ok: 0}, {cursor: 0, ok: 0}], aiPck: 0,
};

new Phaser.Game({
  type: Phaser.AUTO, width: W, height: H, parent: 'game-root',
  backgroundColor: '#000', pixelArt: 1,
  scene: { create, update },
});

function updateStagePlayer(idx, fighterIdx, isInstant = 0) {
  G.cSel[idx].cursor = fighterIdx;
  const f = DANCERS[fighterIdx];
  const p = players[idx];

  const tx = idx === 0 ? G.p1Tx : G.p2Tx;
  if (tx && !G.cSel[idx].ok) {
    tx.setText(f[0]);
  }

  if (isInstant || !G.titL?.scene) {
    p.name = f[0];
    p.sprites = f[1];
    p.pIdx = 0;
    const g = G.pLyrs[idx];
    if (g) {
      g.clear();
      dsp(g, f[1][0], 0, 0, true);
    }
  } else {
    p.nNam = f[0];
    p.nSpr = f[1];
    p.slOut = 1;
    p.slTgt = 400;
  }
}

function create() {
  const s = this;
  G.wrldL = s.add.container(0, 0);
  G.fxL = s.add.container(0, 0);
  G.hudL = s.add.container(0, 0).setDepth(100);
  G.titL = s.add.container(0, 0).setDepth(200);
  G.winL = s.add.container(0, 0).setDepth(200);
  G.splL = s.add.container(0, 0).setDepth(300);

  // Setup Phaser input bindings
  s.input.keyboard.disableGlobalCapture();
  for (const k in CABINET_KEYS) {
    arcadeKeys[k] = CABINET_KEYS[k].map(c => s.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes[phaserKey(c)]));
  }

  drawBackground(s);
  drawStage(s);
  drawFloor(s);
  drawPlayer(s, 0);
  drawPlayer(s, 1);
  drawTugBar(s);
  drawArrowGfx(s);
  G.wrldL.add([G.bgGfx, G.stageGfx, G.floorGfx, G.pLyrs[0], G.pLyrs[1], G.fxL]);

  // Two cameras: main zooms/pans on the world, UI cam keeps HUD fixed
  G.cam = s.cameras.main;
  G.uiCam = s.cameras.add(0, 0, W, H);
  G.cam.ignore([G.hudL, G.titL, G.winL, G.splL]);
  G.uiCam.ignore([G.wrldL]);

  G.turnTxt = cTxt(s, W / 2, 90, '', 22, '#fff200', 1).setAlpha(0);
  for (let i = 0; i < 2; i++) players[i].cTxt = cTxt(s, i ? 650 : 150, 46, '', 16, i ? '#77dd55' : '#ff5577', 1);
  G.hudL.add([G.tugGfx, ...players[0].arrows, ...players[1].arrows, G.turnTxt, players[0].cTxt, players[1].cTxt]);
  G.hudL.setVisible(0);

  clearInputs();

  if (SKIP_TO_GAMEPLAY) {
    updateStagePlayer(0, 0);
    updateStagePlayer(1, 1 % DANCERS.length);
    G.pendingStart = 1;
    // menu song
    unpack(SONGS[0].data).then(song => {
      G.midiText = song;
      G.nSng = decode(song);
      G.pendingStart = 0;
      startBattle();
    });
  } else if (SKIP_TO_CHARSEL) {
    state.v = STATE.CHARSEL;
    drawCharSelScreen(s);
    updateStagePlayer(0, 0, 1);
    updateStagePlayer(1, 1 % DANCERS.length, 1);
    unpack(MIDI_SONG).then(song => {
      G.mTxt = song;
      startMenuMusic();
    });
  } else {
    drawSplashScreen(s);
    unpack(MIDI_SONG).then(song => {
      G.mTxt = song;
      startMenuMusic();
    });
  }

  G.blurred = 0;
  const setBlur = (v) => { G.blurred = v; clearInputs(); };
  document.addEventListener('visibilitychange', () => setBlur(document.hidden));
  window.addEventListener('blur', () => setBlur(1));
  window.addEventListener('focus', () => setBlur(0));

  const unlockAudio = () => {
    const ctx = s.sound?.context;
    if (ctx && ctx.state === 'suspended') {
      ctx.resume().catch(() => {});
    }
    startMenuMusic();
  };
  window.addEventListener('pointerdown', unlockAudio);
  window.addEventListener('keydown', unlockAudio);
  s.input.on('pointerdown', unlockAudio);
}

function startMenuMusic() {
  if (state.v === STATE.BATTLE || state.v === STATE.WIN || state.v === STATE.SONGSEL || state.v === STATE.DIFFSEL) return;
  if (!G.mTxt) return;
  const ctx = G.titL?.scene?.sound?.context;
  if (!ctx) return;
  if (ctx.state === 'suspended') {
    ctx.resume().catch(() => {});
  }
  if (G.mMus) return;
  G.mMus = playMidi(ctx, G.mTxt, (len) => {
    G.menuSongLen = len;
  });
}

/* === DRAWING === */
function drawSplashScreen(s) {
  G.hudL.setVisible(0);
  G.titL.setVisible(0);
  G.winL.setVisible(0);
  G.splL.removeAll(1);
  G.splL.setVisible(1);

  const bg = s.add.rectangle(W / 2, H / 2, W, H, 0x000, 1);
  const txt = cTxt(s, W / 2, H / 2, '🇨🇴 Platanus hack 26, Bogotá 🇨🇴\n\npresenta', 24, '#fff', 1);
  txt.setAlign('center');
  G.splL.add([bg, txt]);
}

function drawBackground(s) {
  const g = s.add.graphics(), FW = W + 2 * PAD, X0 = -PAD;
  g.setDepth(-100);
  // Sky gradient — deep blue top to pale horizon
  const sky = [0x1a3466, 0x254a82, 0x30609e, 0x4578b8, 0x5c90cc, 0x74a8dd, 0x8ec0ea, 0xa8d6f4];
  const bh = Mceil((H + 2 * PAD) / sky.length);
  for (let i = 0; i < sky.length; i++) { fRect(g, sky[i], 1, X0, -PAD + i * bh, FW, bh + 1); }
  // Warm horizon glow
  fRect(g, 0xf0e0c0, .08, X0, 120, FW, 80);
  // Clouds — layered ellipses for volume
  for (const [cx, cy, rw, rh] of [[100, 20, 110, 30], [370, -8, 140, 36], [650, 42, 95, 26], [210, 88, 65, 18], [530, 72, 105, 25]]) {
    g.fillStyle(0xfff, .32); g.fillEllipse(cx, cy, rw, rh);
    g.fillStyle(0xfff, .16); g.fillEllipse(cx + rw * .22, cy - rh * .18, rw * .5, rh * .4);
    g.fillStyle(0xfff, .08); g.fillEllipse(cx - rw * .18, cy + rh * .12, rw * .35, rh * .25);
  }
  G.bgGfx = g;
}

function drawStage(s) {
  const g = s.add.graphics(), X0 = -PAD, X1 = W + PAD, FW = X1 - X0;
  g.setDepth(-90);
  const drawMtn = (c, a, fn) => {
    g.fillStyle(c, a);
    g.beginPath(); g.moveTo(X0, 400);
    for (let x = X0; x <= X1; x += 6) g.lineTo(x, fn(x));
    g.lineTo(X1, 400); g.closePath(); g.fillPath();
  };
  // Far mountains (misty green — Cerros Orientales)
  drawMtn(0x3a6a4a, 1, x => 155 + Msin(x * .005) * 55 + Msin(x * .013 + 1) * 30 + Mcos(x * .009) * 22);
  // Mountain mist band
  fRect(g, 0x90b8d4, .1, X0, 185, FW, 45);
  // Near mountains (rich dark green)
  drawMtn(0x1e4a2a, 1, x => 215 + Msin(x * .007 + 2) * 48 + Msin(x * .021) * 18);
  // Highlight ridge on near mountains
  drawMtn(0x2a6a3a, .25, x => 222 + Msin(x * .007 + 2) * 46 + Msin(x * .021) * 17);
  // Tall buildings (Bogotá skyline)
  for (let x = X0 + 15; x < X1; x += 65) {
    const bh = 80 + ((x * 7 + 31) & 127), by = 400 - bh, bw = 28 + ((x * 3) & 7);
    fRect(g, 0x484860, 1, x, by, bw, bh);
    fRect(g, 0x3a3a50, 1, x + bw - 5, by, 5, bh);
    fRect(g, 0x5a5a70, 1, x, by, bw, 3);
    for (let wy = by + 10; wy < 392; wy += 12)
      for (let wx = x + 3; wx < x + bw - 3; wx += 8) {
        g.fillStyle(((wx * 3 + wy * 7) & 7) > 2 ? 0xffe888 : 0x28283a, ((wx + wy) & 3) ? .5 : .3);
        g.fillRect(wx, wy, 4, 6);
      }
  }
  // Colorful houses (La Candelaria)
  const hc = [0xc83030, 0x2266bb, 0xd4a020, 0x2e8a48, 0xd06828, 0x9a3388, 0xc75080, 0xe8e0c8];
  for (let x = X0, ci = 0; x < X1; x += 24, ci++) {
    const h = 30 + ((x * 3 + 17) & 31), by = 400 - h;
    fRect(g, hc[(ci * 3 + 1) % hc.length], 1, x, by, 22, h);
    fRect(g, 0x000, .12, x + 18, by, 4, h);
    fRect(g, 0x000, .18, x - 1, by, 24, 2);
    fRect(g, 0x1a1a1a, .65, x + 8, 400 - 16, 6, 16);
    fRect(g, 0xddddcc, .5, x + 3, by + 8, 5, 5); g.fillRect(x + 14, by + 8, 5, 5);
  }

  G.stageGfx = g;
}

function drawFloor(s) {
  const g = s.add.graphics(), FW = W + 2 * PAD, X0 = -PAD, FH = H + PAD - 400;
  g.setDepth(-80);
  // Concrete plaza
  fRect(g, 0x989490, 1, X0, 400, FW, FH);
  // Tile joints
  g.fillStyle(0x000, .06);
  for (let y = 400; y < H + PAD; y += 48) g.fillRect(X0, y, FW, 1);
  for (let x = X0; x < W + PAD; x += 48) g.fillRect(x, 400, 1, FH);
  // Depth darkening
  fRect(g, 0x000, .05, X0, 500, FW, H + PAD - 500);
  // Surface specks
  for (let i = 0; i < 30; i++) {
    fRect(g, i & 1 ? 0x868280 : 0xaaa6a0, .4, ((i * 73 + 11) % W) + X0, 410 + ((i * 37) % (H - 420 + PAD)), 2, 1);
  }
  // Curb edge
  fRect(g, 0x666660, 1, X0, 400, FW, 3);
  fRect(g, 0xb0aca6, .35, X0, 400, FW, 1);
  G.floorGfx = g;
}

function drawPlayer(s, idx) {
  const p = players[idx];
  const g = s.add.graphics();
  // g.setDepth(-50);
  g.setScale(idx === 0 ? 9 : -9, 9);
  const pose = p.sprites[p.pIdx % p.sprites.length];
  dsp(g, pose, 0, 0, true);
  G.pLyrs[idx] = g;
  p.gfx = g;
}

function drawTugBar(s) {
  const g = s.add.graphics();
  G.hudL.add(g);
  G.tugGfx = g;
}

function drawTugGfx() {
  const g = G.tugGfx;
  if (!g) return;
  G.barVis += (G.bar - G.barVis) * 0.12;
  g.clear();

  const diff = Mabs(G.bar - G.barVis);
  const shake = Mmax(0, diff - 2) * 0.6;
  const sx = shake > 0 ? (Mrnd() - 0.5) * shake : 0;
  const sy = shake > 0 ? (Mrnd() - 0.5) * shake : 0;

  const bx = 200 + sx, by = 18 + sy, bw = 400, bh = 32; // Thicker bar

  // Thick pixel border (NES style)
  fRect(g, 0x000, 1, bx - 8, by - 8, bw + 16, bh + 16);
  fRect(g, 0x2a2a3a, 1, bx - 4, by - 4, bw + 8, bh + 8);
  // Bar background
  fRect(g, 0x0a0a14, 1, bx, by, bw, bh);

  // Dynamic color split based on marker
  const mx = Mround(bx + ((G.barVis + BAR_MAX) / (2 * BAR_MAX)) * bw);
  const fillW = mx - bx;
  fRect(g, C.p1H, 1.0, bx, by, fillW, bh);
  fRect(g, C.p2H, 1.0, mx, by, bw - fillW, bh);

  // Draw sprite busts pushing each other (scaled x4, 8 rows = 32px height)
  if (players[0]?.sprites) dsp(g, players[0].sprites[0], mx - 30, by + 48, true, false, 8, 4);
  if (players[1]?.sprites) dsp(g, players[1].sprites[0], mx + 30, by + 48, true, true, 8, 4);
}

function drawArrowGfx(s) {
  for (let pi = 0; pi < 2; pi++) {
    for (let i = 0; i < 4; i++) {
      const g = s.add.graphics();
      drawArrow(g, LANE_X[pi][i], HIT_Y, ARROW_SCALE, DIR_ROT[i], C.arrowL, C.arrowD);
      players[pi].arrows.push(g);
      G.hudL.add(g);
    }
  }
}

function drawTitleScreen(s) {
  G.hudL.setVisible(0);
  G.winL.setVisible(0);
  G.titL.removeAll(1);
  G.titL.setVisible(1);

  // Black background
  const bg = s.add.rectangle(W / 2, H / 2, W, H, 0x000, 1);
  G.titL.add(bg);

  // Title sprite (31x19) centered near top
  const titleGfx = s.add.graphics();
  titleGfx.setScale(10, 10);
  titleGfx.x = W / 2 - 20;
  titleGfx.y = 170;
  dsp(titleGfx, TITLE_SPRITE, 0, 0, {});
  G.titL.add(titleGfx);
  G.titleSpriteGfx = titleGfx;

  // Mode selector text (will be updated by updateTitleMode)
  G.titleModeTxts = [];
  updateTitleMode(s);

  // // Bottom text
  // const startTxt = cTxt(s, W / 2, H - 50, 'PRESIONA CUALQUIER TECLA', 16, '#fff', 1);
  // G.titL.add(startTxt);
  // G.startText = startTxt;

  // 4 dancing characters: 2 on the left, 2 on the right
  // Cycle through DANCERS if fewer than 4
  const dCount = DANCERS.length;
  const dancerIndices = [0 % dCount, 1 % dCount, (dCount > 2 ? 2 : 0) % dCount, (dCount > 3 ? 3 : 1) % dCount];
  G.tDnc = [];
  const positions = [
    { x: 100, y: 420, flip: 1 },   // left back
    { x: 185, y: 440, flip: 1 },   // left front
    { x: W - 185, y: 440, flip: -1 }, // right front
    { x: W - 100, y: 420, flip: -1 }, // right back
  ];
  for (let i = 0; i < 4; i++) {
    const di = dancerIndices[i];
    const sprites = DANCERS[di][1];
    const g = s.add.graphics();
    const scale = 7;
    g.setScale(positions[i].flip * scale, scale);
    g.x = positions[i].x;
    g.y = positions[i].y;
    const pIdx = 0;
    dsp(g, sprites[pIdx], 0, 0, true);
    G.titL.add(g);
    G.tDnc.push({ gfx: g, sprites, pIdx, dancerIdx: di, timer: 0 });
  }
}

function updateTitleMode(s) {
  // Remove old mode texts
  if (G.titleModeTxts) {
    for (const t of G.titleModeTxts) { if (t && t.active) t.destroy(); }
  }
  const m1Sel = G.mode === '1p';
  const m2Sel = G.mode === '2p';
  const m1Tx = cTxt(s, W / 2 - 20, H / 2 + 50, m1Sel ? '> 1 JUGADOR' : '  1 JUGADOR', 22, m1Sel ? '#fff' : '#555', 1);
  const m2Tx = cTxt(s, W / 2 - 20, H / 2 + 90, m2Sel ? '> 2 JUGADORES' : '  2 JUGADORES', 22, m2Sel ? '#fff' : '#555', 1);
  G.titL.add([m1Tx, m2Tx]);
  G.titleModeTxts = [m1Tx, m2Tx];
}

function drawPatternBg(s) {
  if (G.menuBgGraphics) {
    s.tweens.killTweensOf(G.menuBgGraphics);
    G.menuBgGraphics.destroy();
  }
  const bg = s.add.graphics();
  G.menuBgGraphics = bg;

  // Colombian FNF Vibe: Base is pure black for max contrast
  bg.fillStyle(0x000000, 1);
  bg.fillRect(-120, -120, W + 240, H + 240);

  // Diagonal bold stripes in Colombian colors (Yellow, Blue, Red)
  const colors = [0xFFD166, 0x118AB2, 0xEF476F];

  for (let y = -120; y < H + 240; y += 120) {
    for (let x = -120; x < W + 240; x += 120) {
      bg.lineStyle(10, colors[((x + y) / 120) % 3], 0.08); // Extremely low opacity
      bg.strokeCircle(x, y, 40);
      bg.strokeCircle(x, y, 80);
    }
  }

  G.wrldL.add(bg);
  G.wrldL.sendToBack(bg);

  s.tweens.add({
    targets: bg,
    x: -120,
    y: -120,
    duration: 3000,
    ease: 'Linear',
    repeat: -1
  });
}

function drawCharSelScreen(s) {
  drawPatternBg(s);
  G.hudL.setVisible(0);
  G.winL.setVisible(0);
  G.titL.removeAll(1);
  G.titL.setVisible(1);
  [G.bgGfx, G.stageGfx, G.floorGfx].forEach(g => g && g.setVisible(0));

  G.charSelGfx = s.add.graphics();
  G.titL.add(G.charSelGfx);
  G.cSSpr = [];

  for (let i = 0; i < DANCERS.length; i++) {
    const sg = s.add.graphics();
    dsp(sg, DANCERS[i][1][0], 0, 0, 1);
    sg.setScale(3.5);
    G.titL.add(sg);
    G.cSSpr.push(sg);
  }
  G.p1Tx = cTxt(s, 157, 530, DANCERS[G.cSel[0].cursor][0], 28, '#ff5577', 1).setStroke('#000', 5);
  G.p2Tx = cTxt(s, 643, 530, DANCERS[G.cSel[1].cursor][0], 28, '#77dd55', 1).setStroke('#000', 5);
  G.titL.add([G.p1Tx, G.p2Tx]);
}

function drawSongSelScreen(s) {
  drawPatternBg(s);
  G.hudL.setVisible(0);
  G.winL.setVisible(0);
  G.titL.removeAll(1);
  G.titL.setVisible(1);

  if (G.mMus) { G.mMus.stop(); G.mMus = null; }

  if (G.bgGfx) G.bgGfx.setVisible(0);
  if (G.stageGfx) G.stageGfx.setVisible(0);
  if (G.floorGfx) G.floorGfx.setVisible(0);

  const title = cTxt(s, W/2, 100, '🎶 SELECCIONA UNA CANCIÓN 🎶', 28, '#e7e7e7', 1);
  G.titL.add(title);

  G.sLItm = [];
  G.sLGfx = s.add.graphics();
  G.titL.add(G.sLGfx);

  for (let i = 0; i < SONGS.length; i++) {
    const name = cTxt(s, 0, 0, SONGS[i].name, 18, '#fff', 1);
    const meta = cTxt(s, 0, 0, SONGS[i].genre + '  •  ' + SONGS[i].bpm, 12, '#cccccc', 0);
    G.titL.add([name, meta]);
    G.sLItm.push({ name, meta });
  }

  playSongPreview(s, G.sSng);
}

function drawDiffSelScreen(s) {
  if (G.pMus) { G.pMus.stop(); G.pMus = null; }
  drawPatternBg(s);
  G.hudL.setVisible(0);
  G.winL.setVisible(0);
  G.titL.removeAll(1);
  G.titL.setVisible(1);

  const title = cTxt(s, W/2, 100, 'SELECCIONA DIFICULTAD', 32, '#fff', 1);
  G.titL.add(title);

  G.dLItm = [];
  G.dLGfx = s.add.graphics();
  G.titL.add(G.dLGfx);

  const diffTxts = ['FÁCIL 🐥', 'NORMAL ✌️', 'DIFÍCIL 🌶️'];
  for (let i = 0; i < diffTxts.length; i++) {
    const txt = cTxt(s, 0, 0, diffTxts[i], 22, '#fff', 1);
    G.titL.add(txt);
    G.dLItm.push(txt);
  }
}

function showWinScreen(winner) {
  G.hudL.setVisible(0);
  G.winL.removeAll(1);
  G.winL.setVisible(1);

  const s = G.titL.scene;
  const col = winner === 0 ? '#ff5577' : '#77dd55';
  const t2 = cTxt(s, W / 2, -50, `${players[winner].name} GANÓ LA RUMBA`, 42, col, 1).setStroke('#000', 6);
  s.tweens.add({
    targets: t2,
    y: 80,
    duration: 1000,
    ease: 'Bounce.easeOut'
  });

  const boxH = 120;
  const bg = s.add.rectangle(W / 2, H - boxH / 2, W, boxH, 0x000, 0.8);

  const w = players[winner];
  const t3 = cTxt(s, W / 2, H - boxH / 2 - 10, `PERFECTO: ${w.perfect}   BIEN: ${w.good}   FALLO: ${w.miss}\nPUNTUACIÓN: ${w.score}`, 20, '#fff', 1).setStroke('#000', 4).setAlign('center');

  const t4 = cTxt(s, W / 2, H - 30, 'PRESIONA START PARA VOLVER', 20, '#ffd166', 1).setStroke('#000', 4);
  t4.setAlpha(0);

  G.winL.add([bg, t2, t3, t4]);
  G.winText = t4;
}

/* === STATE TRANSITIONS === */
function startBattle() {
  if (G.music) { G.music.stop(); G.music = null; }
  if (G.mMus) { G.mMus.stop(); G.mMus = null; }
  if (G.pMus) { G.pMus.stop(); G.pMus = null; }
  state.v = STATE.BATTLE;

  if (G.bgGfx) G.bgGfx.setVisible(1);
  if (G.stageGfx) G.stageGfx.setVisible(1);
  if (G.floorGfx) G.floorGfx.setVisible(1);
  if (G.menuBgGraphics) G.menuBgGraphics.setVisible(0);

  state.t = 0;
  state.winner = -1;
  state.songStart = 0;
  state.songEnd = 0;
  G.audS = 0; G.sLen = 0;
  G.bar = 0; G.barVis = 0;
  G.lastTurn = -1;
  for (const p of players) {
    p.combo = 0; p.score = 0;
    p.perfect = 0; p.good = 0; p.miss = 0;
    p.aBnc = [0, 0, 0, 0];
    if (p.notes) {
      for (const n of p.notes) { if (n.gfx) { n.gfx.destroy(); n.gfx = null; } }
    }
    p.notes = []; p.seq = 0;
    if (p.cTxt) p.cTxt.setText('');
  }
  G.nSpwn = 0;
  if (G.nSng) buildSchedule();
  G.titL.setVisible(0);
  G.winL.setVisible(0);
  G.hudL.setVisible(1);
  clearInputs();
  if (G.nSng) startCountdown(G.titL.scene);
}

function startCountdown(s) {
  if (G.cntL) { G.cntL.destroy(); G.cntL = null; }
  const cntL = s.add.container(0, 0).setDepth(250);
  G.cntL = cntL;
  const nums = ['3', '2', '1'];
  const cols = ['#ffd166', '#ff9933', '#ff5577'];

  const showStep = (idx) => {
    if (state.v !== STATE.BATTLE) {
      if (G.cntL) { G.cntL.destroy(); G.cntL = null; }
      return;
    }
    if (idx < 3) {
      playCountdownTone(idx);
      const tx = cTxt(s, W / 2, H / 2 - 20, nums[idx], 96, cols[idx], 1).setStroke('#000', 8);
      cntL.add(tx);
      s.tweens.add({
        targets: tx,
        scale: { from: 1.6, to: 0.9 },
        alpha: { from: 1, to: 0 },
        duration: 700,
        ease: 'Cubic.easeOut',
        onComplete: () => {
          tx.destroy();
          showStep(idx + 1);
        }
      });
    } else {
      playCountdownTone(3);
      startMusic();
      const lg = s.add.graphics();
      lg.x = W / 2;
      lg.y = H / 2 - 20;
      dsp(lg, TITLE_SPRITE, 0, 0, true);
      cntL.add(lg);
      s.tweens.add({
        targets: lg,
        scaleX: { from: 3.5, to: 8.5 },
        scaleY: { from: 3.5, to: 8.5 },
        duration: 320,
        ease: 'Back.easeOut',
        onComplete: () => {
          s.tweens.add({
            targets: lg,
            alpha: 0,
            scaleX: 10.5,
            scaleY: 10.5,
            duration: 440,
            delay: 240,
            ease: 'Quad.easeIn',
            onComplete: () => {
              if (G.cntL) { G.cntL.destroy(); G.cntL = null; }
            }
          });
        }
      });
    }
  };

  showStep(0);
}

function startMusic() {
  if (!G.nSng) return;
  const ctx = G.titL.scene.sound.context;
  G.audS = ctx.currentTime + 0.08; // playMidi internal base offset
  G.music = playMidi(ctx, G.midiText, len => {
    if (state.v === STATE.BATTLE) G.sLen = len;
  });
}

function endBattle() {
  if (G.cntL) { G.cntL.destroy(); G.cntL = null; }
  let w;
  if (G.bar >= BAR_MAX) w = 0;
  else if (G.bar <= -BAR_MAX) w = 1;
  else w = G.bar > 0 ? 0 : 1;
  state.v = STATE.WIN;
  state.winner = w;
  state.winT = 0;
  for (const p of players) {
    if (p.notes) {
      for (const n of p.notes) { if (n.gfx) { n.gfx.destroy(); n.gfx = null; } }
    }
    p.notes = [];
    if (p.cmbT) { p.cmbT.destroy(); p.cmbT = null; }
  }
  G.hudL.setVisible(0);
  clearInputs();
  showWinScreen(w);
}

function buildSchedule() {
  G.notes = [];
  const song = G.nSng;
  const tempos = song.events.filter(e => e.kind === 'T');
  const div = song.division;

  const cand = [];
  for (const e of song.events) {
    if (e.kind !== 'N' || e.channel === 9) continue;
    const t = secondsAt(e.tick, tempos, div);
    if (t < LEAD_IN) continue;
    cand.push({ t, tick: e.tick, pitch: e.pitch });
  }
  cand.sort((a, b) => a.t - b.t);

  const groups = [];
  for (const c of cand) {
    const g = groups.at(-1);
    if (g && c.t - g.t < 0.05) g.push(c);
    else groups.push([c]);
  }

  const kept = [];
  let lastT = -9;
  const diff = G.diff;
  const gaps = [0.4, 0.25, 0.14]; // 0: EASY, 1: MEDIUM, 2: HARD
  for (const g of groups) {
    g.sort((a, b) => b.pitch - a.pitch);
    const seen = {};
    let rank = 0;
    for (const n of g) {
      if (seen[n.pitch]) continue;
      seen[n.pitch] = 1;
      const primary = rank === 0;
      rank++;

      // Difficulty filtering
      if (diff === 0 && !primary) continue; // Easy: Primary notes only (gap will thin it out)
      if (diff === 1 && !primary) continue; // Medium: Primary notes only
      if (diff === 2 && !primary && n.tick % (div / 2) !== 0) continue; // Hard: Primary + 8th note accompaniment

      if (n.t - lastT < gaps[diff]) continue;
      lastT = n.t;
      kept.push(n);
    }
  }

  // Lane from pitch quartiles spread across the 4 directions
  const ps = kept.map(k => k.pitch).sort((a, b) => a - b);
  const q = i => ps[(((ps.length - 1) * i / 4) | 0)] ?? 60;
  for (const k of kept) {
    let dir;
    if (k.pitch < q(1)) dir = DIR.L;
    else if (k.pitch < q(2)) dir = DIR.D;
    else if (k.pitch < q(3)) dir = DIR.U;
    else dir = DIR.R;
    G.notes.push({ time: k.t, dir, turn: 1 - (((k.t / SEC_LEN) | 0) % 2) });
  }
  G.nTot = G.notes.length;
}

/* === UPDATE LOOP === */
function update(time, delta) {
  if (G.blurred) {
    clearInputs();
    return;
  }
  if (delta > 500) delta = 0;
  state.t += delta;

  for (const k in arcadeKeys) {
    const down = arcadeKeys[k].some(x => x.isDown);
    justPressed[k] = down && !held[k];
    justReleased[k] = !down && held[k];
    held[k] = down;
  }

  const s = G.titL.scene;

  if (state.v === STATE.SPLASH) {
    if (state.t > 2000 && !G.splashFading) {
      G.splashFading = 1;
      s.tweens.add({
        targets: G.splL.list[1], // Text
        alpha: 0,
        duration: 800,
        onComplete: () => {
          drawTitleScreen(s); // Draws under the black background
          s.tweens.add({
            targets: G.splL.list[0], // Black background
            alpha: 0,
            duration: 800,
            onComplete: () => {
              G.splL.setVisible(0);
              state.v = STATE.TITLE;
              state.t = 0;
            }
          });
        }
      });
    }
  } else if (state.v === STATE.TITLE) {
    if (justPressed.P1_U || justPressed.P1_D || justPressed.P2_U || justPressed.P2_D) {
      playMenuBlip();
      G.mode = G.mode === '1p' ? '2p' : '1p';
      updateTitleMode(s);
    }
    if (justPressed.START1 || justPressed.START2 || justPressed.P1_1 || justPressed.P2_1) {
      playMenuSelect();
      state.v = STATE.CHARSEL;
      G.cSel[0] = { cursor: 0, ok: 0 };
      G.cSel[1] = { cursor: 1 % DANCERS.length, ok: 0 };
      G.aiPck = 0;
      G.waitSong = 0;
      updateStagePlayer(0, G.cSel[0].cursor, 1);
      updateStagePlayer(1, G.cSel[1].cursor, 1);
      drawCharSelScreen(s);
    }
    // Animate dancing characters on title screen
    if (G.tDnc) {
      const DANCE_INTERVAL = 400; // ms between pose changes
      for (const d of G.tDnc) {
        d.timer += delta;
        if (d.timer >= DANCE_INTERVAL) {
          d.timer -= DANCE_INTERVAL;
          d.pIdx = (d.pIdx + 1) % d.sprites.length;
          d.gfx.clear();
          dsp(d.gfx, d.sprites[d.pIdx], 0, 0, true);
        }
      }
    }
    if (G.startText && G.startText.active) {
      G.startText.setAlpha(0.5 + 0.5 * Msin(state.t * 0.003));
    }
  } else if (state.v === STATE.CHARSEL) {
    let p1 = G.cSel[0], p2 = G.cSel[1], dl = DANCERS.length;
    if (G.mode === '1p') {
      if (!p2.ok) {
        if (justPressed.P1_L || justPressed.P2_L || justPressed.P1_R || justPressed.P2_R) { playMenuBlip(); updateStagePlayer(1, p2.cursor ^ 1); }
        if (justPressed.P1_U || justPressed.P2_U || justPressed.P1_D || justPressed.P2_D) { playMenuBlip(); updateStagePlayer(1, p2.cursor ^ 2); }
        if (justPressed.P1_1 || justPressed.P2_1 || justPressed.START1 || justPressed.START2) {
          playMenuSelect();
          p2.ok = 1; G.aiPck = 1; G.aiTick = 0; G.aiTicksLeft = 12; p1.ok = 0;
          if (G.p2Tx) G.p2Tx.setText('LISTO').setColor('#fff');
        }
      }
      if (G.aiPck) {
        G.aiTick += delta;
        if (G.aiTick > 80) {
          G.aiTick -= 80; G.aiTicksLeft--;
          updateStagePlayer(0, (p1.cursor + 1) % dl, 1);
          playMenuBlip();
          if (G.aiTicksLeft <= 0) {
            if (dl > 1 && p1.cursor === p2.cursor) updateStagePlayer(0, (p1.cursor + 1) % dl, 1);
            G.aiPck = 0; p1.ok = 1;
            playMenuSelect();
            if (G.p1Tx) G.p1Tx.setText('LISTO').setColor('#fff');
          }
        }
      }
    } else {
      for (let p = 0; p < 2; p++) {
        let cp = G.cSel[p];
        if (!cp.ok) {
          if (justPressed[`P${p+1}_L`] || justPressed[`P${p+1}_R`]) { playMenuBlip(); updateStagePlayer(p, cp.cursor ^ 1); }
          if (justPressed[`P${p+1}_U`] || justPressed[`P${p+1}_D`]) { playMenuBlip(); updateStagePlayer(p, cp.cursor ^ 2); }
          if (justPressed[`P${p+1}_1`] || justPressed[`START${p+1}`]) {
            playMenuSelect(); cp.ok = 1;
            const tx = p ? G.p2Tx : G.p1Tx;
            if (tx) tx.setText('LISTO').setColor('#fff');
          }
        }
      }
    }

    if (G.charSelGfx) {
      let g = G.charSelGfx; g.clear();
      let c1 = G.cSel[0].cursor, c2 = G.cSel[1].cursor;

      for (let i = 0; i < DANCERS.length; i++) {
        let isP1 = i === c1, isP2 = i === c2 && (G.mode === '2p' || G.aiPck || p2.ok);
        let sx = W/2 - 60 + (i % 2) * 120, sy = H/2 - 70 + ((i / 2) | 0) * 140;

        fRect(g, 0x1A102A, 1, sx - 50, sy - 60, 100, 120);

        if (isP1 && isP2) {
          g.lineStyle(4, C.p1H, 1); g.strokeRect(sx - 50, sy - 60, 100, 120);
          g.lineStyle(4, C.p2H, 1); g.strokeRect(sx - 46, sy - 56, 92, 112);
        } else if (isP1) {
          g.lineStyle(4, C.p1H, 1); g.strokeRect(sx - 50, sy - 60, 100, 120);
        } else if (isP2) {
          g.lineStyle(4, C.p2H, 1); g.strokeRect(sx - 50, sy - 60, 100, 120);
        } else {
          g.lineStyle(2, 0x555555, 1); g.strokeRect(sx - 50, sy - 60, 100, 120);
        }

        if (G.cSSpr[i]) {
          G.cSSpr[i].setPosition(sx, sy);
        }
      }
    }

    if (G.cSel[0].ok && G.cSel[1].ok && !G.waitSong) {
      G.waitSong = 1;
      setTimeout(() => { state.v = STATE.SONGSEL; G.waitSong = 0; drawSongSelScreen(s); }, 750);
    }
  } else if (state.v === STATE.SONGSEL) {
    if (justPressed.P1_U || justPressed.P2_U) {
      playMenuBlip();
      G.sSng = (G.sSng - 1 + SONGS.length) % SONGS.length;
      playSongPreview(s, G.sSng);
    }
    if (justPressed.P1_D || justPressed.P2_D) {
      playMenuBlip();
      G.sSng = (G.sSng + 1) % SONGS.length;
      playSongPreview(s, G.sSng);
    }
    if (justPressed.START1 || justPressed.START2 || justPressed.P1_1 || justPressed.P2_1) {
      if (SONGS.length > 0) {
        playMenuSelect();
        state.v = STATE.DIFFSEL;
        drawDiffSelScreen(s);
        return; // Prevent running the rest of the block on destroyed objects
      }
    }

    if (G.sLGfx && G.sLItm) {
      const g = G.sLGfx; g.clear();
      for (let i = 0; i < SONGS.length; i++) {
        const isSel = i === G.sSng;
        const sy = 200 + i * 80;
        const sx = 600;

        g.fillStyle(isSel ? 0xFFD166 : 0x111111, 1);
        if (isSel) g.lineStyle(4, 0xffffff, 1);
        else g.lineStyle(2, 0x555555, 1);
        g.fillRoundedRect(sx - 160, sy - 30, 320, 60, 2);
        g.strokeRoundedRect(sx - 160, sy - 30, 320, 60, 2);

        const t = G.sLItm[i];
        if (t.isSel !== isSel) {
          t.isSel = isSel;
          t.name.setColor(isSel ? '#000000' : '#ffffff').setStroke('#000', isSel ? 0 : 2);
          t.meta.setColor(isSel ? '#333333' : '#aaaaaa');
        }
        t.name.setPosition(sx, sy - 10);
        t.meta.setPosition(sx, sy + 15);
      }
    }
  } else if (state.v === STATE.DIFFSEL) {
    if (justPressed.P1_U || justPressed.P2_U) {
      playMenuBlip();
      if (G.diff > 0) G.diff--;
    }
    if (justPressed.P1_D || justPressed.P2_D) {
      playMenuBlip();
      if (G.diff < 2) G.diff++;
    }
    if (justPressed.START1 || justPressed.START2 || justPressed.P1_1 || justPressed.P2_1) {
      if (!G.pendingStart && SONGS.length > 0) {
        if (G.pMus) { G.pMus.stop(); G.pMus = null; }
        if (G.mMus) { G.mMus.stop(); G.mMus = null; }
        playCoinStart();
        G.pendingStart = 1;
        unpack(SONGS[G.sSng].data).then(song => {
          G.midiText = song;
          G.nSng = decode(song);
          G.pendingStart = 0;
          startBattle();
        });
        return;
      }
    }

    if (G.dLGfx && G.dLItm) {
      const g = G.dLGfx; g.clear();
      for (let i = 0; i < 3; i++) {
        const isSel = i === G.diff;
        const sy = 220 + i * 80;
        const sx = 600;

        g.fillStyle(isSel ? 0xFFD166 : 0x111111, 1);
        if (isSel) g.lineStyle(4, 0xffffff, 1);
        else g.lineStyle(2, 0x555555, 1);
        g.fillRoundedRect(sx - 120, sy - 30, 240, 60, 2);
        g.strokeRoundedRect(sx - 120, sy - 30, 240, 60, 2);

        const t = G.dLItm[i];
        if (t.isSel !== isSel) {
          t.isSel = isSel;
          t.setColor(isSel ? '#000000' : '#ffffff').setStroke('#000', isSel ? 0 : 2);
        }
        t.setPosition(sx, sy);
      }
    }
  } else if (state.v === STATE.BATTLE) {
    updateBattle(delta);
  } else if (state.v === STATE.WIN) {
    state.winT += delta;
    if (state.winT >= 5000 && G.winText && G.winText.alpha === 0) {
      G.winText.setAlpha(1);
    }
    if (G.winText && G.winText.alpha > 0) {
      G.winText.setVisible(state.t % 800 < 400); // blinking
    }

    if (G.sLen && getSongTime() >= G.sLen) {
      if (G.music) { G.music.stop(); G.music = null; }
      const skip = 40 + Mrnd() * 20; // 40-60s
      G.audS = G.titL.scene.sound.context.currentTime - skip;
      G.music = playMidi(G.titL.scene.sound.context, G.midiText, () => {}, skip);
    }

    if (state.winT >= 5000 && (justPressed.START1 || justPressed.START2 || justPressed.P1_1 || justPressed.P2_1)) {
      if (G.music) { G.music.stop(); G.music = null; }
      state.v = STATE.TITLE;
      drawTitleScreen(s);
      startMenuMusic();
    }
  }

  drawDynamicElements();
  animateCharacters(delta);
  updateCamera();

}

function drawDynamicElements() {
  drawTugGfx();
}

function animateCharacters(delta) {
  const bob = state.v === STATE.TITLE ? 0 : Msin(state.t * 0.005) * 2;
  for (let i = 0; i < 2; i++) {
    const p = players[i];
    const g = G.pLyrs[i];
    if (!g) continue;

    // Decay pulse offset back to center (fast snap-back)
    if (p.pT > 0) {
      p.pT = Mmax(0, p.pT - delta * 0.008);
      const ease = p.pT * p.pT; // quadratic ease-out
      p.pDx *= ease > 0 ? Mpow(0.92, delta / 16) : 0;
      p.pDy *= ease > 0 ? Mpow(0.92, delta / 16) : 0;
    } else {
      p.pDx = 0;
      p.pDy = 0;
    }

    if (p.slOut) {
      p.slideOffset = Mmin(p.slTgt, (p.slideOffset || 0) + delta * 2.5);
      if (p.slideOffset >= p.slTgt) {
        p.slOut = 0;
        p.name = p.nNam;
        p.sprites = p.nSpr;
        p.pIdx = 0;
        p.danceTimer = 1000;
        if (g) { g.clear(); dsp(g, p.sprites[0], 0, 0, true); }
      }
    } else {
      if (p.slideOffset > 0) p.slideOffset = Mmax(0, p.slideOffset - delta * 2.5);
    }

    if ((state.v === STATE.CHARSEL || state.v === STATE.SONGSEL || state.v === STATE.DIFFSEL || (state.v === STATE.WIN && i === state.winner)) && !p.slOut && p.sprites.length > 0) {
      p.danceTimer = (p.danceTimer || 0) + delta;
      const danceInterval = state.v === STATE.CHARSEL ? 600 : (state.v === STATE.WIN ? 350 : 400);
      if (p.danceTimer >= danceInterval) {
        p.danceTimer -= danceInterval;
        p.pIdx = (p.pIdx + 1) % p.sprites.length;
        if (g) { g.clear(); dsp(g, p.sprites[p.pIdx], 0, 0, true); }
      }
    }

    if (state.v === STATE.BATTLE && p.combo > 4) {
      p.cmbScale = Mmax(1, (p.cmbScale || 1) - delta * 0.003);
      if (!p.cmbT) {
        p.cmbT = cTxt(g.scene, p.center.x, 260, p.combo + '\nCOMBO', 42, '#FFD166', 1).setStroke('#EF476F', 8).setAlign('center');
        G.fxL.add(p.cmbT);
      } else {
        p.cmbT.setText(p.combo + '\nCOMBO').setScale(p.cmbScale).setPosition(p.center.x, 260 + Msin(state.t * 0.01) * 8);
      }
    } else if (p.cmbT) {
      p.cmbT.destroy();
      p.cmbT = null;
    }

    let cx = p.center.x, cy = p.center.y;
    if (state.v === STATE.SONGSEL || state.v === STATE.DIFFSEL) { cx = i === 0 ? 160 : 320; cy = 400; }

    g.x = cx + p.pDx + (i === 0 ? -(p.slideOffset || 0) : (p.slideOffset || 0));
    g.y = cy + bob - 40 + p.pDy;
  }
}

/* Trigger a dance pose change for the player on a successful note hit */
function triggerDancePose(pi, dir) {
  const p = players[pi];
  const numPoses = p.sprites.length;
  if (numPoses <= 0) return;

  // Map direction to pose index, cycling if fewer poses than 4 arrows
  const newPose = dir % numPoses;
  p.pIdx = newPose;

  // Redraw the sprite with the new pose
  const g = G.pLyrs[pi];
  if (g) {
    g.clear();
    const pose = p.sprites[p.pIdx];
    dsp(g, pose, 0, 0, true);
  }

  // Start pulsation: random direction snap
  const angle = Mrnd() * MPI * 2;
  const strength = 8 + Mrnd() * 6; // 8-14px snap
  p.pDx = Mcos(angle) * strength;
  p.pDy = Msin(angle) * strength;
  p.pT = 1.0;
}

function getSongTime() {
  const ctx = G.titL?.scene?.sound?.context;
  if (!ctx || !G.audS) return 0;
  return ctx.currentTime - G.audS;
}

function updateCamera() {
  if (!G.cam) return;
  let tx = W / 2, ty = 300, tz = 1;
  if (state.v === STATE.BATTLE) {
    const songT = getSongTime();
    const hasNotes = players[0].notes.length > 0 || players[1].notes.length > 0;
    if (hasNotes) {
      const turn = 1 - ((((songT + TRAVEL_TIME) / SEC_LEN) | 0) % 2);
      tx = turn === 0 ? 300 : 500;
      ty = 285;
      tz = 1.15;
    } else {
      tx = W / 2;
      ty = 300;
      tz = 1;
    }
  } else if (state.v === STATE.CHARSEL) {
    tx = W / 2;
    ty = 330;
    tz = 1.05;
  } else if (state.v === STATE.WIN) {
    tx = state.winner === 0 ? 300 : 500;
    ty = 350;
    tz = 1.35;
  }
  G.camX += (tx - G.camX) * .07;
  G.camY += (ty - G.camY) * .07;
  G.camZ += (tz - G.camZ) * .06;
  G.cam.setZoom(G.camZ);
  G.cam.centerOn(G.camX, G.camY);
}

function updateBattle(delta) {
  if (!G.audS) return;
  const songT = getSongTime();
  const turn = 1 - (((songT / SEC_LEN) | 0) % 2);
  G.lastTurn = turn;

  while (G.nSpwn < G.notes.length && G.notes[G.nSpwn].time - TRAVEL_TIME <= songT) {
    const n = G.notes[G.nSpwn];
    players[n.turn].notes.push({ targetTime: n.time, dir: n.dir, hit: 0, dead: 0, gfx: null, y: 0 });
    G.nSpwn++;
  }

  // 1P Mode CPU hit automation for Player 0
  if (G.mode === '1p') {
    for (const n of players[0].notes) {
      if (!n.dead && !n.hit && Mabs(n.y - HIT_Y) < 14) {
        const acc = G.diff === 0 ? 0.75 : (G.diff === 1 ? 0.85 : 0.95);
        if (Mrnd() < acc) tryHit(0, n.dir, songT);
      }
    }
  }

  for (let pi = 0; pi < 2; pi++) {
    const p = players[pi];
    const xs = LANE_X[pi];
    const alive = [];
    for (const n of p.notes) {
      if (n.dead) { if (n.gfx) { n.gfx.destroy(); n.gfx = null; } continue; }
      const y = HIT_Y - (n.targetTime - songT) * (HIT_Y / TRAVEL_TIME);
      n.y = y;
      if (y > HIT_Y + HIT_WIN + 20) {
        n.dead = 1; n.hit = 1;
        onMiss(pi, n.dir);
        if (n.gfx) { n.gfx.destroy(); n.gfx = null; }
        continue;
      }
      if (!n.gfx) {
        n.gfx = G.fxL.scene.add.graphics();
        G.hudL.add(n.gfx);
      }
      n.gfx.clear();
      drawArrow(n.gfx, xs[n.dir], y, ARROW_SCALE, DIR_ROT[n.dir], ARROW_LIGHT[n.dir], ARROW_DARK[n.dir]);
      alive.push(n);
    }
    p.notes = alive;

    for (let d = 0; d < 4; d++) {
      if (p.aBnc && p.aBnc[d] > 0) {
        p.aBnc[d] = Mmax(0, p.aBnc[d] - delta * BOUNCE_DECAY);
      }
      const b = p.aBnc ? p.aBnc[d] : 0;
      const curScale = ARROW_SCALE * (1 + BOUNCE_SCALE * b);
      const curY = HIT_Y - BOUNCE_Y * b;
      const keys = p.dK ? p.dK[d] : [p.keys[d]];
      const isHuman = G.mode !== '1p' || pi === 1;
      const isHeld = isHuman && (keys.some(k => held[k]) || (G.mode === '1p' && pi === 1 && players[0].dK[d].some(k => held[k])));
      const isPressed = isHuman && (keys.some(k => justPressed[k]) || (G.mode === '1p' && pi === 1 && players[0].dK[d].some(k => justPressed[k])));
      const g = p.arrows[d];
      if (g) {
        g.clear();
        drawArrow(g, xs[d], curY, curScale, DIR_ROT[d],
          isHeld ? ARROW_LIGHT[d] : C.arrowL,
          isHeld ? ARROW_DARK[d] : C.arrowD);
      }
      if (G.mode !== '1p' || pi === 1) {
        if (isPressed) tryHit(pi, d, songT);
      }
    }
  }

  if (G.bar >= BAR_MAX || G.bar <= -BAR_MAX) endBattle();
  else if (G.sLen && songT >= G.sLen) endBattle();
}

function showJudgment(scene, pi, dir, rating) {
  if (!scene || !G.hudL) return;
  const x = LANE_X[pi][dir ?? 1], y = HIT_Y - 32;
  const col = rating === 'PERFECTO' ? '#ffd166' : (rating === 'BIEN' ? '#77dd55' : '#ff5577');
  const txt = scene.add.text(x, y, rating, { fontFamily: 'monospace', fontSize: '15px', color: col, fontStyle: 'bold' }).setOrigin(0.5);
  txt.setStroke('#000', 4);
  txt.setDepth(150);
  G.hudL.add(txt);

  scene.tweens.add({
    targets: txt,
    y: y - 28,
    alpha: 0,
    scale: rating === 'PERFECTO' ? 1.25 : 1.05,
    duration: 380,
    ease: 'Power2',
    onComplete: () => txt.destroy()
  });

  if (rating === 'PERFECTO') {
    for (let i = 0; i < 6; i++) {
      const p = scene.add.rectangle(x, y, 4, 4, [0xffd166, 0xff5577, 0x77dd55, 0x29aefd][i % 4]);
      p.setDepth(150);
      G.hudL.add(p);
      const angle = (i / 6) * MPI * 2;
      const speed = 25 + Mrnd() * 20;
      scene.tweens.add({
        targets: p,
        x: x + Mcos(angle) * speed,
        y: y + Msin(angle) * speed,
        alpha: 0,
        scale: 0.2,
        duration: 300,
        ease: 'Quad.easeOut',
        onComplete: () => p.destroy()
      });
    }
  }
}

function tryHit(pi, dir, songT) {
  const p = players[pi];
  let best = null, bestDist = Infinity;
  for (const n of p.notes) {
    if (n.dead || n.hit || n.dir !== dir) continue;
    const dist = Mabs(n.y - HIT_Y);
    if (dist < bestDist && dist < HIT_WIN) { bestDist = dist; best = n; }
  }
  if (best) {
    best.hit = 1;
    best.dead = 1;
    if (best.gfx) { best.gfx.destroy(); best.gfx = null; }
    if (p.aBnc) p.aBnc[dir] = 1.0;
    let dmg;
    if (bestDist < PERFECT_WIN) {
      dmg = DMG_PERFECT; p.perfect++; p.score += 100;
      showJudgment(G.titL.scene, pi, dir, 'PERFECTO');
    } else {
      dmg = DMG_GOOD; p.good++; p.score += 50;
      showJudgment(G.titL.scene, pi, dir, 'BIEN');
    }
    p.combo++;
    p.cmbScale = 1.6;
    G.bar = clamp(G.bar + (pi === 0 ? dmg : -dmg), -BAR_MAX, BAR_MAX);
    triggerDancePose(pi, dir);
  } else {
    onMiss(pi, dir);
    triggerDancePose(pi, dir);
  }
}

function onMiss(pi, dir) {
  const p = players[pi];
  p.miss++;
  p.combo = 0;
  G.bar = clamp(G.bar + (pi === 0 ? -MISS_PEN : MISS_PEN), -BAR_MAX, BAR_MAX);
  showJudgment(G.titL.scene, pi, dir ?? 1, 'FALLO');
  playSynth(150, 40, [.15, .2], [.2, .001], [.2]);
}

function playSynth(f1, f2, dur, g2, g3) {
  const ctx = G.titL?.scene?.sound?.context;
  if (!ctx) return;
  const play = () => {
    const t0 = ctx.currentTime;
    const o = ctx.createOscillator(), g = ctx.createGain();
    o.type = 'square';
    o.frequency.setValueAtTime(f1, t0);
    o.frequency.exponentialRampToValueAtTime(f2, t0 + dur[0]);
    if (dur[2]) o.frequency.setValueAtTime(dur[2], t0 + dur[0]);

    g.gain.setValueAtTime(g2[0], t0);
    g.gain.linearRampToValueAtTime(g2[1], t0 + g3[0]);
    if (g3.length > 1) {
      g.gain.setValueAtTime(g3[1], t0 + g3[2]);
      g.gain.exponentialRampToValueAtTime(g3[3], t0 + dur[1]);
    }

    o.connect(g);
    g.connect(ctx.destination);
    o.start(t0); o.stop(t0 + dur[1]);
  };
  if (ctx.state === 'suspended') ctx.resume().then(play).catch(() => {});
  else play();
}

// Menu navigation blip sound
function playMenuBlip() {
  playSynth(440, 880, [.05, .1], [.08, .001], [.1]);
}

// Menu confirmation sound (distinct from navigation)
function playMenuSelect() {
  playSynth(660, 1320, [.08, .15], [.1, .001], [.15]);
}

// Arcade coin / match start sound
function playCoinStart() {
  playSynth(987.77, 987.77, [.08, .5, 1318.51], [.0, .1], [.02, .1, .08, .001]);
}

// Match countdown tones (3 -> 2 -> 1 -> Title Logo)
function playCountdownTone(step) {
  const f = [523.25, 659.25, 783.99, 1046.5][step];
  if (step < 3) playSynth(f, f, [.12, .26], [.15, .001], [.26]);
  else playSynth(f, f, [.1, .6, 1567.98], [.0, .18], [.02, .18, .1, .001]);
}

/* === MIDI PLAYBACK (kept from prior) === */
function playSongPreview(s, songIdx) {
  if (G.pMus) { G.pMus.stop(); G.pMus = null; }
  if (G.mMus) { G.mMus.stop(); G.mMus = null; }
  G.previewNonce = (G.previewNonce || 0) + 1;
  const nonce = G.previewNonce;
  unpack(SONGS[songIdx].data).then(data => {
    if (state.v !== STATE.SONGSEL) return;
    if (G.sSng !== songIdx) return;
    if (G.previewNonce === nonce) {
      const ctx = s.sound.context;
      G.pMus = playMidi(ctx, data);
    }
  });
}

async function unpack(data) {
  const binary = atob(data.replace(/-/g, '+').replace(/_/g, '/'));
  const bytes = Uint8Array.from(binary, c => c.charCodeAt(0));
  const stream = new Blob([bytes]).stream().pipeThrough(new DecompressionStream('deflate-raw'));
  return new Response(stream).text();
}

function variable(data, state) {
  let value = 0, digit;
  do {
    digit = A.indexOf(data[state.pos++]);
    // if (digit < 0) throw Error('invalid MIDI varint');
    if (digit !== Z) value = value * Z + digit;
  } while (digit !== Z);
  return value;
}

function fixed(data, state, width) {
  let value = 0;
  for (let i = 0; i < width; i++) {
    const digit = A.indexOf(data[state.pos++]);
    // if (digit < 0) throw Error('invalid MIDI field');
    value = value * B + digit;
  }
  return value;
}

function decode(data) {
  const parts = data.split('|');
  // if (parts.length !== 4 || parts[0] !== 'M5') throw Error('invalid MIDI header');
  const division = fixed(parts[1], { pos: 0 }, 2), dictionary = [];
  const ds = { pos: 0 }, count = A.indexOf(parts[2][ds.pos++]);
  for (let i = 0; i < count; i++) dictionary.push(variable(parts[2], ds));
  const body = parts[3], st = { pos: 0 }, events = [];
  let tick = 0;
  while (st.pos < body.length) {
    const kind = body[st.pos++];
    tick += variable(body, st);
    if (kind === 'T') events.push({ kind, tick, tempo: fixed(body, st, 3) * 10 });
    else if (kind === 'N' || kind === 'n') {
      const channel = A.indexOf(body[st.pos++]), pitch = fixed(body, st, 2), level = A.indexOf(body[st.pos++]);
      events.push({ kind: 'N', tick, channel, pitch, level, duration: kind === 'n' ? dictionary[A.indexOf(body[st.pos++])] : variable(body, st) });
    } else if (kind === 'G') {
      const channel = A.indexOf(body[st.pos++]), count = variable(body, st), flags = A.indexOf(body[st.pos++]);
      const pitches = [];
      for (let i = 0; i < count; i++) {
        if (!i) pitches.push(fixed(body, st, 2));
        else {
          const delta = A.indexOf(body[st.pos++]);
          pitches.push(delta === Z ? fixed(body, st, 2) - 128 : pitches[i - 1] + delta - 45);
        }
      }
      const levels = flags & 1 ? Array(count).fill(A.indexOf(body[st.pos++])) : pitches.map(() => A.indexOf(body[st.pos++]));
      const durations = flags & 2 ? Array(count).fill(flags & 4 ? dictionary[A.indexOf(body[st.pos++])] : variable(body, st)) : pitches.map(() => variable(body, st));
      for (let i = 0; i < count; i++) events.push({ kind: 'N', tick, channel, pitch: pitches[i], level: levels[i], duration: durations[i] });
    } else if (kind === 'E') return { division, events, endTick: tick };
    // else throw Error('invalid MIDI event');
  }
  // throw Error('missing MIDI end');
}

function secondsAt(tick, tempos, division) {
  let tempo = 500000, from = 0, seconds = 0;
  for (const t of tempos) {
    if (t.tick > tick) break;
    seconds += (t.tick - from) * tempo / division / 1e6;
    from = t.tick;
    tempo = t.tempo;
  }
  return seconds + (tick - from) * tempo / division / 1e6;
}

function noise(ctx) {
  const buffer = ctx.createBuffer(1, ctx.sampleRate, ctx.sampleRate), data = buffer.getChannelData(0);
  for (let i = 0; i < data.length; i++) data[i] = Mrnd() * 2 - 1;
  return buffer;
}

function oscillator(ctx, type, frequency, output, time, stop, detune = 0) {
  const source = ctx.createOscillator();
  source.type = type;
  source.frequency.setValueAtTime(frequency, time);
  source.detune.setValueAtTime(detune, time);
  source.connect(output);
  source.start(time);
  source.stop(stop);
  return source;
}

function profile(p) { // p = program
  if (p === 12 || p === 115) return { type: 'mallet', cut: 5500, attack: .003, release: .16 };
  if (p >= 32 && p < 40) return { type: 'bass', cut: 900, attack: .008, release: .1 };
  if (p >= 56 && p < 72) return { type: 'brass', cut: 2100, attack: .035, release: .11 };
  if (p >= 16 && p < 32) return { type: 'pluck', cut: 2600, attack: .006, release: .13 };
  if (p >= 8 && p < 16) return { type: 'mallet', cut: 5000, attack: .003, release: .14 };
  if (p >= 24 && p < 32) return { type: 'pluck', cut: 1800, attack: .008, release: .15 };
  if (p >= 40 && p < 56) return { type: 'string', cut: 1800, attack: .045, release: .18 };
  if (p >= 80 && p < 96) return { type: 'pad', cut: 1400, attack: .08, release: .3 };
  return { type: 'piano', cut: 3200, attack: .004, release: .2 };
}

function drum(ctx, buffer, note, filter, time, length) {
  const finish = time + Mmin(.2, Mmax(.04, length));
  if (note < 42) {
    const source = oscillator(ctx, 'sine', 140, filter, time, finish);
    source.frequency.exponentialRampToValueAtTime(46, time + .11);
    return;
  }
  const source = ctx.createBufferSource(), drumFilter = ctx.createBiquadFilter();
  source.buffer = buffer;
  drumFilter.type = note < 46 ? 'bandpass' : 'highpass';
  drumFilter.frequency.value = note < 46 ? 1800 : 6500;
  drumFilter.Q.value = 1.2;
  source.connect(drumFilter);
  drumFilter.connect(filter);
  source.start(time);
  source.stop(finish);
}

function playNote(ctx, buffer, master, channel, note, time, length) {
  const style = profile(channel.program), finish = time + length + style.release + .03;
  const level = Mmin(.14, note.level / 15 * channel.volume / 127 * channel.expression / 127 * .16);
  const amp = ctx.createGain(), filter = ctx.createBiquadFilter(), panner = ctx.createStereoPanning ? null : null;
  amp.gain.setValueAtTime(.0001, time);
  amp.gain.linearRampToValueAtTime(Mmax(.0001, level), time + style.attack);
  amp.gain.setValueAtTime(Mmax(.0001, level * .7), time + Mmax(style.attack, length * .65));
  amp.gain.exponentialRampToValueAtTime(.0001, time + length + style.release);
  filter.type = 'lowpass';
  filter.frequency.setValueAtTime(style.cut, time);
  filter.Q.value = style.type === 'brass' ? 2 : .7;
  filter.connect(amp);
  if (panner) {
    panner.pan.setValueAtTime((channel.pan - 64) / 64, time);
    amp.connect(panner); panner.connect(master);
  } else amp.connect(master);
  if (note.channel === 9) return drum(ctx, buffer, note.pitch, filter, time, length);
  const frequency = 440 * Mpow(2, (note.pitch - 69 + (channel.bend - 8192) / 4096) / 12);
  if (style.type === 'bass') {
    oscillator(ctx, 'sawtooth', frequency, filter, time, finish);
    oscillator(ctx, 'triangle', frequency / 2, filter, time, finish, -5);
  } else if (style.type === 'brass') {
    oscillator(ctx, 'sawtooth', frequency, filter, time, finish, -6);
    oscillator(ctx, 'square', frequency, filter, time, finish, 6);
  } else if (style.type === 'mallet') {
    oscillator(ctx, 'sine', frequency, filter, time, finish);
    oscillator(ctx, 'triangle', frequency * 2, filter, time, finish);
  } else if (style.type === 'pluck' || style.type === 'piano') {
    oscillator(ctx, 'triangle', frequency, filter, time, finish, -3);
    oscillator(ctx, 'sine', frequency * 2, filter, time, finish, 3);
  } else if (style.type === 'string' || style.type === 'pad') {
    oscillator(ctx, 'sawtooth', frequency, filter, time, finish, -8);
    oscillator(ctx, 'sawtooth', frequency, filter, time, finish, 8);
  } else oscillator(ctx, 'triangle', frequency, filter, time, finish);
}

function playMidi(ctx, data, onEnd = () => {}, skipTime = 0) {
  let song;
  try { song = decode(data); } catch (error) { console.error(error); onEnd(0); return; }
  if (!ctx) { onEnd(0); return; }
  const start = () => {
    const tempos = song.events.filter(event => event.kind === 'T');
    const notes = song.events.filter(event => event.kind === 'N').map(event => ({
      event,
      at: secondsAt(event.tick, tempos, song.division),
      length: Mmax(.025, secondsAt(event.tick + event.duration, tempos, song.division) - secondsAt(event.tick, tempos, song.division)),
    }));
    const master = ctx.createGain(), delay = ctx.createDelay(.4), feedback = ctx.createGain(), wet = ctx.createGain();
    master.gain.value = .8;
    delay.delayTime.value = .16;
    feedback.gain.value = .18;
    wet.gain.value = .1;
    master.connect(ctx.destination);
    master.connect(delay);
    delay.connect(feedback);
    feedback.connect(delay);
    delay.connect(wet);
    wet.connect(ctx.destination);
    const channels = Array.from({ length: 16 }, (_, number) => ({ program: PROGRAM[number] || 0, volume: 100, pan: 64, expression: 127, bend: 8192 }));
    const base = ctx.currentTime + .08, buffer = noise(ctx), lookAhead = 2, interval = 80;
    let cursor = 0;
    while(cursor < notes.length && notes[cursor].at < skipTime) cursor++;
    const end = Mmax(secondsAt(song.endTick, tempos, song.division), ...notes.map(note => note.at + note.length));
    const pump = () => {
      const limit = ctx.currentTime - base + lookAhead + skipTime;
      while (cursor < notes.length && notes[cursor].at <= limit) {
        const note = notes[cursor++];
        playNote(ctx, buffer, master, channels[note.event.channel], note.event, base + note.at - skipTime, note.length);
      }
      if (cursor === notes.length) clearInterval(timer);
    };
    let timer;
    pump();
    timer = setInterval(pump, interval);
    stopFn = () => { clearInterval(timer); try { master.disconnect(); } catch (e) {} };
    onEnd(end);
  };
  let stopFn = () => {};
  let started = 0;
  const safeStart = () => {
    if (started) return;
    started = 1;
    start();
  };
  if (ctx.state === 'suspended') {
    ctx.resume().then(safeStart).catch(() => {});
    const onStateChange = () => {
      if (ctx.state === 'running') {
        ctx.removeEventListener('statechange', onStateChange);
        safeStart();
      }
    };
    ctx.addEventListener('statechange', onStateChange);
  } else {
    safeStart();
  }
  return { stop: () => { if (typeof stopFn === 'function') stopFn(); } };
}
})();
