#!/usr/bin/env python3
"""Embed every .mid file from midis/ into game.js as packed var constants.

For each MIDI file it parses, encodes the full song (M5, original profile),
compresses it losslessly (deflate) and base64url-encodes it, exactly like the
browser-side unpack() in game.js expects. The generated block lives in game.js
between the two markers below; re-running this script replaces it in place.
"""

from __future__ import annotations

import argparse
import base64
import re
import sys
import zlib
from pathlib import Path

from convert import encode, parse_midi, seconds_between, tick_at_seconds, Note

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
GAME_JS = REPO_ROOT / "game.js"
MIDI_DIR = Path(__file__).resolve().parent / "midis"
BEGIN = "/* === MIDI SONGS (generated by tools/midi_to_string/embed.py) === */"
END = "/* === /MIDI SONGS === */"
OLD_LINE = re.compile(r'var MIDI_SONG = "[^"]+";\n')

SONG_LIST = [
    # (filename, start_second, end_second)
    # use None for end_second to go until the end
    ("barranquilla.mid", 0.0, 120.0),
    ("fruko_y_sus_tesos.mid", 0.0, 120.0),
    ("loba.mid", 0.0, 120.0),
    ("nuestra_cancion.mid", 0.0, 120.0),
]


def constant_name(path: Path) -> str:
    stem = re.sub(r"[^A-Za-z0-9]+", "_", path.stem).strip("_").upper()
    return "MIDI_SONG_" + stem


def pack(path: Path, start_sec: float | None, end_sec: float | None) -> tuple[str, int, int, float]:
    division, tempos, notes, end_tick = parse_midi(path)
    
    start_tick = 0
    if start_sec:
        start_tick = tick_at_seconds(tempos, division, start_sec)
    if end_sec is not None:
        end_tick = min(end_tick, tick_at_seconds(tempos, division, end_sec))
        
    if start_tick > 0 or end_sec is not None:
        # Filter and shift notes
        shifted = []
        for n in notes:
            if n.end <= start_tick or n.tick >= end_tick:
                continue
            new_tick = max(0, n.tick - start_tick)
            new_end = max(new_tick + 1, min(n.end, end_tick) - start_tick)
            shifted.append(Note(new_tick, new_end, n.channel, n.pitch, n.velocity))
        notes = shifted
        end_tick -= start_tick
        
        # Shift tempos
        shifted_tempos = []
        for t_tick, t_val in tempos:
            if t_tick <= start_tick:
                shifted_tempos = [(0, t_val)]
            else:
                if t_tick < end_tick + start_tick:
                    shifted_tempos.append((t_tick - start_tick, t_val))
        tempos = shifted_tempos

    payload, _, end_tick, _ = encode(
        division, tempos, notes, end_tick,
        no_drums=False, max_seconds=None, profile="original",
        polyphony_limit=None, drop_policy="preserve-bass-melody",
        drop_short_ms=0, min_velocity=0, quantize_ticks=0,
    )
    compressed = base64.urlsafe_b64encode(zlib.compress(payload.encode(), 9)).decode()
    seconds = seconds_between(0, end_tick, tempos, division)
    return compressed, len(compressed), len(notes), seconds


def build_block(entries: list[tuple[str, str, int, float]]) -> str:
    lines = [BEGIN]
    lines.append("// Generated automatically - do not edit by hand.")
    lines.append("// Re-run: python tools/midi_to_string/embed.py")
    lines.append("// Each constant packs one .mid losslessly (M5 -> deflate -> base64url).")
    for name, packed, size, seconds in entries:
        lines.append(f"// {name}: {size} chars base64, about {seconds:.0f}s of music.")
    lines.append("// var MIDI_SONG is the default song played by create(); swap it to any")
    lines.append("// MIDI_SONG_* below to make the game play that track instead.")
    lines.append("")
    for name, packed, _, _ in entries:
        lines.append(f'var {name} = "{packed}";')
    default_song = "MIDI_SONG_FRUKO_Y_SUS_TESOS"
    if not any(e[0] == default_song for e in entries):
        default_song = entries[0][0] if entries else '""'
    lines.append(f'var MIDI_SONG = {default_song};')
    lines.append(END)
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--midis", type=Path, default=MIDI_DIR, help="directory containing .mid files")
    parser.add_argument("--game-js", type=Path, default=GAME_JS, help="path to game.js to patch")
    args = parser.parse_args()
    
    entries = []
    for filename, start_sec, end_sec in SONG_LIST:
        path = args.midis / filename
        if not path.is_file():
            print(f"warning: {path} not found, skipping", file=sys.stderr)
            continue
        packed, size, note_count, seconds = pack(path, start_sec, end_sec)
        entries.append((constant_name(path), packed, size, seconds))
        print(f"{path.name}: {note_count} notes -> {size} chars base64 ({seconds:.0f}s)", file=sys.stderr)

    if not entries:
        print("no .mid files processed", file=sys.stderr)
        return 1

    block = build_block(entries)
    text = args.game_js.read_text()
    if BEGIN in text and END in text:
        text = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), block, text, flags=re.S)
    else:
        if not OLD_LINE.search(text):
            print(f"could not find the existing var MIDI_SONG payload in {args.game_js}", file=sys.stderr)
            return 1
        text = OLD_LINE.sub(block, text, count=1)
    args.game_js.write_text(text)
    print(f"wrote {len(entries)} song constant(s) to {args.game_js}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())